### PR TITLE
Fix `abi3` conversion of `__complex__` classes

### LINKED ISSUE #3164: Inconsistent custom `__complex__` conversions with `abi3`
### Bug Description

Classes that are not `complex` but define `__complex__` convert to `num-complex` types successfully when the full C API is in use, but fail with varying `TypeError`s when the limited API is in use.

### Steps to Reproduce

This is a MWE PyO3 module (strictly the return value of `noop` is irrelevant, but I left it here for clarity):
```rust
use pyo3::prelude::*;

use num_complex::Complex64;

#[pyfunction]
fn noop(a: Complex64) -> Complex64 {
   a 
}

#[pymodule]
fn core(_py: pyo3::Python<'_>, module: &PyModule) -> PyResult<()> {
    module.add_function(wrap_pyfunction!(noop, module)?)?;
    Ok(())
}
```

In Python space, if I compile against the full API, classes that define `__complex__` will successfully convert:
```python
from pyo3_test import noop

class A:
    def __complex__(self):
        return 1j

noop(A())  # returns 1j
```

If I rebuild the extension in limited-API mode, I instead get a type error:
```text
TypeError                                 Traceback (most recent call last)
Cell In[1], line 7
      4     def __complex__(self):
      5         return 1j
----> 7 noop(A())

TypeError: argument 'a': must be real number, not A
```

### Backtrace

_No response_

### Your operating system and version

macOS 13.3.1

### Your Python version (`python --version`)

Python 3.10.6

### Your Rust version (`rustc --version`)

rustc 1.67.1 (d5a82bbd2 2023-02-07)

### Your PyO3 version

0.18.3

### How did you install python? Did you use a virtualenv?

From source, in a venv.

### Additional Info

The relevant conversions are here: https://github.com/PyO3/pyo3/blob/3ec966d97fad85ee048da5f68891552f14c06c52/src/conversions/num_complex.rs#L139-L166.
`PyComplex_AsCComplex` uses the full `__complex__` conversion machinery in CPython, but `PyComplex_RealAsDouble` only tests if the object is already of type `complex`, and if not, assumes it's real and uses the `__float__` conversion machinery, hence the "must be a real number" errors above.

Could we modify the abi3 conversion to do the full `__complex__` conversion before the rest of its logic if `PyComplex_Check` is false?  I'd be happy to make a PR.

### PR DESCRIPTION
**Pull request by jakelishman**
Python classes that were not `complex` but implemented the `__complex__` magic would have that method called via `PyComplex_AsCComplex` when running against the full API, but the limited-API version `PyComplex_RealAsDouble` does not attempt this conversion.  If the input object is not already complex, we can call the magic before proceeding.

Happy to modify if I've made a mess of testing strategy - I'm not sure I've managed to do it in the same style as other tests.

Fix #3164.

### CODE REVIEW

File: src/conversions/num_complex.rs [hunk 1]
```diff
@@ -152,6 +152,19 @@ macro_rules! complex_conversion {
 
                 #[cfg(any(Py_LIMITED_API, PyPy))]
                 unsafe {
+                    use crate::{intern, type_object::PyTypeInfo};
+
+                    let obj = if PyComplex::is_type_of(obj) {
+                        obj
+                    } else if let Ok(method) =
+                        obj.get_type().getattr(intern!(obj.py(), "__complex__"))
```
Comment (adamreichold) [inline src/conversions/num_complex.rs:160]: Why `.get_type().getattr(..)` instead of just `.getattr(..)`?

File: src/conversions/num_complex.rs [hunk 2]
```diff
@@ -152,6 +152,19 @@ macro_rules! complex_conversion {
 
                 #[cfg(any(Py_LIMITED_API, PyPy))]
                 unsafe {
+                    use crate::{intern, type_object::PyTypeInfo};
+
+                    let obj = if PyComplex::is_type_of(obj) {
```
Comment (adamreichold) [inline src/conversions/num_complex.rs:157]: Purely a style question, I think `obj.is_instance_of::<PyComplex>()` would be easier to read.

File: src/conversions/num_complex.rs [hunk 3]
```diff
@@ -152,6 +152,19 @@ macro_rules! complex_conversion {
...
+                        obj
+                    } else if let Ok(method) =
+                        obj.get_type().getattr(intern!(obj.py(), "__complex__"))
+                    {
+                        method.call1((obj,))?
+                    } else {
+                        // This will likely result in an error in `PyComplex_RealAsDouble`, but
```
Comment (adamreichold) [inline src/conversions/num_complex.rs:164]: I don't think this too helpful and would probably to just return the error of calling `__complex__` directly.

If I read https://docs.python.org/3/c-api/complex.html#c.PyComplex_AsCComplex correctly, we would also need to do more, e.g.

```rust
let obj = obj.is_instance_of::<PyComplex>() {
  obj
} else if let Ok(obj) = obj.method_call0(intern!(obj.py(), "__complex__")) {
  obj
} else {
  let num = obj.extract::<f64>()?;
  return Ok(Complex::from(num));
};
```

Comment (jakelishman) [reply src/conversions/num_complex.rs:164]: Oh sorry, my comment is poor here: in your case, `PyComplex_RealAsDouble` does this conversion in the same way that `PyComplex_AsCComplex` does, so the code would continue on to succeed if it's a valid float.

Do you prefer me to change the comment or to switch to your implementation?

File: src/conversions/num_complex.rs (hunk 1 above)
Comment (jakelishman) [reply src/conversions/num_complex.rs:160]: [The spec says magic methods are accessed off the type](https://docs.python.org/3/reference/datamodel.html#special-method-names), so I was trying to be consistent with this behaviour:
```python
class A:
    def __complex__(self):
        return 1j
a = A()
a.__complex__ = lambda self: 2j
print(complex(a))  # 1j
```

In saying this, though, I realise that I'm not invoking the descriptor protocol on access to the `__complex__` attribute of the type, if required, which is why I guess the word "roughly" is in:
> `x[i]` is roughly equivalent to `type(x).__getitem__(x, i)`

Does PyO3 have a convenient interface for manually invoking the descriptor protocol on an object? CPython does it very manually in its internal `_PyObject_LookupSpecial` method, which is what it typically uses to access `__complex__`.

File: src/conversions/num_complex.rs (hunk 2 above)
Comment (jakelishman) [reply src/conversions/num_complex.rs]: No problem - changed in b15573f2.

File: src/conversions/num_complex.rs (hunk 1 above)
Comment (jakelishman) [reply src/conversions/num_complex.rs]: I'd thought about this, but I was concerned about the additional logic in that for parsing `str` and subclasses.  I can swap it to that if you think it's preferable, likely with an catch to error out if we're given a string?  The current implementation is pretty similar to what CPython does (except for me forgetting to invoke the descriptor protocol right now), but I get that over-tight coupling between PyO3/CPython isn't ideal.

**Comment by DataTriny** [comment]
Hello @jakelishman 

Thank you for contributing to PyO3!

The project is undergoing changes on its licensing model to better align with the rest of the Rust crates ecosystem.

Before your work gets merged, please express your consent by leaving a comment on this [pull request](https://github.com/PyO3/pyo3/pull/3108).

Thank you!

File: src/conversions/num_complex.rs (hunk 1 above)
Comment (adamreichold) [reply src/conversions/num_complex.rs]: Yeah, this too much complexity, especially if we try to second guess it by avoid the string logic.

I am also not sure whether `.get_type().getattr(..)` only lacks the descriptor protocol compared to `_PyObject_LookupSpecial` which also seems to do MRO look-up via `_PyType_Lookup`?

To be honest, I wonder if the the current implementation is good enough and a comment on this being "almost" the same protocol as the one CPython uses.

File: src/conversions/num_complex.rs (hunk 3 above)
Comment (jakelishman) [reply src/conversions/num_complex.rs]: Sounds good: done in b30169ae and aa1dcb04.

File: src/conversions/num_complex.rs (hunk 1 above)
Comment (jakelishman) [reply src/conversions/num_complex.rs]: I think the MRO lookup functions correctly with `obj.get_type().getattr()` - the result of `obj.get_type()` is just a regular `PyTypeObject` so the subsequent `getattr` call should resolve the MRO.  I put in an inheritance test in aa1dcb0461ac428d0dc245fe4d3ad1b5e1322028, I put in the implementation of the descriptor protocol (unfortunately the `PyTypeObject` struct is non-limited API, so no `tp_descr_get` slot for us here) in a599e82e, but if you think that's too complex, I can just remove that commit.

**Comment by jakelishman** [comment]
I've pushed a couple more commits on the basis of the review.  I'm happy to revert the descriptor-resolution commit and replace it just with a comment about similarity not equality to CPython's implementation, if you'd rather.

File: src/conversions/num_complex.rs (hunk 1 above)
Comment (adamreichold) [reply src/conversions/num_complex.rs]: I think the code is fine and the tests are convincing.

I would like to avoid sinking this into this `extract` implementation. We should factor out a crate-wide (but internal) helper method, something like `lookup_special` implementing the whole `.get_type().attr(..)`-and-then-again dance starting from a name like `__complex__`.

Maybe as a method on `PyAny` that we could eventually (but not in this PR) make public?

> unfortunately the PyTypeObject struct is non-limited API, so no tp_descr_get slot for us here

I think this is fine for this use case as we already are in a lower performance fallback. For the general helper method, it would be nice to add both implementations (limited and non-limited API). But I do not want to steal your time as this is tangential to the issue you are working on, so a FIXME comment would work for me as well.

Comment (jakelishman) [reply src/conversions/num_complex.rs]: I'm happy to do that too, no worries (but thanks for the consideration!).  Would you prefer a separate clean PR for that implementation, then I can update this PR to use it after that's merged?

I'm not in any hurry on this PR so I've got time to follow whatever procedures you prefer.  I found the `__complex__` discrepancy because of a bug in our own code (we didn't mean to use the behaviour, but were incorrectly returning a single-valued Numpy array at a point we expected a scalar).  We fixed our bug, so we could immediately move to `abi3` regardless of this PR.

Comment (adamreichold) [reply src/conversions/num_complex.rs]: > Would you prefer a separate clean PR for that implementation, then I can update this PR to use it after that's merged?

I think it would be fine to do here as the PR is currently very self-contained and it is always nice to merge infrastructure together with at least one usage site.

**Comment by jakelishman** [comment]
A minor procedural question: this PR is getting a little messy in commit history, and with the CI failures, needs to be updated over `main`.  Do you prefer me to leave the history as-is and push an additional merge commit into this PR, or do you prefer me to rebase these commits back into a coherent story (1. add the new PyAny/ffi method, 2. fix the complex conversion)?

**Comment by adamreichold** [comment]
> A minor procedural question: this PR is getting a little messy in commit history, and with the CI failures, needs to be updated over `main`. Do you prefer me to leave the history as-is and push an additional merge commit into this PR, or do you prefer me to rebase these commits back into a coherent story (1. add the new PyAny/ffi method, 2. fix the complex conversion)?

We certainly prefer a coherent story and have explicit configured to not squash merges, so turning this back into two commits would be really helpful!

**Comment by jakelishman** [comment]
No trouble - I've just rebased down to two commits.

Just for visibility, there's a couple of my decisions that I think other maintainers might want to question:
- the naming/location/visibility of the new `PyAny::getattr_special`. I put it on `PyAny` because it made most sense to me, and the naming/visibility are from https://github.com/PyO3/pyo3/pull/3185#discussion_r1210574089.  Maybe since it's on `PyAny` rather than being a loose helper it might make more sense as a full `pub`?
- the return type of that method being `PyResult<Option<&PyAny>>` rather than `PyResult<&PyAny>` - it's not typically an immediate error if a magic method doesn't exist in my head, at least.

File: newsfragments/3185.fixed.md [hunk 4]
```diff
@@ -0,0 +1 @@
+Fix conversion of classes implementing `__complex__` to `Complex` when using `abi3`.
```
Comment (davidhewitt) [inline newsfragments/3185.fixed.md:1]:
```suggestion
Fix conversion of classes implementing `__complex__` to `Complex` when using `abi3` or PyPy.
```

**Review by davidhewitt — APPROVED** [review]
Thanks, the tests are great and I'm happy that the implementation is correct!

I have a couple of suggestions to round this off, I'm happy to see this merged when those are either addressed or dismissed.

**Comment by davidhewitt** [comment]
As for visibility, I suggest we keep `lookup_special` private for now until users give us a reason to make this public. `_PyObject_LookupSpecial` feels like something which is for diving into the weeds and it's not immediately clear to me when we'd want to recommend it to users over `self.get_type().getattr(...)` (plus descriptor) dance.

**Comment by jakelishman** [comment]
Well, I'm certainly glad that you mentioned `PyType_GetSlots` and how it might not work before Python 3.10.  It transpires that you're correct on the versioning and that it appears frequently because things like `method` are static types, so trying `PyType_GetSlots` on one of those fails to spot the descriptor.  Thanks for that advice - I'm fairly new to programming against the C API, and so I've not good great knowledge of all the available surface.

More importantly, though, it made me realise that `_PyObject_LookupSpecial` changed signature just very recently.  I thought I'd been running my tests using Python 3.9 locally, but I hadn't - I'd just been using 3.11, and CI only tests 3.11 so I hadn't noticed any issues.  Prior to 3.11, `_PyObject_LookupSpecial` is what's now called `_PyObject_LookupSpecialId`, and I don't think that's something we can bind against, because the IDs are shared static objects in the `PyRuntimeState` of the main interpreter.

What course of action would you like here?
- I could expose `_PyObject_LookupSpecial` in the FFI for Python 3.11+ only and have `PyAny::lookup_special` fallback to the getattr-based limited API form in lower CPythons, in addition to the limited API and PyPy?
- Alternatively, I could remove `_PyObject_LookupSpecial` from the FFI and use only a limited-API-safe version `PyAny::lookup_special`, since `_PyObject_LookupSpecial` might not be stable enough (and a special case for latest-Python-only in a probably non-performance-critical code path might be a bit messy).  I can switch this to a `PyType_GetSlots`-based implementation with appropriate checking of the heap-type flags for pre-3.10 CPythons to fallback to a slower getattr-based version. 

Fwiw, the complexity I'm finding here in correctly resolving non-slotted magic-method lookups across all Pythons strengthens the case for a central `PyAny::lookup_special` in my mind, for other PyO3-internal uses - there's so much subtlety I think it'd be very tricky to reproduce correctly elsewhere.

(All your other suggestions are easy and uncontentious to me.)

**Comment by jakelishman** [comment]
Yeah, I think that's what I'd have suggested if someone was contributing code on a project I maintained.  I'll write this all up and push a couple of new commits to show what it looks like.  Testing against older Pythons makes it look to me like I _may_ have found a bug in `Python::run`, but I'll investigate that a little more separately - it's totally orthogonal to this PR, except that the particular way I initially wrote the tests needed tweaking.

(Sorry this has got super deep in the weeds - I wasn't expecting that!  I can say that I'm having great fun learning way more about Python/CPython internals, though.)

**Comment by adamreichold** [comment]
> Testing against older Pythons makes it look to me like I may have found a bug in Python::run, but I'll investigate that a little more separately - it's totally orthogonal to this PR, except that the particular way I initially wrote the tests needed tweaking.

Please have a look at #2927 and #2891, maybe you hit one of those.

File: src/types/any.rs [hunk 5]
```diff
@@ -124,6 +124,56 @@ impl PyAny {
...
+            let attr_name = attr_name.into_py(py);
+            let ret = ffi::_PyObject_LookupSpecial(self.as_ptr(), attr_name.as_ptr());
+            if ret.is_null() {
+                // _PyObject_LookupSpecial doesn't set an exception on lookup failure, but should
+                // if there's an exception during evaluation of the attribute (such as during the
+                // descriptor resolution).
+                match PyErr::take(py) {
+                    Some(err) => Err(err),
+                    None => Ok(None),
+                }
```
[the remark this answers is not in the document]
Comment (jakelishman) [reply src/types/any.rs]: Ah thanks - this _felt_ like something that'd have a chained method, but I couldn't spot the correct one on `Option`.  Done in rebased befabb2e

**Comment by adamreichold** [comment]
Let's give it a whirl in the CI then.

bors try

File: src/types/any.rs [hunk 6]
```diff
@@ -124,6 +124,55 @@ impl PyAny {
...
+                if descr_get_ptr.is_null() {
+                    return Ok(Some(attr));
+                }
+                let descr_get: ffi::descrgetfunc = std::mem::transmute(descr_get_ptr);
+                let ret = descr_get(attr.as_ptr(), self.as_ptr(), self_type.as_ptr());
+                if ret.is_null() {
+                    Err(PyErr::fetch(py))
+                } else {
+                    Ok(Some(py.from_owned_ptr(ret)))
+                }
```
Comment (davidhewitt) [inline src/types/any.rs:167]: I think this could be

```suggestion
        py.from_owned_ptr_or_err(ret).map(Some)
```

File: src/types/any.rs [hunk 7]
```diff
@@ -124,6 +124,55 @@ impl PyAny {
...
+        let attr = if let Ok(attr) = self_type.getattr(attr_name) {
+            attr
+        } else {
+            return Ok(None);
+        };
+
+        // Manually resolve descriptor protocol.
+        unsafe {
+            if cfg!(Py_3_10)
+                || ffi::PyType_HasFeature(attr.get_type_ptr(), ffi::Py_TPFLAGS_HEAPTYPE) != 0
```
Comment (davidhewitt) [inline src/types/any.rs:153]: Given the `unsafe` isn't used in the slow paths, it might be nice to move it inside the fast path.

```suggestion
        if cfg!(Py_3_10)
            || unsafe { ffi::PyType_HasFeature(attr.get_type_ptr(), ffi::Py_TPFLAGS_HEAPTYPE) } != 0
        {
            unsafe { 
               ...
            }
```

File: src/types/any.rs [hunk 8]
```diff
@@ -124,6 +124,55 @@ impl PyAny {
...
+    where
+        N: IntoPy<Py<PyString>>,
+    {
+        let py = self.py();
+        let self_type = self.get_type();
+        let attr = if let Ok(attr) = self_type.getattr(attr_name) {
+            attr
+        } else {
+            return Ok(None);
+        };
```
Comment (davidhewitt) [inline src/types/any.rs:148]: let-else is going to be so nice once PyO3 gets to MSRV of 1.65... but that's going to be a long time yet! (We're just about to do a bump to 1.56 I think.)

**Review by davidhewitt — APPROVED** [review]
Nice one! I have just a couple of tiny code style suggestions for the new `lookup_special` body, otherwise this looks perfect.

`cargo test` on PyPy is known to not work, it's a deficiency on PyPy's side which I hope to resolve one day. We have a `pytests` crate which builds an extension module and runs a small set of tests, which PyPy does support.

File: src/types/any.rs (hunk 8 above)
Comment (adamreichold) [reply src/types/any.rs:148]: How did this get through the full CI though? Are we missing a feature configuration for the MSRV job?

Comment (adamreichold) [reply src/types/any.rs:148]: Yes, right. In such cases, personally, I actually prefer `match` as it gives "tigher" formatting even though it does "stutter" a bit:

```rust
let attr = match self_type.getattr(attr_name) {
  Ok(attr) => attr,
  Err(_err) => return Ok(None),
};
```

File: src/types/any.rs (hunk 7 above)
Comment (jakelishman) [reply src/types/any.rs]: Sounds good - fixed in 194d0c79.

**Comment by jakelishman** [comment]
There we go - style changes made.

> [about pypy]

Ah yeah, that'd explain it - I'll have a look at doing that properly next time round, thanks!

**Comment by adamreichold** [comment]
I think this is good to go now having collected two approvals with all threads resolved.

bors r+

**Comment by jakelishman** [comment]
Thanks for all the help, chaps!
