### PR TITLE
fix: Replace macro use in ordered_float tests

### LINKED ISSUE #5345: ordered-float tests fail
### Bug Description

I noticed as a result of Debian's automatic tests that the ordered-float feature tests fail on current main (https://github.com/PyO3/pyo3/commit/12a1792c4364466a0fda880252dffdc82655c1a5).

### Steps to Reproduce

`cargo test --all-targets --no-default-features --features ordered-float`

### Backtrace

```shell
error[E0432]: unresolved import `crate::py_run`
   --> src/conversions/ordered_float.rs:103:9
    |
103 |     use crate::py_run;
    |         ^^^^^^^^^^^^^ no `py_run` in the root
```

### Your operating system and version

Debian testing

### Your Python version (`python --version`)

Python 3.13.6

### Your Rust version (`rustc --version`)

rustc 1.86.0 (05f9846f8 2025-03-31) (built from a source tarball)

### Your PyO3 version

main (post-0.25.0)

### How did you install python? Did you use a virtualenv?

apt

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by tpoliaw**
The tests make use of the py_run macro which is only available with the
macros feature enabled.

While the py_run macro supports a wider range of requirements, the way
it is used in these tests is straightforward enough that it can be
replaced with a local function to prevent the macros feature needing to
be enabled.

Closes #5345

### CODE REVIEW

**Comment by tpoliaw** [comment]
Probably too late, I just read through the related comments on #5344 and I still think this is ok as a stand-alone change. The tests rely on the macro so requiring it makes some sense.

Would it be better to replace the macro uses so the tests run with no other features enabled or is it still clearer to use the shorthand version?

**Comment by tpoliaw** [comment]
Replacing the macro didn't look too bad so is possibly the better approach so the tests aren't skipped unexpectedly.

File: src/conversions/ordered_float.rs [hunk 1]
```diff
@@ -118,15 +128,7 @@ mod test_ordered_float {
                 Python::attach(|py| {
                     let f_py: Bound<'_, PyFloat>  = f.into_pyobject(py).unwrap();
 
-                    py_run!(
-                        py,
-                        f_py,
-                        &format!(
-                            "import math\nassert math.isclose(f_py, {})",
-                             inner_f as f64 // Always interpret the literal rs float value as f64
```
Comment (tpoliaw) [inline src/conversions/ordered_float.rs:126]: Need to replace the "as f64"

File: newsfragments/5602.misc.md
Comment (davidhewitt) [inline newsfragments/5602.misc.md:1]: I think as a tests-only change we can drop this file, I added `CI-skip-changelog` label.

**Comment by davidhewitt** [comment]
Thanks very much for this! Doing this got me experimenting, IIRC we gated `py_run!` behind the `macros` feature to avoid the optional dependencies.

Maybe we can simplify and do something like #5608, and then always allow `py_run!` macro to be defined?

File: src/conversions/ordered_float.rs [hunk 2]
```diff
@@ -101,12 +101,22 @@ float_conversions!(NotNan, f64, |val| NotNan::new(val)
...
     use proptest::prelude::*;
 
+    fn py_run<'py>(py: Python<'py>, script: String, locals: impl IntoPyDict<'py>) {
+        py.run(
+            &CString::new(script).unwrap(),
+            None,
+            Some(&locals.into_py_dict(py).unwrap()),
+        )
+        .unwrap()
+    }
```
Comment (davidhewitt) [inline src/conversions/ordered_float.rs]:
```suggestion
    fn py_run<'py>(py: Python<'py>, script: &CStr, locals: impl IntoPyDict<'py>) {
        py.run(
            script,
            None,
            Some(&locals.into_py_dict(py).unwrap()),
        )
        .unwrap()
    }
```

Comment (tpoliaw) [reply src/conversions/ordered_float.rs]: I'll have a look at fixing the calls to work with this

**Comment by tpoliaw** [comment]
I think we still need `format` in a couple of places where we're building the strings with args, but have replaced the others with cstr literals.
