### PR TITLE
Remove unsound return of borrowed objects

### LINKED ISSUE #883: Returning borrowed objects is probably always unsound
EDIT (Mistakenly posted the issue template, sorry if it looks weird in email notifications)

While digging around with lifetimes and borrowed objects just now I realised that using `py::from_borrowed_ptr()` for `PyDict::get_item` is fundamentally unsound.

If a user deletes the item from the dict after getting it, the user has easy access in safe code to a dangling PyObject.

This can easily be observed by the following code:

```rust
#[test]
fn test_dict_borrowed_object() {
    use crate::{ffi, AsPyPointer};

    let gil = Python::acquire_gil();
    let py = gil.python();

    let arr = [("a", 1234567)];
    let py_map = arr.into_py_dict(py);

    let item = py_map.get_item("a").unwrap();

    // The value has a ref count of 1, because only the dict owns it still
    assert_eq!(unsafe { ffi::Py_REFCNT(item.as_ptr()) }, 1);

    // Deleting it means the refcount goes to 0 and the borrowed object `item` is now dangling
    py_map.del_item("a").unwrap();

    // I know that Py_REFCNT will never return 0; this is more for illustration.
    // On my machine Py_REFCNT returns 2468790368784 here, but I don't know if it's deterministic.
    assert_eq!(unsafe { ffi::Py_REFCNT(item.as_ptr()) }, 0);

    // User could still use `item` and cause a segfault...
}
```

My feeling from this is that this means that returning borrowed objects from our Py* Rust APIs is probably almost always unsound for similar reasons.

We might want to convert these functions to return owned pointers.

### PR DESCRIPTION
**Pull request by davidhewitt**
As discussed in #883, I think these are a few cases where we should be converting borrowed objects to owned objects for safety reasons.

Closes #883.

### CODE REVIEW

**Comment by davidhewitt** [comment]
In case we're worried about performance regressions, I made some benchmarks (from #891). I ran them on `master`, this PR, #887 , and also #887 with this PR cherry-picked on top.

Results: 

  | master | no-borrowed-objects | new-nativetypes | new-nativetypes + no-borrowed-objects
-- | -- | -- | -- | --
dict_get_item | 3160 +- 820 | 3120 +- 750 | 2280 +- 1600 | 2530 +- 1260
iter_dict | 3680 +- 1000 | 3720 +- 700 | 1620 +- 700 | 2330 +- 560
iter_list | 2090 +- 550 | 2340 +- 1300 | 1080 +- 590 | 1610 +- 430
list_get_item | 1080 +- 410 | 1100 +- 400 | 470 +- 230 | 740 +- 320
drop_many_objects | 4.4 +- 1.2 | 4.8 +- 0.4 | 3.8 +- 0.4 | 3.7 +- 0.9
iter_tuple | 780 +- 110 | 760 +- 560 | 790 +- 300 | 820 +- 340
tuple_get_item | 960 +- 250 | 950 +- 100 | 420 +- 200 | 580 +- 330

Conclusions:

- This PR does now slow down vs master much (maybe just a little)
- `new-nativetypes` is much much faster than master (yay!)
- Applying this PR after `new-nativetypes` causes greater slowdown because the difference between borrowed and owned objects is greater after that. But the combination is still faster than master 😄 

So I would be really keen to see this safety gap closed. If we are *really* worried about performance we could add `unsafe fn get_item_unborrowed` to `PyList` etc., but I don't think the performance difference is so great that it's worth it.

File: src/types/tuple.rs [hunk 1]
```diff
@@ -70,20 +70,19 @@ impl PyTuple {
...
     /// Panics if the index is out of range.
     pub fn get_item(&self, index: usize) -> &PyAny {
-        // TODO: reconsider whether we should panic
-        // It's quite inconsistent that this method takes `Python` when `len()` does not.
         assert!(index < self.len());
         unsafe {
-            self.py()
-                .from_borrowed_ptr(ffi::PyTuple_GET_ITEM(self.as_ptr(), index as Py_ssize_t))
+            // PyTuple_GET_ITEM return borrowed ptr; must make owned for safety (see #890).
+            let ptr = ffi::PyTuple_GET_ITEM(self.as_ptr(), index as Py_ssize_t);
```
Comment (kngwyu) [inline src/types/tuple.rs:76]: Do we need this trick even for tuple? :thinking:

Comment (davidhewitt) [reply src/types/tuple.rs:76]: It's less critical for tuple I think, because it's immutable from Python - but it's possible to mutate a tuple in C / Rust!

I felt for extra peace of mind I would make this owned too. I can undo this one if you prefer.

Comment (kngwyu) [reply src/types/tuple.rs:76]: > I can undo this one if you prefer.

I don't think it's the problem of whether I prefer or do not prefer it.
Since we don't have an API for deleting an object(= `del_item` returns an error), I don't see a clear advantage for using `owned` here.

Comment (davidhewitt) [reply src/types/tuple.rs:76]: Ok. 👍

**Comment by davidhewitt** [comment]
I've undone the change for `PyTuple::get_item`

**Comment by kngwyu** [comment]
Thank you!
