### PR TITLE
Free-threaded build config fixes

### LINKED ISSUE #4709: Setting configs incompatible with Py_GIL_DISABLED should error harder
I noticed working on cryptography, which tries to build against the Python 3.7 limited API, that it has this pair of configs set:

```
cargo:rustc-cfg=Py_3_7
cargo:rustc-cfg=Py_GIL_DISABLED
```

This leads to confusing compiler errors due to the conditional compilation in pyo3-ffi not being written to handle this case since it's impossible:

```
DEBUG    Compiling cryptography-x509 v0.1.0 (/Users/goldbaum/Documents/cryptography/src/rust/cryptography-x509)
DEBUG error[E0432]: unresolved import `crate::PyMutex`
DEBUG  --> /Users/goldbaum/Documents/pyo3/pyo3-ffi/src/object.rs:3:5
DEBUG   |
DEBUG 3 | use crate::PyMutex;
DEBUG   |     ^^^^^^^^^^^^^^ no `PyMutex` in the root
DEBUG
DEBUG error[E0425]: cannot find value `_Py_IMMORTAL_REFCNT` in this scope
DEBUG    --> /Users/goldbaum/Documents/pyo3/pyo3-ffi/src/object.rs:162:20
DEBUG     |
DEBUG 29  | const _Py_IMMORTAL_REFCNT_LOCAL: u32 = u32::MAX;
DEBUG     | ------------------------------------------------ similarly named constant `_Py_IMMORTAL_REFCNT_LOCAL` defined here
DEBUG ...
DEBUG 162 |             return _Py_IMMORTAL_REFCNT;
DEBUG     |                    ^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `_Py_IMMORTAL_REFCNT_LOCAL`
DEBUG
DEBUG error[E0560]: struct `object::PyObject` has no field named `ob_refcnt`
DEBUG   --> /Users/goldbaum/Documents/pyo3/pyo3-ffi/src/object.rs:55:5
DEBUG    |
DEBUG 55 |     ob_refcnt: 1,
DEBUG    |     ^^^^^^^^^ `object::PyObject` does not have this field
DEBUG    |
DEBUG    = note: all struct fields are already assigned
```

We should panic earlier because this configuration will never work.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #4709.

Trying to get a library name or build pyo3-ffi against a free-threaded ABI for Python earlier than 3.13 now panics.

Also adds tests for the panics and for the free-threaded library names as followup for #4690 where I ran out of steam to add new tests.

While working on this I noticed that there was code to work around https://github.com/python/cpython/issues/101614 which was fixed in CPython for 3.10 and newer, so I modified the workaround code path to only apply for Python 3.9 and older.

### CODE REVIEW

File: pyo3-build-config/src/impl_.rs [hunk 1]
```diff
@@ -691,6 +691,11 @@ pub struct PythonVersion {
 }
 
 impl PythonVersion {
+    pub const PY313: Self = PythonVersion {
+        major: 3,
+        minor: 13,
+    };
+    #[allow(dead_code)]
```
Comment (ngoldbaum) [inline pyo3-build-config/src/impl_.rs:698]: this is leftover from a mistaken refactoring that removed the only internal use of this outside tests and should be deleted

File: pyo3-build-config/src/impl_.rs [hunk 2]
```diff
@@ -1642,24 +1645,33 @@ fn default_lib_name_windows(
     debug: bool,
     gil_disabled: bool,
 ) -> String {
-    if debug {
+    if debug && version.minor < 10 {
```
Comment (ngoldbaum) [inline pyo3-build-config/src/impl_.rs:1648]: maybe define a PY310 constant?

**Comment by davidhewitt** [comment]
👍 thanks, do you want me to review before the above comments are resolved?

**Comment by ngoldbaum** [comment]
Go ahead. 

Tiny bit of context: I often look at PRs on my phone since it helps me catch things if I look over code in a different context from where I wrote it.

File: pyo3-ffi/build.rs [hunk 3]
```diff
@@ -112,9 +112,16 @@ fn ensure_python_version(interpreter_config: &InterpreterConfig) -> Result<()> {
                     .0
                     .contains(&BuildFlag::Py_GIL_DISABLED)
                 {
-                    warn!(
+                    let version = interpreter_config.version;
+                    if version < PythonVersion::PY313 {
+                        panic!(
```
Comment (davidhewitt) [inline pyo3-ffi/build.rs:117]: This should use `ensure!` rather than `panic!`, it leads to a friendlier presentation of the error to users.

**Review by davidhewitt — COMMENTED** [review]
Thanks, this seems reasonable to me 👍

**Comment by davidhewitt** [comment]
See also https://github.com/PyO3/maturin/pull/2310#issuecomment-2494026889, can probably adjust here.

**Comment by ngoldbaum** [comment]
Along with some changes to maturin on top of https://github.com/PyO3/maturin/pull/2310 (which I'll create a separate PR for) this latest push lets more of the maturin tests pass on my local dev setup.

File: guide/src/free-threading.md [hunk 4]
```diff
@@ -234,7 +243,24 @@ needed. For now you should explicitly add locking, possibly using conditional
 compilation or using the critical section API to avoid creating deadlocks with
 the GIL.
 
-## Thread-safe single initialization
+### Cannot build extensions using the limited API
+
+The free-threaded build uses a completely new ABI and there is not yet an
+equivalent to the limited API for the free-threaded ABI. That means if your
+crate depends on PyO3 using the `abi3` feature or an an `abi-pyxx` feature, PyO3
```
Comment (davidhewitt) [inline guide/src/free-threading.md:250]:
```suggestion
crate depends on PyO3 using the `abi3` feature or an an `abi3-pyxx` feature, PyO3
```

File: pyo3-build-config/src/impl_.rs [hunk 5]
```diff
@@ -2457,9 +2484,81 @@ mod tests {
...
+                CPython,
+                true,
+                false,
+                true,
+                false,
+            )
+            .unwrap(),
+            "python3_d",
+        );
+        // Python versions older than 3.13 panic if gil_disabled is true
```
Comment (davidhewitt) [inline pyo3-build-config/src/impl_.rs:2506]:
```suggestion
        // Python versions older than 3.13 don't support gil_disabled
```

File: pyo3-ffi/build.rs [hunk 6]
```diff
@@ -56,15 +56,21 @@ fn ensure_python_version(interpreter_config: &InterpreterConfig) -> Result<()> {
...
-                versions.max,
-                std::env::var("CARGO_PKG_VERSION").unwrap(),
-            );
+            if !interpreter_config
+                .build_flags
+                .0
+                .contains(&BuildFlag::Py_GIL_DISABLED)
+            {
+                ensure!(
+                        interpreter_config.version <= versions.max || env_var("PYO3_USE_ABI3_FORWARD_COMPATIBILITY").map_or(false, |os_str| os_str == "1"),
```
Comment (davidhewitt) [inline pyo3-ffi/build.rs:65]: This transformation disables the version check completely on the free-threaded build; I think this is risky given testing with 3.14 free-threading is likely to start happening soon.

I think better would be to do something like

```rust
if interpreter_config.version < versions.max {
    if interpreter_config.build_flags.0.contains(&BuildFlags::Py_GIL_DISABLED) {
        // free-threaded specific error
    } else if !env_var("PYO3_USE_ABI3_FORWARD_COMPATIBILITY").map_or(false, |os_str| os_str == "1") {
        // env var not set, raise the existing error
    }
}
```

**Review by davidhewitt — APPROVED** [review]
Thanks, can confirm locally that on the PyO3 side this looks correct. I just have a few copy suggestions.

Note that `maturin` will also need adjusting to not build abi3 wheels in the free-threaded case, i.e. at the moment I get 

```
📦 Built wheel for abi3 Python ≥ 3.7 to /var/folders/z2/3t02d9cn6gxg11n5yd9yk3wm0000gn/T/.tmpM81f0O/pyo3_scratch-0.1.0-cp37-abi3-macosx_11_0_arm64.whl
💥 maturin failed
  Caused by: pip install in /Users/david/.virtualenvs/pyo3-3.13t failed running ["-m", "pip", "--disable-pip-version-check", "install", "--no-deps", "--force-reinstall", "/var/folders/z2/3t02d9cn6gxg11n5yd9yk3wm0000gn/T/.tmpM81f0O/pyo3_scratch-0.1.0-cp37-abi3-macosx_11_0_arm64.whl"]: exit status: 1
--- Stdout:

--- Stderr:
ERROR: pyo3_scratch-0.1.0-cp37-abi3-macosx_11_0_arm64.whl is not a supported wheel on this platform.
---
```

(maybe you already did that in the `maturin` PR).

File: pyo3-ffi/build.rs (hunk 6 above)
Comment (ngoldbaum) [reply pyo3-ffi/build.rs]: I did this and noticed we were using `interpreter_config.build_flags.0.contains(&BuildFlags::Py_GIL_DISABLED)` quite a bit, so I added that as a method to the `InterpreterConfig` struct to make the spelling a little clearer

**Comment by ngoldbaum** [comment]
> (maybe you already did that in the maturin PR).

I think that was fixed by https://github.com/PyO3/maturin/pull/2316

**Review by davidhewitt — APPROVED** [review]
Thanks, this looks great to me!
