### PR TITLE
Fix ambiguous associated item error

### LINKED ISSUE #5781: `pyclass(from_py_object)` fails on enums with a variant named `Error`
### Bug Description

It's basically #4723.  If an enum with a variant named `error` is annotated with `pyclass(from_py_object)`, it'll fail because the generated code tries to access `Enum::Error`.

### Steps to Reproduce

```rust
use pyo3::prelude::*;

#[derive(Clone, Copy)]
#[pyclass(from_py_object, module = "aspartik.logger")]
pub enum Level {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
}
```

```
   Compiling tmp v0.1.0 (/tmp)
error: ambiguous associated item
   --> src/lib.rs:4:11
    |
  4 | #[pyclass(from_py_object, module = "aspartik.logger")]
    |           ^^^^^^^^^^^^^^ help: use fully-qualified syntax: `<Level as FromPyObject>::Error`
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #57644 <https://github.com/rust-lang/rust/issues/57644>
note: `Error` could refer to the variant defined here
   --> src/lib.rs:10:5
    |
 10 |     Error,
    |     ^^^^^
note: `Error` could also refer to the associated type defined here
   --> /cs/data/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pyo3-0.28.0/src/conversion.rs:412:5
    |
412 |     type Error: Into<PyErr>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^
    = note: `#[deny(ambiguous_associated_items)]` (part of `#[deny(future_incompatible)]`) on by default

error: could not compile `tmp` (lib) due to 1 previous error
```

### Backtrace

```shell

```

### Your operating system and version

Alpine Linux 3.24.0_alpha20260127

### Your Python version (`python --version`)

-

### Your Rust version (`rustc --version`)

rustc 1.92.0 (ded5c06cf 2025-12-08)

### Your PyO3 version

0.28.0

### How did you install python? Did you use a virtualenv?

-

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by funsafemath**
Fixes #5781

It's possible to use `<Self as #pyo3_path::FromPyObject<..., ...>>::Error` instead of `#pyo3_path::PyErr` in `frompyobject.rs`, but it requires changing a bit more code, and I don't think it's more readable

### CODE REVIEW

File: tests/ui/ambiguous_associated_items.rs [hunk 1]
```diff
@@ -22,4 +22,28 @@ enum DeriveItems {
     Target(Py<PyAny>),
 }
 
+// #[pyclass(from_py_object)] is a superset of #[pyclass], but I'd rather not change old tests
+#[pyclass(eq, from_py_object)]
```
Comment (Tpt) [inline tests/ui/ambiguous_associated_items.rs]: Nit: to be more self-contained
```suggestion
#[pyclass(from_py_object)]
```

File: tests/ui/ambiguous_associated_items.rs [hunk 2]
```diff
@@ -22,4 +22,28 @@ enum DeriveItems {
...
+#[derive(PartialEq, Clone)]
```
Comment (Tpt) [inline tests/ui/ambiguous_associated_items.rs]:
```suggestion
#[derive(Clone)]
```

File: tests/ui/ambiguous_associated_items.rs [hunk 3]
```diff
@@ -22,4 +22,28 @@ enum DeriveItems {
     Target(Py<PyAny>),
 }
 
+// #[pyclass(from_py_object)] is a superset of #[pyclass], but I'd rather not change old tests
```
Comment (Tpt) [inline tests/ui/ambiguous_associated_items.rs]:
```suggestion
```

**Review by Tpt — COMMENTED** [review]
Thank you for this! Looks good to me, just a nit on test

**Comment by funsafemath** [comment]
uh github doesn't squash suggestions by default?
