### PR TITLE
vectorcall: fix bindings & use for call0 and call_method0

### LINKED ISSUE #1283: Fix Vectorcall Bindings
Looks like these are not implemented correctly and are now breaking CI with Rust 1.48.  https://github.com/PyO3/pyo3/pull/1282/checks?check_run_id=1425446591

I'm going to disable them in an initial PR and then fix them in a follow-up. We should fix before 0.13 release.

### PR DESCRIPTION
**Pull request by davidhewitt**
This PR fixes the broken vectorcall ffi bindings, and proves that the new ones work by using them in `.call0` and `.call_method0` implementations (where possible).

This yields quite a tidy ~20% performance speedup on those functions, because it no longer creates an empty `PyTuple` and `PyDict` each time:

before: 

```
test bench_call_0        ... bench:      50,712 ns/iter (+/- 5,555)
test bench_call_method_0 ... bench:     164,581 ns/iter (+/- 10,141)
```

after:

```
test bench_call_0        ... bench:      40,996 ns/iter (+/- 4,490)
test bench_call_method_0 ... bench:     138,826 ns/iter (+/- 18,465)
```

I'd love to follow this PR up with some ways to use vectorcall for functions with arguments too. Will leave that for #684 instead of pushing this further right now.

Closes #1283

### CODE REVIEW

**Comment by davidhewitt** [comment]
Windows failing to link on abi3 - presumably it's us doing something wrong; I'm asking about it at https://bugs.python.org/issue42415

**Comment by davidhewitt** [comment]
Rather than wait for that bug to be resolved (which I guess might not happen until Python 3.9.1) I've put a TODO in the code and just enabling the optimization for the unlimited API for now.

File: src/ffi/cpython/abstract_.rs [hunk 1]
```diff
@@ -0,0 +1,304 @@
...
+    _PyObject_VectorcallTstate(PyThreadState_GET(), callable, args, nargsf, kwnames)
+}
+
+extern "C" {
+    #[cfg(all(Py_3_8, not(PyPy)))]
+    #[cfg_attr(not(Py_3_9), link_name = "_PyObject_VectorcallDict")]
+    pub fn PyObject_VectorcallDict(
+        callable: *mut PyObject,
+        args: *const *mut PyObject,
+        nargsf: usize,
```
Comment (kngwyu) [inline src/ffi/cpython/abstract_.rs:104]: `libc::size_t` would be better?

File: src/ffi/cpython/abstract_.rs [hunk 2]
```diff
@@ -0,0 +1,304 @@
...
+    pub fn PyVectorcall_Call(
+        callable: *mut PyObject,
+        tuple: *mut PyObject,
+        dict: *mut PyObject,
+    ) -> *mut PyObject;
+}
+
+#[cfg(all(Py_3_8, not(PyPy)))]
+#[inline(always)]
+pub unsafe fn _PyObject_FastCallTstate(
```
Comment (kngwyu) [inline src/ffi/cpython/abstract_.rs:119]: Where is this function? (I'm looking at https://github.com/python/cpython/blob/v3.8.6/Include/cpython/abstract.h ).

File: src/ffi/cpython/abstract_.rs [hunk 3]
```diff
@@ -0,0 +1,304 @@
...
+        2 | PY_VECTORCALL_ARGUMENTS_OFFSET as usize,
+        std::ptr::null_mut(),
+    )
+}
+
+// skipped _PyObject_VectorcallMethodId
+// skipped _PyObject_CallMethodIdNoArgs
+// skipped _PyObject_CallMethodIdOneArg
+
+// skipped _PyObject_HasLen
```
Comment (kngwyu) [inline src/ffi/cpython/abstract_.rs:206]: Just curious, why are they skipped?

File: src/ffi/cpython/mod.rs [hunk 4]
```diff
@@ -0,0 +1,3 @@
+pub mod abstract_;
```
Comment (kngwyu) [inline src/ffi/cpython/mod.rs:1]: :+1:  for creating this new module. Maybe we can reduce `cfg` using this.

File: src/instance.rs [hunk 5]
```diff
@@ -272,7 +272,18 @@ impl<T> Py<T> {
     ///
     /// This is equivalent to the Python expression `self()`.
     pub fn call0(&self, py: Python) -> PyResult<PyObject> {
-        self.call(py, (), None)
+        cfg_if::cfg_if! {
+            // TODO: Use PyObject_CallNoArgs instead after https://bugs.python.org/issue42415,
+            // at which point can enable optimization for limited API.
```
Comment (kngwyu) [inline src/instance.rs:277]: > at which point can enable

I'm sorry but I don't understand the grammar (caveat: I'm not a native English speaker, so please just ignore if I'm wrong)

**Review by kngwyu — CHANGES_REQUESTED** [review]
Thanks. This is a pretty good step towards vectorizing function calls. Comments are mainly around FFI definitions.

File: src/ffi/cpython/abstract_.rs (hunk 2 above)
Comment (davidhewitt) [reply src/ffi/cpython/abstract_.rs:119]: I'm looking at the same file but the version in `master` (so `3.10-dev`). I figured it was best for these inline functions to be as up-to-date as possible.

File: src/ffi/cpython/abstract_.rs (hunk 3 above)
Comment (davidhewitt) [reply src/ffi/cpython/abstract_.rs:206]: I didn't consider them relevant to my PR; I could add them but I'd also quite like to keep as few unlimited API definitions as possible (as they're more likely for us to be work to maintain).

See also #1289 which talks a bit about what I'm thinking.

File: src/ffi/cpython/mod.rs (hunk 4 above)
Comment (davidhewitt) [reply src/ffi/cpython/mod.rs:1]: Yes, I think for sure (again see #1289).

File: src/instance.rs (hunk 5 above)
Comment (davidhewitt) [reply src/instance.rs:277]: Yes, this is me being lazy; I've skipped the subject. I'll tidy this up 😄

**Review by kngwyu — APPROVED** [review]

**Comment by kngwyu** [comment]
Thanks!
