### PR TITLE
Fix memory leak in `PyTypeBuilder::build`

### LINKED ISSUE #3400: Potential memory leak in `PyTypeBuilder::build`
### Bug Description

As described in https://github.com/pyca/cryptography/issues/9457 I've been running `cryptography` using valgrind to analyze an issue in my program. During this I came across a memory leak while loading the bindings. `cryptography` uses PyO3 and as noted in the bug report above, the problem seens to come from the `py_class_qualified_name` method, which leaks some memory:
```
==998588== 44 bytes in 1 blocks are definitely lost in loss record 66 of 176
==998588==    at 0x4E0A13B: realloc (vg_replace_malloc.c:1649)
==998588==    by 0x68803CA: realloc (alloc.rs:140)
==998588==    by 0x68803CA: shrink (alloc.rs:308)
==998588==    by 0x68803CA: shrink<u8, alloc::alloc::Global> (raw_vec.rs:440)
==998588==    by 0x68803CA: shrink_to_fit<u8, alloc::alloc::Global> (raw_vec.rs:357)
==998588==    by 0x68803CA: shrink_to_fit<u8, alloc::alloc::Global> (mod.rs:1042)
==998588==    by 0x68803CA: alloc::vec::Vec<T,A>::into_boxed_slice (mod.rs:1101)
==998588==    by 0x687FAFA: alloc::ffi::c_str::CString::_from_vec_unchecked (c_str.rs:348)
==998588==    by 0x67EAE64: <T as alloc::ffi::c_str::CString::new::SpecNewImpl>::spec_new_impl (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x67E8C73: pyo3::pyclass::create_type_object::PyTypeBuilder::build (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x637AFF4: pyo3::pyclass::create_type_object::create_type_object (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x635CDB1: pyo3::sync::GILOnceCell<T>::init (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x67F2BF9: pyo3::impl_::pyclass::lazy_type_object::LazyTypeObjectInner::get_or_try_init (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x63E2C83: cryptography_rust::x509::sct::add_to_module (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x63A24C2: cryptography_rust::_rust (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x67EE57F: pyo3::impl_::pymodule::ModuleDef::make_module (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
==998588==    by 0x6392B34: PyInit__rust (in /home/tha/temp/venv/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
```

### Steps to Reproduce

1. `python -m venv venv`
2. `./venv/bin/pip install cryptography`
3. `valgrind --leak-check=full ./venv/bin/python -c "from cryptography.hazmat.bindings import _rust"`

### Backtrace

_No response_

### Your operating system and version

Ubuntu 23.04

### Your Python version (`python --version`)

Python 3.11.4

### Your Rust version (`rustc --version`)

Don't know. Using pre-built binaries

### Your PyO3 version

Don't know. Using pre-built binaries

### How did you install python? Did you use a virtualenv?

apt

### Additional Info

As @alex reported, this seems to come from https://github.com/PyO3/pyo3/blob/main/src/pyclass/create_type_object.rs#L376

### PR DESCRIPTION
**Pull request by messense**
Fixes #3400

### CODE REVIEW

File: src/pyclass/create_type_object.rs [hunk 1]
```diff
@@ -386,6 +387,8 @@ impl PyTypeBuilder {
         // Safety: We've correctly setup the PyType_Spec at this point
         let type_object: Py<PyType> =
             unsafe { Py::from_owned_ptr_or_err(py, ffi::PyType_FromSpec(&mut spec))? };
+        // Safety: `name` is a valid pointer obtained from `CString::into_raw` in `py_class_qualified_name`
+        drop(unsafe { CString::from_raw(name) });
```
Comment (davidhewitt) [inline src/pyclass/create_type_object.rs:391]: Rather than use unsafety here let's change `py_class_qualified_name` to return a `CString`. That way we can also flip the check around and instead `mem::forget(name)` on Python < 3.11.

**Review by davidhewitt — CHANGES_REQUESTED** [review]
It looks like this is only correct since Python 3.11:

https://docs.python.org/3/whatsnew/changelog.html#id144

So we'll need to decide to do this based on the Python version _at runtime_. For non-abi3 that's easy, we use cfg, for abi3 we need to detect sys.version_info - see `bpo_35810_workaround` in `pyclass.rs` for an example of how to do this.

**Comment by messense** [comment]
FYI, the C API changelog entry is a bit wrong, it's not `bpo-29103`, it's actually [`bpo-45315`](https://bugs.python.org/issue45315)

**Review by davidhewitt — APPROVED** [review]
Thanks - this looks good to me 👍
