### PR TITLE
Handle errors on `PyIterator` when calling `size_hint`

### LINKED ISSUE #5595: `size_hint` implementation in `Bound<'py, PyIterator>` looks suspect
The call to `PyObject_LengthHint` probably needs error checking. It's documented to return -1 on error, but we don't handle any possible exception, which will cause future code to start raising errors.

(Probably should either call `PyErr::write_unraisable`, or just clear the exception)

### PR DESCRIPTION
**Pull request by bschoenmaeckers**
fixes #5595

### CODE REVIEW

File: src/types/iterator.rs [hunk 1]
```diff
@@ -392,6 +401,43 @@ def fibonacci(target):
...
     }
 
+    #[test]
+    #[cfg(all(feature = "macros", not(Py_LIMITED_API)))]
+    fn length_hint_error() {
+        #[crate::pyfunction(crate = "crate")]
+        fn test_size_hint(obj: &crate::Bound<'_, crate::PyAny>) {
+            let iter = obj.cast::<PyIterator>().unwrap();
+            assert_eq!((0, None), iter.size_hint());
+            assert!(PyErr::take(obj.py()).is_none());
```
Comment (davidhewitt) [inline src/types/iterator.rs:414]: Perhaps use `UnraisableCapture` to demonstrate that the error was sent to `sys.unraisablehook`?

**Review by davidhewitt — COMMENTED** [review]
Thanks for handling!

File: src/types/iterator.rs (hunk 1 above)
Comment (bschoenmaeckers) [reply src/types/iterator.rs:414]: Thanks! Did not know yet about this utility.
