### PR TITLE
More ergonomic error messages for invalid #[pyclass] args

### LINKED ISSUE #823: Wrong format error diagnostics
In https://github.com/PyO3/pyo3/blob/6998660ca43c8a39c0e2f01541da418e3c731e86/pyo3-derive-backend/src/pyclass.rs we have errors like:
```
  "Wrong 'name' format",
```

It would be appreciated if they could say things like Got an X but expected a Y.

### PR DESCRIPTION
**Pull request by kngwyu**
Resolves #823

### CODE REVIEW

File: pyo3-derive-backend/src/pyclass.rs [hunk 1]
```diff
@@ -56,70 +56,71 @@ impl PyClassArgs {
...
                     };
                     self.has_extends = true;
                 }
-                _ => {
-                    return Err(syn::Error::new_spanned(
-                        *assign.right.clone(),
-                        "Wrong format for extends",
-                    ));
-                }
+                _ => expected!("type path(e.g., my_mod::MyClass)"),
```
Comment (birkenfeld) [inline pyo3-derive-backend/src/pyclass.rs]:
```suggestion
                _ => expected!("type path (e.g., my_mod::MyClass)"),
```

File: pyo3-derive-backend/src/pyclass.rs [hunk 2]
```diff
@@ -56,70 +56,71 @@ impl PyClassArgs {
...
+                syn::Expr::Path(exp) if exp.path.segments.len() == 1 => {
                     self.name = Some(exp.clone().into());
                 }
-                _ => {
-                    return Err(syn::Error::new_spanned(
-                        *assign.right.clone(),
-                        "Wrong 'name' format",
-                    ));
-                }
+                _ => expected!("single type path(e.g., Name)"),
```
Comment (birkenfeld) [inline pyo3-derive-backend/src/pyclass.rs]:
```suggestion
                _ => expected!("type name (e.g., Name)"),
```

File: pyo3-derive-backend/src/pyclass.rs [hunk 3]
```diff
@@ -56,70 +56,71 @@ impl PyClassArgs {
...
                 }) => {
                     self.module = Some(lit.clone());
                 }
-                _ => {
-                    return Err(syn::Error::new_spanned(
-                        *assign.right.clone(),
-                        "Wrong format for module",
-                    ));
-                }
+                _ => expected!(r#"string literal(e.g., "mymod")"#),
```
Comment (birkenfeld) [inline pyo3-derive-backend/src/pyclass.rs]:
```suggestion
                _ => expected!(r#"string literal (e.g., "mymod")"#),
```

File: pyo3-derive-backend/src/pyclass.rs [hunk 4]
```diff
@@ -143,11 +144,11 @@ impl PyClassArgs {
             "dict" => {
                 parse_quote! {pyo3::type_flags::DICT}
             }
-            _ => {
+            x => {
                 return Err(syn::Error::new_spanned(
                     exp.path.clone(),
-                    "Unsupported parameter",
-                ));
+                    format!("Expected one of gc/weakref/subclass/dict, but got {}", x),
```
Comment (davidhewitt) [inline pyo3-derive-backend/src/pyclass.rs]: Could perhaps add a test for this case too?

File: tests/ui/invalid_pyclass_args.stderr [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+ --> $DIR/invalid_pyclass_args.rs:6:21
+  |
+6 | #[pyclass(extends = "PyDict")]
+  |                     ^^^^^^^^
+
+error: Expected type name (e.g., Name), but got m :: MyClass
+ --> $DIR/invalid_pyclass_args.rs:9:18
+  |
+9 | #[pyclass(name = m::MyClass)]
+  |                  ^^^^^^^^^^
```
Comment (davidhewitt) [inline tests/ui/invalid_pyclass_args.stderr]: I'm trying to decide if the `but got x` portion of the error messages is necessary.

On the plus side, they make the error description slightly nicer to read.

However, the invalid "but got" input is already highlighted in the source code beneath the error, so we're kinda repeating the information twice.

Also, in this `m::MyClass` case the formatting has been changed versus the original source code, which makes it a bit weird to read.

Comment (davidhewitt) [reply tests/ui/invalid_pyclass_args.stderr]: cc @gilescope who reported the original issue.

Comment (kngwyu) [reply tests/ui/invalid_pyclass_args.stderr]: Thank you, I chose a simplfied one.

**Comment by gilescope** [comment]
Cracking.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
