### PR TITLE
Turn calls of __traverse__ into no-ops for unsendable pyclass if on the wrong thread

### LINKED ISSUE #3688: Program aborts when Python's garbage collector gets called from another thread and attempts to traverse an unsendable pyclass instance.
I have created a repository providing a full breakdown and minimal reproducible example of the error 
at [https://github.com/JRRudy1/pyo3_gc_error](https://github.com/JRRudy1/pyo3_gc_error). I will provide a summary below, but please check out 
the repository instead as I put a lot of effort into clearly presenting and investigating the issue.

In summary, I have discovered an error, or perhaps an undocumented limitation, in the way 
PyO3 handles thread-checking for "unsendable" `pyclass` instances as they are being traversed 
by Python's garbage collector (GC). In particular, this occurs when garbage collection is triggered 
from a separate thread, and the pyclasses integrate with the GC by implementing the `__traverse__` 
magic method. The error (or limitation) results in a hard abort, and is particularly problematic 
since it cannot be caught from Python using a `try`/`except` block.

The conditions and sequence of events leading to the error can be summarized as:
1. Two (or more) instances of an "unsendable" pyclass are created from Python
2. The objects are in a reference cycle, and the pyclass defines `__traverse__`/`__clear__` to break it
4. All references to them outside the cycle are dropped, so the next GC cycle should clean them up
5. Before the GC runs automatically, it gets explicitly called from another thread (`gc.collect` from 
    Python or `GcCollect` from C)
6. When the GC calls back into Rust to traverse the objects, PyO3 detects that the calling thread is
    not the original thread and incorrectly deduces that the object was sent between threads
7. PyO3 triggers a panic and the program aborts with a misleading error message

I have gotten reasonably familiar with PyO3's internals and may be interested in working on this, 
but I would need some guidance from an "expert" with a more nuanced understanding of the 
possible implications. It is possible that the limitation cannot be safely fixed, and the only solution 
is to improve the error message and add a warning to the documentation.

As mentioned above, please visit [https://github.com/JRRudy1/pyo3_gc_error](https://github.com/JRRudy1/pyo3_gc_error) for more information.

### PR DESCRIPTION
**Pull request by adamreichold**
Adds a "threadsafe" variant of `PyCell::try_borrow` which will fail instead of panicking if called on the wrong thread and use it in `call_traverse` to turn GC traversals of unsendable pyclasses into no-ops if on the wrong thread.

This can imply leaking the underlying resource if the originator thread has already exited so that the GC will never run there again, but it does avoid hard aborts as we cannot raise an exception from within `call_traverse`.

Closes #3688

### CODE REVIEW

**Comment by adamreichold** [comment]
@JRRudy1 Could you use a dependency specification like

```toml
pyo3 = { git = "https://github.com/PyO3/pyo3.git", branch = "unsendable-threadsafe-traverse" }
```

and verify that this would work for your use case? Thanks.

File: src/pycell.rs [hunk 1]
```diff
@@ -975,6 +983,7 @@ impl From<PyBorrowMutError> for PyErr {
 #[doc(hidden)]
 pub trait PyCellLayout<T>: PyLayout<T> {
     fn ensure_threadsafe(&self);
+    fn check_threadsafe(&self) -> Result<(), PyBorrowError>;
```
Comment (davidhewitt) [inline src/pycell.rs:986]: Potentially this should return `bool` to match the `PyClassThreadChecker` trait implementation? It would make `try_borrow_threadsafe` implementation a bit messier but might be nice for consistency.

**Review by davidhewitt — COMMENTED** [review]
Thanks, nice! Looks straightforward enough.

I wonder if there's a way to add a test for this. I suspect the most reasonable option, if we felt it worth it, would be to add a test which manually calls the traverse slot?

File: src/pycell.rs (hunk 1 above)
Comment (adamreichold) [reply src/pycell.rs:986]: I had written down both and ended up with this version because the calling (i.e. `try_borrow_threadsafe`) was more consistent this way without the `PyCellLayout` impl becoming more complicated. The other way around, both impls looked messier. But to be honest, the differences were small/purely aesthetic either way, so If you'd like me to, I can certainly change this back.

**Comment by adamreichold** [comment]
> I wonder if there's a way to add a test for this. I suspect the most reasonable option, if we felt it worth it, would be to add a test which manually calls the traverse slot?

Will give it a try.

I also noticed that this should be mentioned in the guide...

File: src/pycell.rs (hunk 1 above)
Comment (davidhewitt) [reply src/pycell.rs:986]: I trust your taste for good design, so let's keep it like this then 👍

**Review by davidhewitt — APPROVED** [review]
Looks great to me, thanks, great test 👍
