### PR TITLE
Remove deferred reference count increments and make the global reference pool optional

### LINKED ISSUE #4105: segmentation fault second run of rust function in python pyo3 0.21.2
Hi. I'm trying to apply pyo3 0.21.2 to 0.20 codes.

With 0.20 codes my python app works, but with the new code does not.

The current situation:
- python version = 3.9.15
1. the first call of `rust_function` in python succeeds, but the second call fails.
2. The error was segmentation fault.
3. The error messages are slightly different per run:
```
vk[d].setdefault(a, dict())[p_key] = sound_data
KeyError: 'chr11:871499/2' // <- this string can't be one of p_key, a or d. The string like that comes from another variable.

Exception ignored deletion of interned string failed:
Traceback (most recent call last):
  File "python_project.py", line 333, in rust_function
    self.rust_have_been_failed = True
KeyError: 'À\xad\x8dU' // <- A value that shouldn't exist if it's working properly.

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
--Type <RET> for more, q to quit, c to continue without paging--
pymalloc_free (ctx=0x0, p=0x1)
    at /usr/local/src/conda/python-3.9.15/Objects/obmalloc.c:1866
1866    /usr/local/src/conda/python-3.9.15/Objects/obmalloc.c: No such file or directory.
```

```
/usr/local/src/conda/python-3.9.15/Objects/object.c: No such file or directory.
```
4. returning `(String, i32)` instead of `(Py<PyString>, i32)` does not raise the error.

The codes here: [https://gist.github.com/Crispy13/03d25f8d556e644b5425ddf1decff6dc](https://gist.github.com/Crispy13/03d25f8d556e644b5425ddf1decff6dc)

The rust function get input string from python, and return it back with additional i32.

Is it me? What's the cause of the error?

### PR DESCRIPTION
**Pull request by adamreichold**
While this started out as an optimization to fully avoid the overhead of the global reference pool, #4105 lead us to the conclusion that deferring reference count increments is fundamentally unsound and so has to be removed from the global reference pool in any configuration. As a consequence, the pool will be limited to handling reference count decrements and the `Clone` implementation for types `Py` will panic if called without the GIL being held.

Since the new behaviour of `Clone` is significant hazard to existing code but unavoidable for a sound API, we decided to hide it behind the new `py-clone` feature which needs to be explicitly enabled thereby giving downstream projects a chance to inspect their usage of `Clone` before committing to the new possibilities of panics.

Closes #4105

~~I don't think leaking references in `Drop` is nice because it is quite easy for this to be called without the GIL being held, especially in embedding scenarios. But it should be safe nevertheless. It might call for an inverted feature to explicitly opt out of the reference pool by enabling e.g. `disable-reference-pool`.~~

### CODE REVIEW

**Comment by alex** [comment]
Why print vs. panic in drop?

**Comment by adamreichold** [comment]
> Why print vs. panic in drop?

It is quite hard to avoid dropping without the GIL, especially in embedding situations. And in contrast to `Clone`, leaking is sound.

**Comment by adamreichold** [comment]
That said, I would also be fine with panicking in `Drop` and put the onus of avoiding it on the extension author as this is already a bit of a "I-don't-care-just-make-it-fast" knob.

**Comment by davidhewitt** [comment]
I quite like the idea of this feature. I wonder, maybe instead of leaking, without the pool enabled the drop & clone code can just unconditionally call `Python::with_gil`?

That way the program is correct whether or not the feature is enabled, but users get to control this knob according to the performance characteristics of their program.

**Comment by davidhewitt** [comment]
(and hopefully with nogil in the long term the reference pool feature might just then become deprecated for better options)

**Comment by adamreichold** [comment]
> without the pool enabled the drop & clone code can just unconditionally call Python::with_gil?

Isn't this much too prone to deadlocks?

**Comment by davidhewitt** [comment]
Ungh, yes that's true. With nogil what I suggest would be viable. 😭

**Comment by Icxolu** [comment]
Could we provide the `Clone` impl for `Py` only under that feature flag? That would eliminate the panic and make it a compile error. Cloning would still be possible by going through `Bound`, with the guarantee that the gil is held.

**Comment by adamreichold** [comment]
> Could we provide the `Clone` impl for `Py` only under that feature flag? That would eliminate the panic and make it a compile error. Cloning would still be possible by going through `Bound`, with the guarantee that the gil is held.

The problem I see is that you might want to still clone `Py` values to e.g. fulfil trait requirements of Rust types but ensure by context that you have the GIL.

File: src/gil.rs [hunk 1]
```diff
@@ -467,7 +478,10 @@ pub unsafe fn register_decref(obj: NonNull<ffi::PyObject>) {
     if gil_is_acquired() {
         ffi::Py_DECREF(obj.as_ptr())
     } else {
+        #[cfg(feature = "reference-pool")]
         POOL.register_decref(obj);
+        #[cfg(all(not(feature = "reference-pool"), debug_assertions))]
+        eprintln!("Leaking pointer into Python heap because the GIL is not held.");
```
Comment (davidhewitt) [inline src/gil.rs:484]: Is it potentially helpful to give the address of the pointer?

File: src/gil.rs [hunk 2]
```diff
@@ -451,7 +459,10 @@ pub unsafe fn register_incref(obj: NonNull<ffi::PyObject>) {
     if gil_is_acquired() {
         ffi::Py_INCREF(obj.as_ptr())
     } else {
+        #[cfg(feature = "reference-pool")]
         POOL.register_incref(obj);
+        #[cfg(not(feature = "reference-pool"))]
+        panic!("Cannot clone pointer into Python heap without the GIL being held.");
```
Comment (davidhewitt) [inline src/gil.rs:465]: In the spirit of #4098, should we add `#[track_caller]` here (and on the `Py::clone` impl, assuming that it's valid to add to trait methods)?

**Review by davidhewitt — COMMENTED** [review]
Yes, I think it's extremely handy to be able to `#[derive(Clone)]` in particular, which would require `Py<T>: Clone`.

Also the direction seems to be that panic-on-drop is not allowed (e.g. https://github.com/rust-lang/rfcs/pull/3288) so +1 for not panicking. But I would be open to aborting instead of printing :)

Pending a decision on what to do with Drop I think the idea here gets a 👍 from me as a lever for users to pull when they know their application better than us (i.e. it never clones or drops Python values without the GIL held).

We should document this in the features and performance sections of the guide before merging, though.

File: src/gil.rs (hunk 1 above)
Comment (adamreichold) [reply src/gil.rs:484]: I think if finding such an issue, then a backtrace would be relevant but if we go for aborting that would result in any case.

> But I would be open to aborting instead of printing :)

I am fine with making that change. We just need to document this with a big red warning sign but as you wrote, this should get its own section anyway.

As for printing the pointer value, I think this can become a security issue as pointer values can be used to break ASLR and with services exposed to the web, it is conceivable that such a message ends up with the attacker. This would be a security issue for itself but following a defence in depth approach, we might want to be careful about printing pointer values.

File: src/gil.rs (hunk 2 above)
Comment (adamreichold) [reply src/gil.rs:465]: It appears possible, c.f. https://rustc-dev-guide.rust-lang.org/backend/implicit-caller-location.html#traits and hence I will add it.

Comment (adamreichold) [reply src/gil.rs:465]: I'll also add it to the `Drop` path because the backtrace reporting is just as relevant for the abort case.

Comment (davidhewitt) [reply src/gil.rs:465]: To be clear I'm not entirely sure aborting is necessary in Drop, as we already have precedent to leak e.g. unsendable objects. 

(I guess a further knob users may want a choice on is whether to leak or abort, but it's less clear that's a good fit for a feature.)

**Comment by adamreichold** [comment]
Added a section in the performance chapter of the guide. @inducer @matthiasdiener As this was originally reported by you, what do you think about the feature and its explanation in the guide?

File: src/gil.rs (hunk 1 above)
Comment (adamreichold) [reply src/gil.rs]: One last problem I have is that `std::process::abort` does not take a message and there is no stable portable way to do it ourselves and we do not have the GIL to e.g. call the unraisable hook.

For `PanicTrap` we just went for explicitly causing a double panic by panicking in `Drop` which is only called during unwinding. This was also was gave us the backtrace.

I shoehorned the same approach here but left it as a separate commit so we can decide to drop it if this deemed too hacky.

File: src/gil.rs (hunk 2 above)
Comment (alex) [reply src/gil.rs:466]: FWIW, my concern with printing + leaking is that it's very difficult to catch in testing. If I want to ensure my app never takes these paths, it's much easier if I get a clear test failure.

Comment (adamreichold) [reply src/gil.rs:466]: I agree with that but I think there is no right choice. Not even adding another knob seems just right, as the additional complexity seems over the top.

In the end, for me the consistency with how we already handle unsendable types was what tipped the odds towards leaking for me, because I think the problems are very much the same, even similarly niche, and if go for aborting here, we should do that for unsendable types as well.

Comment (davidhewitt) [reply src/gil.rs:466]: The case for testing is an interesting one, though.

What if we had an environment variable that upgraded leaking to abort (or vice versa) on debug builds for this case? I think the runtime overhead might be acceptable as part of a debugging setup.

I think for the unsendable case, aborting is not desirable at all because it's difficult to prevent the GC running on other threads.

Comment (adamreichold) [reply src/gil.rs:466]: I would consider adding a `--cfg` which could be enabled via `RUSTFLAGS` etc. but personally, I find it too much complexity.

I mean, we all like performance, but for projects valuing correctness (e.g. cryptography), my recommendation would be to not keep doing what we have been doing until now. This is for projects which want to live on the razor's edge.

And in the long term, the problem will go away or rather move to a different project. A GILless CPython will carry the machinery to update reference counts from threads all over the place and we should be able to just unconditionally drop our reference pool for these builds.

**Comment by Icxolu** [comment]
> The problem I see is that you might want to still clone `Py` values to e.g. fulfil trait requirements of Rust types but ensure by context that you have the GIL.

> Yes, I think it's extremely handy to be able to `#[derive(Clone)]` in particular, which would require `Py<T>: Clone`.

Hmm, I can definitely see that point, but in that case I feel like having this as opt-out of "safe" behavior, rather than opt-in to "i-know-what-im-doing" is not ideal, since this has "spooky" side effects. Starting with `no-default-features`, or turning them off later and forgetting to turn this one back on, will lead to very different behavior, which won't be noticed until runtime. Arguably this is probably not a very common scenario currently, but it feels like an easy footgun nevertheless.

**Comment by adamreichold** [comment]
> Hmm, I can definitely see that point, but in that case I feel like having this as opt-out of "safe" behavior, rather than opt-in to "i-know-what-im-doing" is not ideal, since this has "spooky" side effects. Starting with no-default-features, or turning them off later and forgetting to turn this one back on, will lead to very different behavior, which won't be noticed until runtime. Arguably this is probably not a very common scenario currently, but it feels like an easy footgun nevertheless.

I share that sentiment which is why I included

> It might call for an inverted feature to explicitly opt out of the reference pool by enabling e.g. disable-reference-pool.

in the cover letter.

Do note one downside of this though: Rust's features are additive so there is a different kind of spooky side effect. One crate in dependency graph of an extension can enable affecting everything else. It would be bad style to enable it in a non-leaf crate, but it is possible.

So if we really want to make this hard to enable accidentally as possible, we should probably go for a raw `--cfg` flag enabled by wrangling compiler flags to which I would also be amenable.

But I think we should first hear from the original reporters whether they actually want this. Just dropping the PR because it does not really help them is also an option.

**Comment by davidhewitt** [comment]
Following up from https://github.com/PyO3/pyo3/issues/4105#issuecomment-2068092437

It seems that we may need to migrate to a strategy where `Clone` without the GIL will always panic. We _could_ gate the whole `Clone` implementation behind a feature, given that the panic is inconvenient and users may not want to deal with the possibility of runtime crashes. (Instead they would likely need to write `Clone` implementations by hand.)

For `Drop` - I think that deferring reference count decreases is still safe (worst it can do is cause leaks).

Maybe we can move the overhead away from all PyO3 functions, and instead if there is a deferred drop we signal up a worker thread to wake, which can attempt to acquire the GIL and drop all currently pending deferred drops? Moving the overheads off every function call may be a good enough solution until GIL-less Python can give us an alternative option.

**Comment by davidhewitt** [comment]
(I know I already suggested this reference-counting-thread idea in https://github.com/PyO3/pyo3/issues/3827#issuecomment-1942438315 and @adamreichold correctly pointed out that deferring the work is dangerous.

With what we are now seeing particularly about deferred `Clone` being incorrect, my thought is the reference-counting-thread idea may be viable when only used for `Drop`.)

**Comment by adamreichold** [comment]
> Maybe we can move the overhead away from all PyO3 functions, and instead if there is a deferred drop we signal up a worker thread to wake, which can attempt to acquire the GIL and drop all currently pending deferred drops? Moving the overheads off every function call may be a good enough solution until GIL-less Python can give us an alternative option.

But isn't this mainly gaming the benchmarks? Our call overhead will reduce, but the actual work to be done will increase (at least there is an additional acquisition of the GIL, and on another thread to which all these objects may be cache-cold).

This could improve throughput at the cost of increase CPU usage, but only if the other threads actually release the GIL for reasonable amounts of time. And if that worker thread never actually gets the GIL, we could see unbounded memory growth.

While deferred drop is certainly not as dangerous a deferred clone, I fear we are inventing a garbage collector here. And if do decide to do that, I think we should go for established solutions, e.g. epoch-based reclamation or hazard pointers which at least have some support crates available.

Personally, I don't think we should make this work. This is adding completely additional semantics that Python itself does not (yet) support which will always be difficult to get right as long as Python does not cooperate in these memory management tasks.

So while I could live without the `Clone` impl, I would like to avoid making the `Drop` do more than leak or panic/abort. If we are unused about this, then I think adding a feature flag to control whether `Clone` is unavailable and `Drop` leaks versus `Clone` and `Drop` both panic/abort makes more sense to avoid any surprises. Adding a panicking `Clone` also sounds like it fits the additive feature model.

**Comment by davidhewitt** [comment]
> But isn't this mainly gaming the benchmarks? Our call overhead will reduce, but the actual work to be done will increase (at least there is an additional acquisition of the GIL, and on another thread to which all these objects may be cache-cold).
> 
> This could improve throughput at the cost of increase CPU usage, but only if the other threads actually release the GIL for reasonable amounts of time. And if that worker thread never actually gets the GIL, we could see unbounded memory growth.

Very true. Ok, I hereby agree to drop (heh) the reference-counting-thread idea 👍 

I think there's still some open question on whether we should be trying to keep the drop pool around. I feel like for sake of compatibility we can't migrate users immediately from the existing pool to leaking on drop without GIL, as silently adding memory leaks to their program may break confidence in PyO3. The abort-on-drop is similarly unappealing for migration but is at least a noisy failure mode.

Whether to leak / abort, some prior art is that `pybind11` throws exceptions if objects are dropped without the GIL held - https://github.com/pybind/pybind11/blob/19a6b9f4efb569129c878b7f8db09132248fbaa1/include/pybind11/pytypes.h#L269

Given the concern about testing for leaks being hard, I'd be tempted to suggest that we add this as a `disable-reference-pool` feature which replaces the reference pool with aborts.

I think we are now on a course to release 0.22 ASAP, given that there are various behavioural changes afoot here.

So I propose the following for 0.22:
- We get the next step of the `gil-refs` deprecation complete.
- We gate a panicking `Py::clone` implementation behind a `py-clone` feature.
- We add `disable-reference-pool` to abort on drop instead of pooling.
- (Maybe) we also complete the changes to `Python::allow_threads`

**Comment by adamreichold** [comment]
>     * We gate a panicking `Py::clone` implementation behind a `py-clone` feature.

I added a new commit here which removes delayed refcnt increments and adds said feature.

>     * We add `disable-reference-pool` to abort on drop instead of pooling.

Added another commit which renames the feature proposed here.

>     * (Maybe) we also complete the changes to `Python::allow_threads`

I would glad if we did.

Note that the tests currently pass only with `py-clone` enabled and `disable-reference-pool`  disabled. I will have to work on this, but I thought I push what I have so far to enable review of the more tricky parts of the code and especially the associated documentation.

**Comment by davidhewitt** [comment]
👍 I will do my best to find time to give this a full review tomorrow. Am pretty loaded with family responsibility at the moment so my opportunities to focus are a bit rare this month.

File: src/pybacked.rs
Comment (Icxolu) [inline src/pybacked.rs:1]: Should these get a `clone_ref` now? Or should we introduce a `CloneRef` trait, potentially with a blanket impl for `T: Clone` (which could also help with `#[pyo3(get)]`)?

File: src/instance.rs [hunk 3]
```diff
@@ -1810,7 +1817,9 @@ where
 /// If the GIL is held this increments `self`'s reference count.
 /// Otherwise this registers the [`Py`]`<T>` instance to have its reference count
 /// incremented the next time PyO3 acquires the GIL.
```
Comment (Icxolu) [inline src/instance.rs:1819]: This needs updating

**Review by Icxolu — COMMENTED** [review]
I think these features should be mentioned in the `Features reference` section of the guide, probably with a strong emphasis on both to only enable them in "leaf" crates (and not libraries)

File: guide/src/faq.md [hunk 4]
```diff
@@ -127,12 +127,10 @@ If you don't want that cloning to happen, a workaround is to allocate the field
 ```rust
 # use pyo3::prelude::*;
 #[pyclass]
-#[derive(Clone)]
 struct Inner {/* fields omitted */}
 
 #[pyclass]
 struct Outer {
-    #[pyo3(get)]
```
[the remark this answers is not in the document]
Comment (adamreichold) [reply guide/src/faq.md:135]: I think adding a `CloneRef` trait is the way to go, but I also agree that this should be a follow-up change as this is already outside of my comfort zone to wrangle into shape and request review of.

File: src/pybacked.rs
Comment (adamreichold) [reply src/pybacked.rs:1]: I can provide `clone_ref` inherent methods or we can postpone this until the introduction of the trait. I am also unsure on how to change the tests then, i.e. should they go through `clone` or `clone_ref`? Personally, I would prefer if we defer.

Comment (Icxolu) [reply src/pybacked.rs:1]: Sure, lets defer this until we introduce `CloneRef`

File: guide/src/performance.md [hunk 5]
```diff
@@ -96,3 +96,45 @@ impl PartialEq<Foo> for FooBound<'_> {
     }
 }
 ```
+
+## Disable the global reference pool
+
+PyO3 uses global mutable state to keep track of deferred reference count updates implied by `impl<T> Drop for Py<T>` being called without the currently GIL being held. The necessary synchronization to obtain and apply these reference count updates when PyO3-based code next acquires the GIL is somewhat expensive and can become a significant part of the cost of crossing the Python-Rust boundary.
+
+This functionality can be avoided by adding the `disable-reference-pool` feature. This removes the global reference pool and the associated costs completely. However, it does _not_ remove the `Drop` implementation for `Py<T>` which is necessary to interoperate with existing Rust code written without PyO3-based code in mind. To stay compatible with the wider Rust ecosystem in these cases, we keep the implementation but abort when `Drop` is called without the GIL being held.
```
Comment (davidhewitt) [inline guide/src/performance.md:104]: I wonder if it's worth listing types which contain `Py<T>` internally as things to watch out for, e.g.:

- `PyErr`
- `PyBackedStr`, `PyBackedBytes`

File: src/gil.rs
Comment (davidhewitt) [inline src/gil.rs:1]: Well it's nice to see this file simplified at least 😂

**Review by davidhewitt — APPROVED** [review]
This looks solid to me, thanks! I ache a little bit for the necessary loss of the convenience of the `Py::clone` implementation.

I think the `CloneRef` trait and related question of how to rework `#[pyo3(get)]` is going to be worth exploring ASAP.

**Comment by mejrs** [comment]
Do we have metrics showing the performance differences between this and the current implementation? I'd be uncomfortable with this if there was not a noticeable performance benefit.

> So if we really want to make this hard to enable accidentally as possible, we should probably go for a raw --cfg flag enabled by wrangling compiler flags to which I would also be amenable.

I would very much prefer this over feature flags.

**Comment by adamreichold** [comment]
> Do we have metrics showing the performance differences between this and the current implementation? I'd be uncomfortable with this if there was not a noticeable performance benefit.

Removing deferred clones/reference count increments is necessary for correctness and `py-clone` is additive hiding the now necessarily panicking `Clone` impl to avoid surprises when people update, i.e. they have to enable the feature if they want to continue to use `Clone` and at least get a chance to read about the implications.

The other feature to disable the reference pool is motivated by the CPU profiles from #4085 where it is the single largest contributor which we could do away with. The use case is a bit extreme, but especially for the extension use case the reference pool is mainly an additional convenience users can do without. But of course, it makes usage more difficult so it is opt-in.

File: src/pybacked.rs
Comment (adamreichold) [reply src/pybacked.rs:1]: Created #4133 to remind us to do this after this lands.

File: guide/src/faq.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (adamreichold) [reply guide/src/faq.md:135]: Created #4133 to remind us to do this after this lands.

**Comment by adamreichold** [comment]
I have pushed a new version which should address the review comments so far.

I also added a separate commit which turns the `disable-reference-pool` feature into the `disable_pyo3_reference_pool` conditional compilation flag. I did opt to keep it documented in `features.md` though.

So assuming no further issues are found, before this can be merged we need to reach consensus on two open questions as far as I can see:
- [ ] Do we want to use a feature or a conditional compilation flag. We did decide on inverted semantics in both cases, i.e. the default is safe and the dangerous but fast path must be explicitly enabled. The feature has significantly better usability, but can be abused in non-leaf crates. The conditional compilation flag is intentionally harder to use (which is the intention for using it at all) and set as a global property of the build by design.
- [ ] Do we want another flag/feature/environment variable to turn aborting the process on dropping without the GIL into leaks? Aborts are better for testing but leaking is always safe even though performance can suffer. So maybe we want to couple this to `cfg(debug_assertions)` and abort in debug builds but leak in release builds?

**Comment by adamreichold** [comment]
Any thoughts on two remaining design questions? Otherwise, this should be good to go after conflict resolution.

**Comment by davidhewitt** [comment]
Sorry for the delay, I got delayed by a pile of family responsibility in April which left me quite burned out.

I think a conditional compile flag is good and adding a second one for the downgrade of aborts to leaks seems ok to me too.

I somewhat wonder if we should split the `py-clone` feature into a separate PR, as I think that changes user experience noticeably and I worry if it is slightly lost in the discussion here. Having a new PR just with that diff and a clearer opening post with references to these threads may help users with archaeology later.

**Comment by adamreichold** [comment]
> I think a conditional compile flag is good and adding a second one for the downgrade of aborts to leaks seems ok to me too.

So explicitly, this means we do not want to tie this to `cfg(debug_assertions)` and I will rather make this leak by default and add another flag `disable_pyo3_reference_pool_and_abort_on_drop` which will upgrade the leaks to aborts? 

> I somewhat wonder if we should split the py-clone feature into a separate PR, as I think that changes user experience noticeably and I worry if it is slightly lost in the discussion here. Having a new PR just with that diff and a clearer opening post with references to these threads may help users with archaeology later.

There are somewhat functionally intertwined, so I would glad if I could instead mitigate this by updating the cover letter here to retrace the steps and decisions.

**Comment by davidhewitt** [comment]
> > I think a conditional compile flag is good and adding a second one for the downgrade of aborts to leaks seems ok to me too.
> 
> So explicitly, this means we do not want to tie this to `cfg(debug_assertions)` and I will rather make this leak by default and add another flag `disable_pyo3_reference_pool_and_abort_on_drop` which will upgrade the leaks to aborts?

Hmmm. I think in my mind leaking is the worst case (as it implies GC / memory overhead for the rest of program runtime, which may be hard for users to notice). So I'd prefer abort by default and the second flag changes from aborting to leaking.

If we do move ahead with #4174 then having just one flag to get to aborting seems slightly better too.

> > I somewhat wonder if we should split the py-clone feature into a separate PR, as I think that changes user experience noticeably and I worry if it is slightly lost in the discussion here. Having a new PR just with that diff and a clearer opening post with references to these threads may help users with archaeology later.
> 
> There are somewhat functionally intertwined, so I would glad if I could instead mitigate this by updating the cover letter here to retrace the steps and decisions.

👍 Yep that's reasonable to me!

**Comment by adamreichold** [comment]
> Hmmm. I think in my mind leaking is the worst case (as it implies GC / memory overhead for the rest of program runtime, which may be hard for users to notice). So I'd prefer abort by default and the second flag changes from aborting to leaking.

There are now two cfg flags: `pyo3_disable_reference_pool` and `pyo3_leak_on_drop_without_reference_pool`.

> 👍 Yep that's reasonable to me!

I have updated the cover letter.

File: src/gil.rs (hunk 2 above)
Comment (adamreichold) [reply src/gil.rs:439]: As discussed downthread, we have an additional `pyo3_leak_on_drop_without_reference_pool` conditional compilation flag now which switches from abort to leak on drop without the GIL.

**Review by davidhewitt — APPROVED** [review]
This looks good to me, thanks! 🎉

**Comment by alex** [comment]
> nox > Session check-feature-powerset aborted: some features missing from `full` meta feature: {'py-clone'}.
