### PR TITLE
Fix TypeError when converting Rust encoding errors to Python

### LINKED ISSUE #5651: TypeError converting Rust's FromUtf8Error to Python's UnicodeDecodeError
### Bug Description

Getting an unexpected `TypeError` with strange message when converting Rust's `FromUtf8Error` to Python's `UnicodeDecodeError`. Not sure if other error/exception types are also affected, I haven't had a chance to check more thoroughly.

### Steps to Reproduce

Using a simple function to create a Rust `FromUtf8Error`:

```rust
#[pyfunction]
fn unicode_error() -> PyResult<String> {
    Ok(String::from_utf8(b"\xff".to_vec())?)
}
```

From Python:
```python
>>> unicode_error()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes exactly 5 arguments (1 given)
Normalization failed: type=UnicodeDecodeError args='invalid utf-8 sequence of 1 bytes from index 0'
>>>
```

I expected to get the `UnicodeDecodeError`, instead getting a message (presumably) about PyO3 failing to construct the `UnicodeDecodeError`.

### Backtrace

```shell

```

### Your operating system and version

Ubuntu 24.04

### Your Python version (`python --version`)

Python 3.12.3

### Your Rust version (`rustc --version`)

rustc 1.89.0 (29483883e 2025-08-04)

### Your PyO3 version

0.27.1

### How did you install python? Did you use a virtualenv?

Installed Python through apt

Using a virtualenv and Maturin

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by staticintlucas**
Fixes #5651.

Fixes the implementation of `PyErrArguments` for `string::FromUtf8Error` and `ffi::IntoStringError`.

Removes the broken implementation of `PyErrArguments` for `str::Utf8Error`, `string::FromUtf16Error`, and `char::DecodeUtf16Error`.

Adds a convenience trait called `IntoPyErrWithBytes` for `str::Utf8Error` to allow easy conversion to `PyErr`. The implementation of `From<str::Utf8Error>` for `PyErr` was being used in a few places internally in PyO3, so this felt like the best solution. And unlike the UTF-16 errors, `str::Utf8Error` contains everything needed to construct a Python `UnicodeDecodeError` except the source bytes. I exposed this API publicly since it's probably a pretty common use case (at least compared to UTF-16), but let me know if you want any changes (especially regarding API naming).

### CODE REVIEW

File: src/err/mod.rs [hunk 1]
```diff
@@ -723,6 +723,28 @@ where
...
+///
+/// ```
+/// # use pyo3::prelude::*;
+/// # use pyo3::IntoPyErrWithBytes;
+/// # #[allow(dead_code)]
+/// # fn bytes_to_str(bytes: &[u8]) -> PyResult<&str> {
+/// str::from_utf8(bytes).map_err(|e| e.into_with_bytes(bytes))
+/// # }
+/// ```
+pub trait IntoPyErrWithBytes {
```
Comment (Icxolu) [inline src/err/mod.rs]: Rather that adding a new trait I would prefer if we just made a constructor on `PyUnicodeDecodeError` which returns the `PyErr`. Internally it could make use of  `PyUnicodeDecodeError::new_utf8` to construct it.

Comment (staticintlucas) [reply src/err/mod.rs]: I've moved the implementation to a new constructor for `PyUnicodeDecodeError`. 

I don't want to call `PyUnicodeDecodeError::new_utf8` since it is fallible and I don't want to have to worry about handling errors while already creating an error. I've kept the implementation mostly the same using a private `Utf8ErrorWithBytes` struct which implements `PyErrArguments` and calls `PyUnicodeDecodeError::new_err` under the hood.

Lemme know if this approach sounds reasonable to you, or you want any more changes

**Comment by staticintlucas** [comment]
Will add some tests for my changes ~tomorrow~ *next week* to make codecov happy

File: newsfragments/5668.fixed.md [hunk 2]
```diff
@@ -0,0 +1,2 @@
+Fixed the implementations of `From<string::FromUtf8Error>` and `From<ffi::IntoStringError>` for `PyErr`.
+Removed the failing implementations of `From<str::Utf8Error>`, `From<string::FromUtf16Error>`, and `From<char::DecodeUtf16Error>` for `PyErr`.
```
Comment (davidhewitt) [inline newsfragments/5668.fixed.md]: Please split the "removed" portion into a second file `newsfragments/5668.removed.md`

File: src/err/impls.rs [hunk 3]
```diff
@@ -118,28 +118,77 @@ macro_rules! impl_to_pyerr {
...
+    fn arguments(self, py: Python<'_>) -> Py<PyAny> {
+        let Self { err, bytes } = self;
+        let start = err.valid_up_to();
+        let end = err.error_len().map_or(bytes.len(), |l| start + l);
+
+        let encoding = types::PyString::new(py, "utf-8").into_any();
+        let bytes = types::PyBytes::new(py, &bytes).into_any();
+        let start = types::PyInt::new(py, start).into_any();
+        let end = types::PyInt::new(py, end).into_any();
+        let reason = types::PyString::new(py, "invalid utf-8").into_any();
```
Comment (davidhewitt) [inline src/err/impls.rs:136]: I guess it's hard to do better than this with the current API, we'd have to peek the invalid bytes and deduce the reason for failure?

(Probably not worth doing that, just checking.)

File: src/exceptions.rs [hunk 4]
```diff
@@ -754,8 +759,30 @@ impl PyUnicodeDecodeError {
...
+    ///
+    /// let invalid_utf8 = b"fo\xd8o";
+    /// # #[expect(invalid_from_utf8)]
+    /// let err = std::str::from_utf8(invalid_utf8).expect_err("should be invalid utf8");
+    /// let py_err = PyUnicodeDecodeError::new_err_from_utf8(invalid_utf8, err);
+    /// ```
+    pub fn new_err_from_utf8(bytes: &[u8], err: std::str::Utf8Error) -> crate::PyErr {
+        Utf8ErrorWithBytes {
+            err,
+            bytes: bytes.to_vec(),
```
Comment (davidhewitt) [inline src/exceptions.rs]: Can we avoid this intermediate allocation? I guess not, because we don't have `py: Python` here.

... is it possibly better to take `'py: Python` as an argument, call `new_utf8` above to construct Python bytes immediately, and then use `PyErr::from_value` inside this function?

File: src/err/impls.rs [hunk 5]
```diff
@@ -118,28 +118,77 @@ macro_rules! impl_to_pyerr {
...
+            .into_any()
+            .unbind()
+    }
+}
+
+impl std::convert::From<exceptions::Utf8ErrorWithBytes> for PyErr {
+    fn from(err: exceptions::Utf8ErrorWithBytes) -> PyErr {
+        exceptions::PyUnicodeDecodeError::new_err(err)
+    }
+}
```
Comment (davidhewitt) [inline src/err/impls.rs]: This implementation may not be needed if the changes to `new_err_from_utf8` to call `from_utf8` as proposed in my other comment.

File: src/exceptions.rs [hunk 6]
```diff
@@ -703,6 +703,11 @@ impl_windows_native_exception!(
     native_doc!("WindowsError")
 );
 
+pub(crate) struct Utf8ErrorWithBytes {
+    pub(crate) err: std::str::Utf8Error,
+    pub(crate) bytes: Vec<u8>,
+}
```
Comment (davidhewitt) [inline src/exceptions.rs]: It might make sense for this enum to live in `src/err/impls.rs` closer to where it's used if the `new_err_from_utf8` implementation changes.

File: src/err/impls.rs [hunk 7]
```diff
@@ -179,4 +228,75 @@ mod tests {
...
+            bytes: bytes.clone(),
+        }
+        .into();
+        check_err(utf8_err_with_bytes);
+
+        let utf8_err_with_bytes = exceptions::PyUnicodeDecodeError::new_err_from_utf8(
+            &bytes,
+            std::str::from_utf8(&bytes).expect_err("\\xff is invalid utf-8"),
+        );
+        check_err(utf8_err_with_bytes);
```
Comment (davidhewitt) [inline src/err/impls.rs]: This test might make sense to be in `src/exceptions.rs` given it tests that constructor.

File: src/exceptions.rs (hunk 4 above)
Comment (davidhewitt) [reply src/exceptions.rs]: EDIT I just saw your comment about fallibility.

I think if `new_utf8` returns an error, we could just bubble that up with `return e`. I guess that only happens in weird edge cases like keyboard interrupt, memory allocation error etc.

Comment (davidhewitt) [reply src/exceptions.rs]: ... or we just return `PyResult<PyErr>` here and let callers decide whether to flatten the other errors away, but the API does feel a bit awkward then.

Comment (staticintlucas) [reply src/exceptions.rs]: Yeah I didn't really want to return a `PyResult<PyErr>`, in part because it would be an awkward API and in part to keep symmetry between `new_err_from_utf8` and `new_err`.

Adding a `py: Python` argument would also break the symmetry with `new_err`, but if you think that's worth it to avoid the extra allocation then I can make that change

File: src/err/impls.rs (hunk 3 above)
Comment (staticintlucas) [reply src/err/impls.rs:136]: We can check for incomplete byte sequences (i.e. unexpected end of input) versus invalid bytes by checking if `err.error_len()` is `None`. But the Rust error type does not differentiate between the different kinds of invalid bytes (invalid start byte, invalid continuation, encoding out of range, etc...)

**Comment by staticintlucas** [comment]
I think the failing test should be due to Rust diagnostic messages changing in 1.92, not related to my change

File: src/exceptions.rs (hunk 4 above)
Comment (davidhewitt) [reply src/exceptions.rs]: On reflection I think that having the return type just be `PyErr` is good enough, the failure mode is _unlikely_ and users will probably always just flatten the outer error anyway because there's not an obvious alternative.

Taking `py: Python` I think is fine; the discussion we've had around other parts of the PyO3 error handling story is strongly leaning towards the conclusion that we will want to require `py: Python` to _create_ a `PyErr` in the future (because it leads to more efficient implementations, as we find here).

**Comment by Icxolu** [comment]
I took the liberty to rebase this to current main and updated `new_err_from_utf8` to take a `Python` token and making use of `new_utf8`, flattening failures.

Thanks @staticintlucas for the initial implementation

@davidhewitt Do you want to take a final look?

File: src/err/impls.rs [hunk 8]
```diff
@@ -118,28 +118,78 @@ macro_rules! impl_to_pyerr {
...
+    fn arguments(self, py: Python<'_>) -> Py<PyAny> {
+        Utf8ErrorWithBytes {
+            err: self.utf8_error(),
+            bytes: self.into_bytes(),
+        }
+        .arguments(py)
+    }
+}
+
+impl std::convert::From<std::string::FromUtf8Error> for PyErr {
```
Comment (Tpt) [inline src/err/impls.rs]:
```suggestion
impl From<std::string::FromUtf8Error> for PyErr {
```

File: src/err/impls.rs [hunk 9]
```diff
@@ -118,28 +118,78 @@ macro_rules! impl_to_pyerr {
...
+    fn arguments(self, py: Python<'_>) -> Py<PyAny> {
+        Utf8ErrorWithBytes {
+            err: self.utf8_error(),
+            bytes: self.into_cstring().into_bytes(),
+        }
+        .arguments(py)
+    }
+}
+
+impl std::convert::From<std::ffi::IntoStringError> for PyErr {
```
Comment (Tpt) [inline src/err/impls.rs]:
```suggestion
impl From<std::ffi::IntoStringError> for PyErr {
```

**Comment by davidhewitt** [comment]
Looks like a genuine msrv failure
