### PR TITLE
Fix PyDictIterator's segfault(for #159)

### LINKED ISSUE #159: Segfaults when iterating a PyDict with >   262141 keys
I think the number of keys is irrelevant but more to do with the object size. 

Create a dict with 127 keys and values, rust iteration segfaults by passing a null dict (po) to Pydict_Next on Linux. Will send a repro tomorrow.  I am on mobile.

### PR DESCRIPTION
**Pull request by kngwyu**
Fix #159 
Thanks @fdoyon for debugging!

### CODE REVIEW

**Comment by konstin** [comment]
Thank you and a big :+1: for both of you! I'll add some style comments because if we add the test as example people will copy it's style so we should be careful not to promote bad style.

File: examples/rustapi_module/src/dict_iter.rs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+        let mut seen = 0u32;
+        for (sym, values) in dict.iter() {
+            seen += 1;
+            println!(
+                "{:4}/{:4} iterations:{}=>{}",
+                seen, self.expected, sym, values
+            );
+        }
+
+        match seen == self.expected {
```
Comment (konstin) [inline examples/rustapi_module/src/dict_iter.rs]: This should be if (afaik clippy also complains about that)

File: examples/rustapi_module/src/dict_iter.rs [hunk 2]
```diff
@@ -0,0 +1,42 @@
+use pyo3::prelude::*;
+
+use pyo3::exceptions as exc;
+use pyo3::types::PyDict;
+
+#[pymodinit(_test_dict)]
```
Comment (konstin) [inline examples/rustapi_module/src/dict_iter.rs]: I'd like to move all examples to module names without underscores

File: examples/rustapi_module/src/dict_iter.rs [hunk 3]
```diff
@@ -0,0 +1,42 @@
+use pyo3::prelude::*;
+
+use pyo3::exceptions as exc;
```
Comment (konstin) [inline examples/rustapi_module/src/dict_iter.rs]: No need to rename here

File: examples/rustapi_module/src/dict_iter.rs [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+#[pyclass]
+pub struct DictSize {
+    expected: u32,
+}
+
+#[pymethods]
+impl DictSize {
+    #[new]
+    fn __new__(obj: &PyRawObject, expected: u32) -> PyResult<()> {
+        obj.init(|_t| DictSize { expected })
```
Comment (konstin) [inline examples/rustapi_module/src/dict_iter.rs]: This will need `||` since PyToken was removed.

File: examples/rustapi_module/tests/test_dict_iter.py [hunk 5]
```diff
@@ -0,0 +1,12 @@
+from rustapi_module._test_dict import DictSize
+import pytest
+
+@pytest.mark.parametrize(
+    "size",
+    [64, 128, 256],
+)
+def test_size(size):
+    d = {}
+    for i in range(0,size):
```
Comment (konstin) [inline examples/rustapi_module/tests/test_dict_iter.py]: `range(size)`

File: src/types/dict.rs [hunk 6]
```diff
@@ -148,13 +148,19 @@ impl PyDict {
...
+        }
     }
 }
 
-pub struct PyDictIterator<'a> {
-    dict: &'a PyDict,
+pub struct PyDictIterator<'dict> {
+    dict: PyObject,
     pos: isize,
+    __marker: PhantomData<&'dict ()>,
```
Comment (konstin) [inline src/types/dict.rs]: Is there a special reason not to use `Python` as marker here. Also imho we don't need the underscores since the fields are private anyway

**Comment by kngwyu** [comment]
Ah but looks test fails after rebasing.
Please wait for a while.

File: src/types/dict.rs [hunk 7]
```diff
@@ -166,7 +172,7 @@ impl<'a> Iterator for PyDictIterator<'a> {
             let mut key: *mut ffi::PyObject = mem::uninitialized();
             let mut value: *mut ffi::PyObject = mem::uninitialized();
             if ffi::PyDict_Next(self.dict.as_ptr(), &mut self.pos, &mut key, &mut value) != 0 {
-                let py = self.dict.py();
+                let py = Python::assume_gil_acquired();
```
Comment (konstin) [inline src/types/dict.rs]: I prefer the old version here since it makes sure that this method isn't changed into some gil-less variant one day and this becomes essentially UB

Comment (kngwyu) [reply src/types/dict.rs]: `PyObject` doesn't implement `PyObjectWithGIL`.
We need to change this line if we use `PyObject`

Comment (konstin) [reply src/types/dict.rs]: ok that's fine; Could you add that as a comment for future reference?

File: src/types/dict.rs [hunk 8]
```diff
@@ -175,6 +181,12 @@ impl<'a> Iterator for PyDictIterator<'a> {
     }
 }
 
+impl<'py> Drop for PyDictIterator<'py> {
+    fn drop(&mut self) {
+        unsafe { ffi::Py_DECREF(self.dict.as_ptr()) }
```
Comment (konstin) [inline src/types/dict.rs]: This confuses me: Where have we called INCREF so we can DECREF here?

**Comment by kngwyu** [comment]
Thanks for your review!
I fixed review points and added
```rust
 impl<'py> Drop for PyDictIterator<'py> {
    fn drop(&mut self) {
        unsafe { ffi::Py_DECREF(self.dict.as_ptr()) }
    }
}
```
.
Since we call INCREF for PyObject when getting it from `&PyDict` so I think it's correct, but not sure.

File: src/types/dict.rs (hunk 8 above)
Comment (kngwyu) [reply src/types/dict.rs]: In PyDict::iter.
`to_object` calls `from_borrowed_object`.

**Comment by konstin** [comment]
Afaik that's already done by 

https://github.com/PyO3/pyo3/blob/aed0466915527f15656b8dbc343bd0d00c4e7682/src/object.rs#L315-L322

**Comment by kngwyu** [comment]
Ah, thanks, I missed it.

File: src/types/dict.rs (hunk 7 above)
Comment (kngwyu) [reply src/types/dict.rs]: Now I changed `PyDictIterator` to have `Python`.
Still comment is needed?

Comment (konstin) [reply src/types/dict.rs]: No, that's clear now

**Comment by fdoyon** [comment]
Thanks gents, I had hoped to contribute some code but it seems I am missing some understanding of the memory model. :+1:

**Comment by kngwyu** [comment]
@fdoyon 
The key point is `&PyDict` is a pointer to `*mut ffi::PyObject` and it points an element in ReleasePool.
```rust
pub unsafe fn register_owned(_py: Python, obj: *mut ffi::PyObject) -> &PyObjectRef {
    let pool: &'static mut ReleasePool = &mut *POOL;
    pool.owned.push(obj);
    &*(&pool.owned[pool.owned.len() - 1] as *const *mut ffi::PyObject as *const PyObjectRef)
}
```

So we can avoid segfault by having `*mut ffi::PyObject` directly.
But, as you commented, it's still a big problem. This kind of bug can happens anywhere in our codebase.

**Comment by kngwyu** [comment]
Made a separate issue #271
