### PR TITLE
fix error with complex enums with many fields

### LINKED ISSUE #4827: Enum with struct variants can only have 12 fields
### Bug Description

I was refactoring some code from 

```rust
#[pyclass]
enum TupleEnum {
   Variant1(InnerType1),
   Variant2(InnerType2),
}

#[pyclass]
struct InnerType1 {
    field_1: u32,
    field_2: u32,
    field_3: String,
    field_4: f32,
}

...

```

to this

```rust
#[pyclass]
enum StructEnum {
    Variant1 {
        field_1: u32,
        field_2: u32,
        field_3: String,
        field_4: f32,
    },
    Variant2 {
        etc...
    }
}
```

Effectively getting rid of the wrapped types and representing them in the enum's variants directly.

However, it looks like there is some kind of limit on the number of fields that you can have in an enum member. The example in the "Steps to reproduce" produces this error:

```
error[E0277]: `(&str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str)` cannot be converted to a Python object
   --> pyanif/src/blocks/beam.rs:373:1
    |
373 | #[pyclass]
    | ^^^^^^^^^^ the trait `pyo3::IntoPyObject<'_>` is not implemented for `(&str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str)`
    |
    = note: `IntoPyObject` is automatically implemented by the `#[pyclass]` macro
    = note: if you do not wish to have a corresponding Python type, implement it manually
    = note: if you do not own `(&str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str)` you can perform a manual conversion to one of the types in `pyo3::types::*`
    = help: the following other types implement trait `pyo3::IntoPyObject<'py>`:
              &(T0, T1)
              &(T0, T1, T2)
              &(T0, T1, T2, T3)
              &(T0, T1, T2, T3, T4)
              &(T0, T1, T2, T3, T4, T5)
              &(T0, T1, T2, T3, T4, T5, T6)
              &(T0, T1, T2, T3, T4, T5, T6, T7)
              &(T0, T1, T2, T3, T4, T5, T6, T7, T8)
            and 17 others
note: required by a bound in `pyo3::IntoPyObjectExt::into_py_any`
   --> /home/majp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.23.3/src/conversion.rs:367:33
    |
367 | pub trait IntoPyObjectExt<'py>: IntoPyObject<'py> + into_pyobject_ext::Sealed {
    |                                 ^^^^^^^^^^^^^^^^^ required by this bound in `IntoPyObjectExt::into_py_any`
...
380 |     fn into_py_any(self, py: Python<'py>) -> PyResult<Py<PyAny>> {
    |        ----------- required by a bound in this associated function
    = note: this error originates in the attribute macro `pyclass` (in Nightly builds, run with -Z macro-backtrace for more info)

```

### Steps to Reproduce

```rust
// my_module.rs

use pyo3::prelude::*

enum StructEnum {
    Variant1 {
        field_1: u32,
        field_2: f32,
        field_3: String,
        field_4: f32,
        field_5: f32,
        field_6: u32,
        field_7: u32,
        field_8: u32,
        field_9: u32,
        field_10: u32,
        field_11: u32,
        field_12: u32,
        field_13: u32,
        field_14: u32,
        field_15: u32,
    }
}
```

won't compile. However, with 12 fields, there is no error:

```rust
#[pyclass]
enum StructEnum {
    Variant1 {
        field_1: u32,
        field_2: f32,
        field_3: String,
        field_4: f32,
        field_5: f32,
        field_6: u32,
        field_7: u32,
        field_8: u32,
        field_9: u32,
        field_10: u32,
        field_11: u32,
        field_12: u32,
        // field_13: u32,
        // field_14: u32,
        // field_15: u32,
    }
}
```

### Backtrace

```shell
error[E0277]: `(&str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str)` cannot be converted to a Python object
   --> pyanif/src/blocks/beam.rs:373:1
    |
373 | #[pyclass]
    | ^^^^^^^^^^ the trait `pyo3::IntoPyObject<'_>` is not implemented for `(&str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str)`
    |
    = note: `IntoPyObject` is automatically implemented by the `#[pyclass]` macro
    = note: if you do not wish to have a corresponding Python type, implement it manually
    = note: if you do not own `(&str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str, &str)` you can perform a manual conversion to one of the types in `pyo3::types::*`
    = help: the following other types implement trait `pyo3::IntoPyObject<'py>`:
              &(T0, T1)
              &(T0, T1, T2)
              &(T0, T1, T2, T3)
              &(T0, T1, T2, T3, T4)
              &(T0, T1, T2, T3, T4, T5)
              &(T0, T1, T2, T3, T4, T5, T6)
              &(T0, T1, T2, T3, T4, T5, T6, T7)
              &(T0, T1, T2, T3, T4, T5, T6, T7, T8)
            and 17 others
note: required by a bound in `pyo3::IntoPyObjectExt::into_py_any`
   --> /home/majp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.23.3/src/conversion.rs:367:33
    |
367 | pub trait IntoPyObjectExt<'py>: IntoPyObject<'py> + into_pyobject_ext::Sealed {
    |                                 ^^^^^^^^^^^^^^^^^ required by this bound in `IntoPyObjectExt::into_py_any`
...
380 |     fn into_py_any(self, py: Python<'py>) -> PyResult<Py<PyAny>> {
    |        ----------- required by a bound in this associated function
    = note: this error originates in the attribute macro `pyclass` (in Nightly builds, run with -Z macro-backtrace for more info)


```

### Your operating system and version

Ubuntu 24.04

### Your Python version (`python --version`)

Python 3.12.3

### Your Rust version (`rustc --version`)

rustc 1.83.0 (90b35a623 2024-11-26)

### Your PyO3 version

0.23.3

### How did you install python? Did you use a virtualenv?

No venv, just the `python3` that comes with Ubuntu 24.04.

### Additional Info

Thanks for this awesome project. I imagine creating this is an insane task. So lots of appreciation from here :)

### PR DESCRIPTION
**Pull request by Icxolu**
Changes the expansion of `__match_args__` for complex enums to not use Rust tuples to lift the limit of 12 fields. 

Closes #4827

### CODE REVIEW

File: pyo3-macros-backend/src/pyclass.rs [hunk 1]
```diff
@@ -1185,34 +1186,30 @@ fn impl_complex_enum_variant_cls(
...
-        },
-    };
-
-    let variant_match_args = gen_py_const(variant_cls_type, &spec, ctx);
+    let spec = FnSpec::parse(
+        &mut match_args_impl.sig,
+        &mut match_args_impl.attrs,
+        Default::default(),
+    )?;
+    let variant_match_args = impl_py_class_attribute(variant_cls_type, &spec, ctx)?;
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/pyclass.rs:1210]: I had an initial feeling that building the syntax tree and then parsing it might be a bit convoluted (we could just construct a `FnSpec` directly) but maybe this is actually quite elegant because it means the `#[classattr]` defined above fully defines the final result.

It would have been nice to avoid the fallibility, but I think it's fine on balance.

**Review by davidhewitt — APPROVED** [review]
Super, many thanks! Happy New Year :)

File: pyo3-macros-backend/src/pyclass.rs (hunk 1 above)
Comment (Icxolu) [reply pyo3-macros-backend/src/pyclass.rs:1210]: > it means the `#[classattr]` defined above fully defines the final result.

This was my motivation for this. I think it's more robust against accidental inconsistencies (now and in the future)

> It would have been nice to avoid the fallibility, but I think it's fine on balance.

Yeah, I was a bit sad as well . It _should_ never fail, so we could also `expect`, but that did not feel much better to me.

Happy New Year to you as well 🎆
