### PR TITLE
`pyo3-build-config`: rebuild when `PYO3_ENVIRONMENT_SIGNATURE` value changed

### LINKED ISSUE #2724: `pyo3-build-config` doesn't rebuild when virtualenv Python version changed
### Bug Description

When recreating a virtualenv to a different Python version/implementation, `pyo3-build-config` doesn't rebuild which can cause `undefined symobl: xxx` issue on import.

### Steps to Reproduce

```bash
root@ubuntu:~# maturin new pyo3-repro
✔ 🤷 Which kind of bindings to use? · pyo3
  ✨ Done! New project created pyo3-repro
root@ubuntu:~# cd pyo3-repro/
root@ubuntu:~/pyo3-repro# virtualenv -p pypy3 venv
created virtual environment PyPy3.8.13.final.0-64 in 1736ms
  creator PyPy3Posix(dest=/root/pyo3-repro/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.4.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
root@ubuntu:~/pyo3-repro# . venv/bin/activate
(venv) root@ubuntu:~/pyo3-repro# maturin develop
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /root/pyo3-repro/venv/bin/python
   Compiling target-lexicon v0.12.5
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.47
   Compiling once_cell v1.16.0
   Compiling quote v1.0.21
   Compiling libc v0.2.137
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.103
   Compiling parking_lot_core v0.9.4
   Compiling smallvec v1.10.0
   Compiling scopeguard v1.1.0
   Compiling cfg-if v1.0.0
   Compiling unindent v0.1.10
   Compiling indoc v1.0.7
   Compiling lock_api v0.4.9
   Compiling memoffset v0.6.5
   Compiling pyo3-build-config v0.17.3
   Compiling parking_lot v0.12.1
   Compiling pyo3-ffi v0.17.3
   Compiling pyo3 v0.17.3
   Compiling pyo3-macros-backend v0.17.3
   Compiling pyo3-macros v0.17.3
   Compiling pyo3-repro v0.1.0 (/root/pyo3-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 34.18s
📦 Built wheel for PyPy 3.8 to /tmp/.tmpJbZYXj/pyo3_repro-0.1.0-pp38-pypy38_pp73-linux_x86_64.whl
🛠  Installed pyo3-repro-0.1.0
(venv) root@ubuntu:~/pyo3-repro# deactivate
root@ubuntu:~/pyo3-repro# rm -rf venv/
root@ubuntu:~/pyo3-repro# virtualenv -p python3.10 venv
created virtual environment CPython3.10.6.final.0-64 in 1529ms
  creator CPython3Posix(dest=/root/pyo3-repro/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.4.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
root@ubuntu:~/pyo3-repro# . venv/bin/activate
(venv) root@ubuntu:~/pyo3-repro# maturin develop
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /root/pyo3-repro/venv/bin/python
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
📦 Built wheel for CPython 3.10 to /tmp/.tmp7JKmvP/pyo3_repro-0.1.0-cp310-cp310-linux_x86_64.whl
🛠  Installed pyo3-repro-0.1.0
(venv) root@ubuntu:~/pyo3-repro# python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyo3_repro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pyo3-repro/venv/lib/python3.10/site-packages/pyo3_repro/__init__.py", line 1, in <module>
    from .pyo3_repro import *
ImportError: /root/pyo3-repro/venv/lib/python3.10/site-packages/pyo3_repro/pyo3_repro.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyPyTuple_Size
(venv) root@ubuntu:~/pyo3-repro# cat target/debug/build/pyo3-build-config-492403e83d77b89c/out/pyo3-build-config.txt
implementation=PyPy
version=3.8
shared=true
abi3=false
lib_name=pypy3-c
lib_dir=/usr/bin
executable=/root/pyo3-repro/venv/bin/python
pointer_width=64
build_flags=
suppress_build_script_link_lines=false
```

### Backtrace

_No response_

### Your operating system and version

Ubuntu 22.04

### Your Python version (`python --version`)

PyPy 3.8 & Python 3.10

### Your Rust version (`rustc --version`)

rustc 1.65.0

### Your PyO3 version

0.17.3

### How did you install python? Did you use a virtualenv?

apt, use a virtualenv

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by messense**
Fixes #2724

### CODE REVIEW

File: pyo3-build-config/src/impl_.rs [hunk 1]
```diff
@@ -1685,6 +1685,8 @@ fn get_env_interpreter() -> Option<PathBuf> {
 ///   4. `python3`, as above
 pub fn find_interpreter() -> Result<PathBuf> {
     if let Some(exe) = env_var("PYO3_PYTHON") {
+        println!("cargo:rerun-if-env-changed=PYO3_PYTHON_VERSION");
+        println!("cargo:rerun-if-env-changed=PYO3_PYTHON_IMPLEMENTATION");
```
Comment (messense) [inline pyo3-build-config/src/impl_.rs:1689]: Though we need to decide whether these two env vars should override version and implementation we get from the Python interpreter like what `PYO3_CROSS_PYTHON_VERSION` and `PYO3_CROSS_PYTHON_IMPLEMENTATION`. I prefer not to do that, what do you guys think?

Comment (adamreichold) [reply pyo3-build-config/src/impl_.rs:1689]: Hhhmmm, I think if these are passed explicitly, they should override what the interpreter says. We could issue a warning if their contents does not match what the interpreter says though.

Comment (messense) [reply pyo3-build-config/src/impl_.rs:1689]: I prefer not to because they are not intended to be used to override Python version and implementation. Perhaps it's better to be named as `_PYO3_XXX` if we agree to not override.

That said, I'm not strongly opposed to make them override what the interpreter says.

Comment (adamreichold) [reply pyo3-build-config/src/impl_.rs:1689]: If we really want them only to trigger rebuilds, how about `PYO3_ENVIRONMENT_SIGNATURE` and document that this has no other effect than to trigger rebuilds if its value changes. It would then be up to the other layers of automation like Maturin what they put in there (like interpreter version used by the venv).

Comment (messense) [reply pyo3-build-config/src/impl_.rs:1689]: An opaque variable is certainly better, thanks for the idea!

**Review by adamreichold — APPROVED** [review]

**Review by davidhewitt — APPROVED** [review]
Yep I think this makes sense too 👍
