### PR TITLE
Introspection: fix return type hint for Result<()>

### LINKED ISSUE #5645: Return value hint for `__init__` is wrong, should be `None`
_Originally posted by @davidhewitt in https://github.com/PyO3/pyo3/pull/4951#discussion_r2554099826_

### PR DESCRIPTION
**Pull request by Tpt**
Uses a hack to get const specialization working

Closes #5645

### CODE REVIEW

File: src/impl_/introspection.rs [hunk 1]
```diff
@@ -17,6 +19,73 @@ impl<T: PyReturnType, E> PyReturnType for Result<T, E> {
...
+
+impl IsEmptyTuple for IsEmptyTupleFalse {
+    const VALUE: bool = false;
+}
+
+pub struct IsEmptyTupleTrue;
+
+impl IsEmptyTuple for IsEmptyTupleTrue {
+    const VALUE: bool = true;
+}
```
Comment (davidhewitt) [inline src/impl_/introspection.rs]: We have `pyclass::boolean_struct::Boolean` which might be worth re-using?

File: src/impl_/introspection.rs [hunk 2]
```diff
@@ -17,6 +19,73 @@ impl<T: PyReturnType, E> PyReturnType for Result<T, E> {
...
 
+/// Hack to guess if the output type is the empty tuple
+///
+/// Inspiration: <https://github.com/GoldsteinE/gh-blog/blob/master/const_deref_specialization/src/lib.md>
+/// TL;DR: with closure we can get the compiler to return us the output type of the usual deref-based specialization
+pub const fn is_empty_tuple_from_closure<B: IsEmptyTuple>(
+    _closure_returning_bool: &impl FnOnce() -> B,
+) -> bool {
+    B::VALUE
+}
```
Comment (davidhewitt) [inline src/impl_/introspection.rs]: This is neat, it provides a way to lift type inference into compile time 🎉

File: src/conversion.rs [hunk 3]
```diff
@@ -601,6 +601,9 @@ impl<'py> IntoPyObject<'py> for () {
     type Output = Bound<'py, Self::Target>;
     type Error = Infallible;
 
+    #[cfg(feature = "experimental-inspect")]
+    const OUTPUT_TYPE: TypeHint = PyTuple::TYPE_HINT; // TODO(Tpt): should be tuple[()]
```
Comment (davidhewitt) [inline src/conversion.rs:599]: I suppose this depends on having a Python ast value for `()`?

Comment (Tpt) [reply src/conversion.rs:599]: Yes!

File: src/impl_/introspection.rs (hunk 1 above)
Comment (Tpt) [reply src/impl_/introspection.rs]: Indeed. Done!

File: newsfragments/5674.fixed.md [hunk 4]
```diff
@@ -0,0 +1 @@
+Introspection: fix the return type annotation of `PyResult<()` (must be `None` and not `tuple`)
```
Comment (davidhewitt) [inline newsfragments/5674.fixed.md]:
```suggestion
Introspection: fix the return type annotation of `PyResult<()>` (must be `None` and not `tuple`)
```

File: pyo3-macros-backend/src/type_hint.rs [hunk 5]
```diff
@@ -148,7 +148,17 @@ impl PythonTypeHint {
...
+                quote! {{
+                    const TYPE: #pyo3_crate_path::inspect::TypeHint = if #pyo3_crate_path::impl_::introspection::is_empty_tuple_from_closure(&|| {
+                        #pyo3_crate_path::impl_::introspection::IsEmptyTupleChecker::<#t>::new().check()
+                    }) {
+                        #pyo3_crate_path::inspect::TypeHint::builtin("None")
+                    } else {
+                        <#t as #pyo3_crate_path::impl_::introspection::PyReturnType>::OUTPUT_TYPE
+                    };
+                    TYPE
+                }}
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/type_hint.rs]: I was studying this again and I think I'd prefer a simplification here.

We have the `probes.rs` file which has similar type-level logic at compile time. It's limited to cases where the exact type `T` is known, which is also true here (`#t`).

The closure type inference looks like it is super helpful where we need to get from an expression to a type. I think it might just be more complexity than is needed for this one.

I think the solution will look something like:

```suggestion
                quote! {
                    #[allow(unused_imports)]
                    use #pyo3_path::impl_::pyclass::Probe as _;
                    if #pyo3_path::impl_::pyclass::IsEmptyTuple::<#t>::VALUE {
                        #pyo3_crate_path::inspect::TypeHint::builtin("None")
                    } else {
                        <#t as #pyo3_crate_path::impl_::introspection::PyReturnType>::OUTPUT_TYPE
                    }
                }
```

Will need a suitable `IsEmptyTuple` probe defined.

I feel bad asking for such beautiful const-eval logic to be simplified away, but we do already have the probe pattern and it seems like that's enough here too. Maybe we'll find another excuse for the closure type inference trick now that we know how to use it? 😃 

Sorry also to miss this on first review; I've had a long week.

Comment (Tpt) [reply pyo3-macros-backend/src/type_hint.rs]: That's much nicer indeed! Thank you for the tip. Done.

File: src/pyclass.rs [hunk 6]
```diff
@@ -113,8 +113,8 @@ pub mod boolean_struct {
         }
     }
 
-    pub struct True(());
-    pub struct False(());
+    pub struct True;
+    pub struct False;
```
Comment (davidhewitt) [inline src/pyclass.rs]: I think these changes can be reverted:

```suggestion
    pub struct True(());
    pub struct False(());
```
