### PR TITLE
remove private types from `pyo3-ffi`

### LINKED ISSUE #5062: ffi-check fails on 3.13.3
### Bug Description

It looks like https://github.com/python/cpython/commit/3f3863281bb3cd40efc2f1c4bed901457b8cd170 changed the names of the fields on a private type in `Code.h`, and that's making ffi-check unhappy:

```
error[E0609]: no field `original_opcode` on type `bindings::_PyCoLineInstrumentationData`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `line_delta` on type `bindings::_PyCoLineInstrumentationData`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Given that this happened in a 3.13 bugfix release, is the most appropriate fix just to use the new names in the ffi?

### Steps to Reproduce

Using a CPython 3.13.3 interpreter:

```
nox -s ffi-check
```

### Backtrace

```shell

```

### Your operating system and version

Mac

### Your Python version (`python --version`)

3.13.3

### Your Rust version (`rustc --version`)

1.87 nightly

### Your PyO3 version

current `main`

### How did you install python? Did you use a virtualenv?

pyenv

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by davidhewitt**
Related to #4379, also closes #5062 

This PR removes all types and structures starting with `_Py` from `pyo3-ffi`. These are private and may be freely altered in patch releases (as seen in #5062), so we should not expose these to users, and should only bother defining them in `pyo3-ffi` when they're necessary to satisfy public CPython ABI.

As part of this PR I changed the `opaque_struct!` macro to require explicitly opting-in to `pub` (or `pub(crate)`), rather than always making the defined item public.

### CODE REVIEW

File: pyo3-ffi/src/cpython/code.rs [hunk 1]
```diff
@@ -177,20 +136,24 @@ pub struct PyCodeObject {
...
     #[cfg(not(Py_3_12))]
-    pub _co_code: *mut PyObject,
+    _co_code: *mut PyObject,
     #[cfg(not(Py_3_12))]
-    pub _co_linearray: *mut c_char,
+    _co_linearray: *mut c_char,
     #[cfg(Py_3_13)]
+    #[allow(
+        private_interfaces,
+        reason = "field is public, but the type is opaque and private"
```
Comment (mejrs) [inline pyo3-ffi/src/cpython/code.rs:145]: we don't have the msrv for this

Comment (mejrs) [reply pyo3-ffi/src/cpython/code.rs:145]: Also, isn't `PyCodeObject` itself opaque? I'd rather get make it opaque than deal with all this conditional compilation.

**Review by mejrs — COMMENTED** [review]
Thanks! Were you planning to just limit this to underscore apis? There are things like PyCodeObject and PyHeapTypeObject that aren't exactly public api either.

File: pyo3-ffi/src/cpython/code.rs (hunk 1 above)
Comment (davidhewitt) [reply pyo3-ffi/src/cpython/code.rs:145]: Yes, you're right:

https://docs.python.org/3/c-api/code.html#c.PyCodeObject

> The C structure of the objects used to describe code objects. The fields of this type are subject to change at any time.

I read that as "including in patch releases", so we should not expose this structure.

**Comment by davidhewitt** [comment]
> There are things like PyCodeObject and PyHeapTypeObject that aren't exactly public api either.

As per https://github.com/PyO3/pyo3/pull/5064#discussion_r2039275709 have made `PyCodeObject` opaque. 

There are definitely other structures which should not be public, but given that each time we change this we might break downstream code I would prefer to just remove these when there's a good reason, e.g. the CPython headers hide the symbol or explicitly document as private API. Also if we removed `PyHeapTypeObject`, probably warrants its own PR at the very least.

**Review by mejrs — APPROVED** [review]
Thanks, that's a nice line diff.

**Comment by clin1234** [comment]
Wholeheartedly agree, especially when CPython's C interfaces changes in prerelease builds!

**Comment by mejrs** [comment]
@davidhewitt the auto merge didn't quite work:

```
 error: type `_PyCompilerSrcLocation` is more private than the item `PyFutureFeatures::ff_location`
    --> pyo3-ffi/src/cpython/compile.rs:53:5
     |
  53 |     pub ff_location: _PyCompilerSrcLocation,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ field `PyFutureFeatures::ff_location` is reachable at visibility `pub`
     |
  note: but type `_PyCompilerSrcLocation` is only usable at visibility `pub(self)`
    --> pyo3-ffi/src/cpython/compile.rs:36:1
     |
  36 | struct _PyCompilerSrcLocation {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: `-D private-interfaces` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(private_interfaces)]`
  
  error: could not compile `pyo3-ffi` (lib) due to 1 previous error
```

**Comment by davidhewitt** [comment]
Thanks, I've decided to fix by restricting visibility of `PyFutureFeatures` struct to < 3.10 (it was unused in the public C API after the `PyFuture_From*` functions were made internal in 3.10).

**Comment by ngoldbaum** [comment]
Let's try to merge once again.

**Comment by ngoldbaum** [comment]
Windows build failed with:

```
  error[E0609]: no field `co_freevars` on type `code::PyCodeObject`
    --> pyo3-ffi\src\cpython\code.rs:89:35
     |
  89 |     crate::PyTuple_GET_SIZE((*op).co_freevars)
     |                                   ^^^^^^^^^^^ unknown field
     |
     = note: available field is: `0`
  
  For more information about this error, try `rustc --explain E0609`
```
