### PR TITLE
Fix fixed offset timezone conversion bug.

### LINKED ISSUE #3267: PyO3 incorrectly converts local to UTC times on FixedOffset conversion
### Bug Description

When converting to/from `datetime.datetime`/`DateTime<FixedOffset>`, PyO3 is using `DateTime::naive_utc` and `DateTime::from_utc` -- I believe these should be `naive_local` and `from_local`, respectively.

### Steps to Reproduce

```
    #[test]
    fn pyo3_tz_bug() {
        Python::with_gil(|py| {
            let code = r#"
import datetime
t = datetime.datetime.fromtimestamp(86400).replace(tzinfo=datetime.timezone(datetime.timedelta(hours=-8)))
            "#.trim();

            let globals = PyDict::new(py);
            py.run(code, Some(globals), None).unwrap();

            // Get ISO 8601 string from python
            let t = globals.get_item("t").unwrap();
            let py_iso_str = t.call_method0("isoformat").unwrap();

            // Get ISO 8601 string from rust
            let t = t.extract::<DateTime<FixedOffset>>().unwrap();
            let rust_iso_str = t.to_rfc3339();

            // They should be equal
            assert_eq!(py_iso_str.to_string(), rust_iso_str);
        })
    }
```

This test fails with

```
assertion failed: `(left == right)`
  left: `"1970-01-02T00:00:00-08:00"`,
 right: `"1970-01-01T16:00:00-08:00"`
 ```
 
 I think the bug probably went unnoticed because it exists on both the `IntoPy` and `FromPy` paths so cancels itself out when you go to and from, but you can induce it by creating dates in native python as shown above.

### Backtrace

_No response_

### Your operating system and version

OS X Ventura 13.4

### Your Python version (`python --version`)

3.11

### Your Rust version (`rustc --version`)

1.70

### Your PyO3 version

0.19

### How did you install python? Did you use a virtualenv?

brew, no

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by grantslatton**
Closes #3267

### CODE REVIEW

File: src/conversions/chrono.rs [hunk 1]
```diff
@@ -729,6 +730,30 @@ mod tests {
...
+    #[test]
+    fn test_pyo3_offset_fixed_frompyobject_created_in_python() {
+        Python::with_gil(|py| {
+            let code = r#"
+import datetime
+t = datetime.datetime.fromtimestamp(12345).replace(tzinfo=datetime.timezone(datetime.timedelta(hours=-8)))
+            "#.trim();
+
+            let globals = PyDict::new(py);
+            py.run(code, Some(globals), None).unwrap();
```
Comment (adamreichold) [inline src/conversions/chrono.rs:742]: I think this might look simpler by using [`eval`](https://docs.rs/pyo3/latest/pyo3/marker/struct.Python.html#method.eval)?

File: src/conversions/chrono.rs [hunk 2]
```diff
@@ -729,6 +730,30 @@ mod tests {
         })
     }
 
+    #[test]
+    fn test_pyo3_offset_fixed_frompyobject_created_in_python() {
+        Python::with_gil(|py| {
+            let code = r#"
+import datetime
+t = datetime.datetime.fromtimestamp(12345).replace(tzinfo=datetime.timezone(datetime.timedelta(hours=-8)))
```
Comment (adamreichold) [inline src/conversions/chrono.rs:738]: Since the particular value of the timestamp should not matter, this looks like a good candidate for a proptest by interpolate the timestamp and the offset into the Python code?

File: src/conversions/chrono.rs (hunk 1 above)
Comment (grantslatton) [reply src/conversions/chrono.rs:742]: If you structure the code with `eval`, how do you get the import? Maybe I am misunderstanding

Comment (adamreichold) [reply src/conversions/chrono.rs]: A useful trick is to use `__import__` as for example [here](https://github.com/PyO3/rust-numpy/blob/08510a3aa31a09c45df4602c484ac81056f0c4e8/src/array.rs#L742).

**Comment by adamreichold** [comment]
Since we are going through a license change, please also have a loot at #3108

File: src/conversions/chrono.rs (hunk 2 above)
Comment (adamreichold) [reply src/conversions/chrono.rs]: Wouldn't it make sense to make the timezone offset variable for the proptest as well?

File: src/conversions/chrono.rs (hunk 1 above)
Comment (grantslatton) [reply src/conversions/chrono.rs]: I think you'll wind up with an expression that looks like

```
let code = format!("__import('datetime').datetime.fromtimestamp({timestamp}).replace(tzinfo=__import('datetime').timezone(__import('datetime').timedelta(hours=-8)))");
```

Note the 3 uses of `__import__` to make this work, IMO the `run` solution is more readable

Comment (adamreichold) [reply src/conversions/chrono.rs]: How about

```rust
let globals = [("datetime", py.import("datetime").unwrap())].into_py_dict(py);
let t = py.eval(format!("datetime.datetime.fromtimestamp({timestamp}).replace(tzinfo=datetime.timezone(datetime.timedelta(hours={hours})))"), Some(globals), None).unwrap();
```

then?

Comment (adamreichold) [reply src/conversions/chrono.rs]: (Also note that you cannot use inline format literals due to our MSRV.)

**Comment by adamreichold** [comment]
Not sure what the Windows build failures are about. Is the Python installation missing the time zone database there?

**Comment by grantslatton** [comment]
> Not sure what the Windows build failures are about. Is the Python installation missing the time zone database there?

It's because Windows only supports times in 1970-2038 I believe, but the proptest is using a much larger range, I am fixing this now

**Comment by grantslatton** [comment]
Hunting down some more bugs the more exhaustive proptest found. Found one in chrono: https://github.com/chronotope/chrono/issues/1154

There is another one that results in the python vs rust datetimes being 1 second off when the time falls exactly on the daylight savings switchover. Unsure if pyo3 conversion bug (with the `fold` parameter) or just a discrepancy between python and chrono. Investigating further...

**Comment by pitdicker** [comment]
@grantslatton I am interested in the issues you may run into.

**Comment by grantslatton** [comment]
> @grantslatton I am interested in the issues you may run into.

Does chrono have facilities for supporting ambiguous instants created at the end of daylight savings? i.e. https://peps.python.org/pep-0495/

File: .vscode/settings.json [hunk 3]
```diff
@@ -0,0 +1,6 @@
+{
```
Comment (adamreichold) [inline .vscode/settings.json:1]: This is IDE-specific and does not belong into version control. Please also squash your commits as we generally aim for a helpful commit history and do not squash automatically.

File: proptest-regressions/conversions/chrono.txt [hunk 4]
```diff
@@ -0,0 +1,9 @@
+# Seeds for failure cases proptest has generated in the past. It is
```
Comment (adamreichold) [inline proptest-regressions/conversions/chrono.txt:1]: I would like to avoid checking this in for now as well. AFAIK this file is also not stable w.r.t. dependency and toolchain updates and we have no procedure for managing it.

**Comment by grantslatton** [comment]
I am wondering if we should also fix https://github.com/PyO3/pyo3/issues/3266 in the same change, because this change will result in `fold` information being lost on `FromPyObject`, because PyO3's doesn't have a conversion out to `DateTime<Tz>` -- only `DateTime<Utc>` and `DateTime<FixedOffset`. 

But doing this would require changing the `IntoPy for DateTime<Tz: TimeZone>` path to different impls: one for `DateTime<Utc>`, `DateTime<FixedOffset>`, `DateTime<Local>`, and `DateTime<Tz>`. This would be a breaking change that would break any downstream code that has defined their own custom `TimeZone` impl. There is probably no such code, as everyone is probably using timezones defined by `chrono` and `chrono_tz`.

I think such a change increases the correctness of this crate, because right now the conversion is lossy and loses daylight savings information present in `chrono_tz::Tz` locale timezones.

**Comment by adamreichold** [comment]
> This would be a breaking change that would break any downstream code that has defined their own custom TimeZone impl. There is probably no such code, as everyone is probably using timezones defined by chrono and chrono_tz.

This would mean the fix would also be limited to 0.20, the next release where breakage is possible. So I think the question is whether the side effects of losing the fold information is serious enough that one would say the backwards-compatible version of the fix cannot be used anyway?

Personally, I would be fine with try to fix this properly for 0.20 only because the chrono integration is still a relatively new feature of PyO3 and some churn seems expected.

**Comment by adamreichold** [comment]
P.S.: You seem to have included two unrelated commits during your rebase.

**Comment by Psykopear** [comment]
Ok, sorry for the delay. I've reviewed the issue and the PR, the bug is there, and this fixes it, nice catch.

> I am wondering if we should also fix https://github.com/PyO3/pyo3/issues/3266 in the same change, because this change will result in fold information being lost on FromPyObject, because PyO3's doesn't have a conversion out to DateTime\<Tz> -- only DateTime\<Utc> and DateTime\<FixedOffset>.

The problem with the `chrono_tz` integration IIRC, is that python<3.9 doesn't have the `zoneinfo` package in the standard library, and I'm not sure it's reasonable to implement the integration without that. So, unless there is an alternative solution I missed (that doesn't require adding a python dependency like [backports.zoneinfo](https://pypi.org/project/backports.zoneinfo/) and/or tzdata), we'd probably need to put the `chrono_tz` integration under a separate feature (dependent on python>=3.9), and keep only the `chrono` one for python<3.9. The two features would also have to be mutually exclusive I think, because we can't implement the python traits for both `chrono::Tz` (the trait) and `chrono_tz::Tz` (the enum).

All that to say that it's probably ok to lose the `fold` info with just `chrono` (since we only handle fixedoffsets), and fix this for python>=3.9 in the `chrono_tz` integration.
Gating the new integration under a separate feature will also avoid breaking code that uses the current one, because you'd need to enable the `chrono_tz` feature.

**Review by adamreichold — APPROVED** [review]
@grantslatton @Psykopear Ok, you to summarize my understanding: We take as it is and it fixes #3267 but #3266 will need a more involved approach which might even use an independent code path. Do you both agree with this?

**Comment by grantslatton** [comment]
> @grantslatton @Psykopear Ok, you to summarize my understanding: We take as it is and it fixes #3267 but #3266 will need a more involved approach which might even use an independent code path. Do you both agree with this?

Yes this is right
