### PR TITLE
Collecting multiple attribute error

### LINKED ISSUE #2892: Reporting multiple errors from proc-macros
At the moment our proc-macros are implemented such that they return on the first error they encounter.

I think in some cases it should be possible to collect multiple errors together so that all of these could be reported to the user. For example, the following code:

```rust
use pyo3::prelude::*;

#[pyclass]
struct Example {
    #[pyo3(foo)]
    x: i32,
    #[pyo3(blah)]
    y: i32,
}
```

will at time of writing report compilation errors like the following:

```
error: expected one of: `get`, `set`, `name`
 --> src/lib.rs:5:12
  |
5 |     #[pyo3(foo)]
  |            ^^^


error: cannot find attribute `pyo3` in this scope
 --> src/lib.rs:7:7
  |
7 |     #[pyo3(blah)]
  |       ^^^^
  |
  = note: `pyo3` is in scope, but it is a crate, not an attribute
```

This is because as soon as the error on "foo" occurs, the macro stops parsing and so the `#[pyo3(blah)]` attribute is never consumed.

A better pair of error messages could be the following:

```
error: expected one of: `get`, `set`, `name`
 --> src/lib.rs:5:12
  |
5 |     #[pyo3(foo)]
  |            ^^^


error: expected one of: `get`, `set`, `name`
 --> src/lib.rs:7:7
  |
7 |     #[pyo3(blah)]
  |       ^^^^
```

I think I'm unlikely to work on this any time soon myself, but it would be a nice UX improvement if anyone is interested in getting dirty with our proc-macros 😄

### PR DESCRIPTION
**Pull request by Cheukting**
~~Attempt to clos e #2892~~ (Edit by @davidhewitt - I think there's more we can do with `#[pymethods]` probably, though might be a fair bit more work.)

I am not sure how to add the test in CI but I have tested manually with the following:

```
use pyo3::prelude::*;

#[pyclass]
struct Example {
    #[pyo3(foo)]
    #[pyo3(blah)]
    x: i32,
    #[pyo3(pop)]
    y: i32,
}
```

Originally it gave:
```
error: expected one of: `get`, `set`, `name`
 --> pytests/src/pyclasses.rs:7:12
  |
7 |     #[pyo3(foo)]
  |            ^^^

error: cannot find attribute `pyo3` in this scope
  --> pytests/src/pyclasses.rs:10:7
   |
10 |     #[pyo3(pop)]
   |       ^^^^
   |
   = note: `pyo3` is in scope, but it is a crate, not an attribute

error: could not compile `pyo3-pytests` (lib) due to 2 previous errors
```

Now it gives:
```
error: expected one of: `get`, `set`, `name`
 --> pytests/src/pyclasses.rs:7:12
  |
7 |     #[pyo3(foo)]
  |            ^^^

error: expected one of: `get`, `set`, `name`
 --> pytests/src/pyclasses.rs:8:12
  |
8 |     #[pyo3(blah)]
  |            ^^^^

error: expected one of: `get`, `set`, `name`
  --> pytests/src/pyclasses.rs:10:12
   |
10 |     #[pyo3(pop)]
   |            ^^^

error: could not compile `pyo3-pytests` (lib) due to 3 previous errors
```

### CODE REVIEW

File: pyo3-macros-backend/src/attributes.rs [hunk 1]
```diff
@@ -233,13 +233,28 @@ pub fn take_attributes(
...
-    Ok(out)
+    if !allerr.is_empty() {
+        let mut error = allerr[0].clone();
+        for err in &allerr[1..] {
+            error.combine(err.clone());
+        }
+        Err(error)
+    } else {
+        Ok(out)
+    }
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/attributes.rs:259]: Ah, this `error.combine()` function is extremely handy!

I think now that we know about this, to avoid the `allerr` vec we can probably have something like this:

```rust
struct ErrorCombiner(Option<syn::Error>);

impl ErrorCombiner {
    fn combine(&mut self, error: syn::Error) {
        if let Some(existing) = &mut self.0 {
            existing.combine(error);
        } else {
            self.0 = Some(error);
        }
    }

    fn ensure_empty(self) -> Result<()> {
        if let Some(error) = self.0 {
            Err(error)
        } else {
            None
        }
}
```

Above, instead of extending the `Vec` we would combine the error immediately, and then at the end of the function we could just check the combiner is empty:

```suggestion
    error_combiner.ensure_empty()?;
    Ok(out)
```

I think this pattern would be useful in a lot of places in the macro code!

**Review by davidhewitt — COMMENTED** [review]
Thanks, this looks like a great discovery!

To test this, we should update the UI tests to make use of these attributes. For example, see `tests/ui/invalid_pyclass_args.rs`.

At the moment it has a separate class for each invalid entry. We could instead write pieces which can be combined together, for example:

```rust
#[pyclass(
    extend = pyo3::types::PyDict,  // typo in the key
    extends = "PyDict", // Needs to be an ident, not a string
)]
struct InvalidExtends;
```

... and so on.

See also `invalid_pymethods.rs` - we have loads of `#[pymethods] impl MyClass` blocks, and we should be able to combine them all into one with this functionality!

**Comment by Cheukting** [comment]
Thanks for the suggestions @davidhewitt i have added the test and have refactored as suggested.

File: tests/ui/invalid_pyclass_args.rs [hunk 2]
```diff
@@ -76,4 +76,13 @@ struct InvalidOrderedStruct {
...
 }
 
+#[pyclass]
+struct Example {
+    #[pyo3(foo)]
+    #[pyo3(blah)]
+    x: i32,
+    #[pyo3(pop)]
+    y: i32,
+}
```
Comment (davidhewitt) [inline tests/ui/invalid_pyclass_args.rs:86]: Let's call this something more descriptive:

```suggestion
#[pyclass]
struct MultipleErrors {
    #[pyo3(foo)]
    #[pyo3(blah)]
    x: i32,
    #[pyo3(pop)]
    y: i32,
}
```

File: pyo3-macros-backend/src/attributes.rs [hunk 3]
```diff
@@ -233,13 +233,41 @@ pub fn take_attributes(
 
 pub fn take_pyo3_options<T: Parse>(attrs: &mut Vec<syn::Attribute>) -> Result<Vec<T>> {
     let mut out = Vec::new();
-    take_attributes(attrs, |attr| {
-        if let Some(options) = get_pyo3_options(attr)? {
-            out.extend(options);
+    let mut all_error = ErrorCombiner(None);
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/attributes.rs:236]: Personally I prefer a plural name:

```suggestion
    let mut all_errors = ErrorCombiner(None);
```

File: pyo3-macros-backend/src/pyclass.rs [hunk 4]
```diff
@@ -230,34 +230,52 @@ pub fn build_py_class(
...
+    let mut field_options: Vec<(&syn::Field, FieldPyO3Options)> = field_options_res
+        .drain(..)
+        .filter_map(|result| match result {
+            Err(err) => {
+                all_error.combine(err);
+                None
+            }
+            Ok(options) => Some(options),
+        })
+        .collect::<Vec<_>>();
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/pyclass.rs:276]: I think we should now be able to simplify here and go back to something more like the original implementation and drop the need for the intermediate `field_options_res`.

I think the idea would be to set up `all_errors` before the `match &mut class.fields`. And then instead of collecting into vec-of-results I think it would be possible to swap the `.map` for `.filter_map`.

Something like

```rust
                .filter_map(|field| {
                    match FieldPyO3Options::take_pyo3_options(&mut field.attrs) {
                        Ok(options) => Some((&*field, options)),
                        Err(e) => {
                            all_errors.combine(e);
                            None
                        }
                    }                    
                })
```

**Review by davidhewitt — COMMENTED** [review]
Thanks, I love these kinds of UX improvements! Just a couple of thoughts related to the implementation still.

(And sorry it took me a few days here, was focussing on #4266 for a while.)

**Comment by Cheukting** [comment]
Thank you for your patience. I was busy with EuroPython. I plan to finish this PR this weekend or next week.

**Review by davidhewitt — APPROVED** [review]
Thanks, I'm excited to merge this and hope I can find some time to also play with `ErrorCombiner` in more places across the codebase :)

**Comment by davidhewitt** [comment]
(I took the liberty to fix the new merge conflicts.)

**Comment by Cheukting** [comment]
Thank you @davidhewitt
