### PR TITLE
Use linked list in ReleasePool

### LINKED ISSUE #271: Reference to ReleasePool can be broken
Please see https://github.com/PyO3/pyo3/issues/159#issuecomment-437898689 for detail.
Currently, `register_owned/borrowed/pointer` methods returns a reference to an element in `Vec`, like
```rust
pub unsafe fn register_owned(_py: Python, obj: *mut ffi::PyObject) -> &PyObjectRef {
    let pool: &'static mut ReleasePool = &mut *POOL;
    pool.owned.push(obj);
    &*(&pool.owned[pool.owned.len() - 1] as *const *mut ffi::PyObject as *const PyObjectRef)
}
```
.
But, since `Vec`'s inner address can be changed by `realloc`, this reference can be invalid one, and causes segfault like #158.
There can be some solutions for this.
## 1. Wrap by box
Current definition of release pool
```rust
struct ReleasePool {
    owned: Vec<*mut ffi::PyObject>,
    borrowed: Vec<*mut ffi::PyObject>,
    pointers: *mut Vec<*mut ffi::PyObject>,
    obj: Vec<Box<any::Any>>,
    p: spin::Mutex<*mut Vec<*mut ffi::PyObject>>,
}
```
to 
```rust
struct ReleasePool {
    owned: Vec<PinBox<*mut ffi::PyObject>>,
    borrowed: Vec<PinBox<*mut ffi::PyObject>>,
    pointers: *mut Vec<PinBox<*mut ffi::PyObject>>,
    obj: Vec<PinBox<any::Any>>,
    p: spin::Mutex<*mut Vec<*mut ffi::PyObject>>,
}
```
so that each objects have a consistent address.
Then we can get a consistent reference by
```rust
&*(&*pool.owned[pool.owned.len() - 1] as *const *mut ffi::PyObject as *const PyObjectRef)
```

### advantage
Easy

### disadvantage
Allocation overhead

## 2. Remove ReleasePool
Remove release pool and rewrite all PyObject wrapper like `PyDict` and `PyList` to have a lifetime`'py`.
E.g.
```rust
#[repr(transparent)]
pub struct PyDict<'py>(PyObject, Python<'py>);
```
And also rewrite all constructors  to return owned type instead of returning `&'py`.
E.g.
```rust
impl<'py> PyDict<'py> {
    /// Creates a new empty dictionary.
    pub fn new(py: Python<'py>) -> PyDict<'py> {
        unsafe {
            let obj = crate::PyObject::from_owned_ptr(py, ffi::PyDict_New());
            PyDict(obj, py)
        }
    }
}
```

### advantages
Ergonomics improves
No overhead
### disadvantage
Really big breaking change

### PR DESCRIPTION
**Pull request by kngwyu**
Fix #271 
I haven't benched yet and maybe `LinkedList<[NonNull<_>; 256]` or so is more efficient

### CODE REVIEW

**Comment by kngwyu** [comment]
The 1st commit is naive `LinkedList<NonNull<PyObject>>` implementation.
The 2nd commit is `LinkedList<[NonNull<PyObject>; 256]>` implementation.
I'll note a bench for both two.

File: src/pythonrun.rs [hunk 1]
```diff
@@ -118,49 +118,40 @@ struct ReleasePool {
...
-        *v = self.pointers;
-        self.pointers = ptr;
+        std::mem::swap(&mut self.pointers, &mut *v);
         drop(v);
 
-        // release py objects
-        for ptr in vec.iter_mut() {
+        // release PyObjects
+        for ptr in vec.iter() {
             ffi::Py_DECREF(ptr.as_ptr());
```
Comment (konstin) [inline src/pythonrun.rs]: Filed #282 because this is lurking UB

**Comment by kngwyu** [comment]
@konstin 
Benchmark result:
[T; 256]
```
running 1 test
test iter_dict ... bench:   2,222,297 ns/iter (+/- 69,061)
```
Vec<T> built by `Vec::with_capacity(256)`
```
running 1 test
test iter_dict ... bench:   2,591,632 ns/iter (+/- 166,590)
```

**Comment by konstin** [comment]
Thanks for measuring, we now have a good rationale for keeping `mem::uninitialized()`.
