### PR TITLE
fix compile error for multiple async method arguments

### LINKED ISSUE #4034: Unable to use async functions with multiple arguments in #[pymethods]
### Bug Description

Error occurs when trying to use multiple arguments in an async function within `#[pymethods]`. However, it works as expected if using `#[staticmethod]` without `&self`.

### Steps to Reproduce

```
// works
#[pyclass]
struct Test;

#[pymethods]
impl Test {
    #[staticmethod]
    async fn test(a: i32, b: i32) -> i32 {
        a + b
    }
}

// fails
#[pyclass]
struct Test;

#[pymethods]
impl Test {
    async fn test(&self, a: i32, b: i32) -> i32 {
        a + b
    }
}
```

### Backtrace

```shell
error: expected one of `.`, `;`, `?`, `else`, or an operator, found keyword `let`
 --> src\lib.rs:6:1
  |
6 | #[pymethods]
  | ^^^^^^^^^^^^ expected one of `.`, `;`, `?`, `else`, or an operator
  |
  = note: this error originates in the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Your operating system and version

Windows 11

### Your Python version (`python --version`)

Python 3.10.11

### Your Rust version (`rustc --version`)

rustc 1.77.1 (7cf61ebde 2024-03-27)

### Your PyO3 version

0.21.1

### How did you install python? Did you use a virtualenv?

--

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by davidhewitt**
fixes #4034

I missed in review that the `;` was only being applied once at the end of the `#evaluate_arg` expansion. 

While at it I tidied this implementation up a bit further. I probably should have reviewed #4015 better; it's been a long week 🤦

### CODE REVIEW

File: tests/test_coroutine.rs [hunk 1]
```diff
@@ -245,39 +245,6 @@ fn coroutine_panic() {
     })
 }
 
-#[test]
-fn test_async_method_receiver_with_other_args() {
```
Comment (davidhewitt) [inline tests/test_coroutine.rs:249]: Moved the test down as the ordering in the file made more sense to me the other way around.

**Review by Icxolu — APPROVED** [review]

**Comment by davidhewitt** [comment]
Not a problem at all. I've made the same mistake before with separators and really should have noticed it in review!
