### PR TITLE
Fix installing in 'venv' and datetime tests on Windows

### LINKED ISSUE #468: Error during building in virtualenv on Windows
## 🐛 Bug Reports
I've failed to build [example from *README*](https://github.com/PyO3/pyo3#using-rust-from-python) using virtualenv on Windows.

### 🌍 Environment

- Your operating system and version: Windows 10 Pro 10.0.17134 Build 17134
- Your python version: Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
- How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Using [executable](https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe), yes, I am using virtualenv.
- Your rust version (`rustc --version`): rustc 1.36.0-nightly (597f43248 2019-04-26)
- Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: yes, I've tried on both.

### 💥 Reproducing

Contents of `setup.py`:
```python
from setuptools import setup
from setuptools_rust import Binding, RustExtension

setup(name='testrust',
      version='0.0.1',
      rust_extensions=[RustExtension('string_sum', 'Cargo.toml',
                                     binding=Binding.PyO3)],
      test_suite='tests',
      zip_safe=False)
```

Install virtualenv
```bat
> python -m venv venv
```
Activate virtualenv
```bat
> venv\Scripts\activate.bat
```
Build project
```bat
(venv) > python setup.py build
```
and get an error
```bat
running build
running build_ext
running build_rust
cargo rustc --lib --manifest-path Cargo.toml --features pyo3/python3 pyo3/extension-module --release --verbose -- --crate-type cdylib
       Fresh unicode-xid v0.1.0
       Fresh lazy_static v1.3.0
       Fresh ucd-util v0.1.3
       Fresh proc-macro-hack-impl v0.4.1
       Fresh utf8-ranges v1.0.2
       Fresh version_check v0.1.5
       Fresh doc-comment v0.3.0
       Fresh spin v0.5.0
       Fresh regex-syntax v0.6.6
       Fresh thread_local v0.3.6
       Fresh proc-macro-hack v0.4.1
       Fresh memchr v2.2.0
       Fresh proc-macro2 v0.4.28
       Fresh quote v0.6.12
       Fresh aho-corasick v0.7.3
       Fresh mashup-impl v0.1.9
       Fresh libc v0.2.53
       Fresh num-traits v0.2.6
       Fresh syn v0.15.33
       Fresh regex v1.1.6
       Fresh inventory-impl v0.1.3
       Fresh ctor v0.1.9
       Fresh ghost v0.1.0
       Fresh pyo3-derive-backend v0.7.0-alpha.1 (https://github.com/PyO3/pyo3#8399916e)
       Fresh mashup v0.1.9
       Fresh pyo3cls v0.7.0-alpha.1 (https://github.com/PyO3/pyo3#8399916e)
       Fresh inventory v0.1.3
       Fresh pyo3 v0.7.0-alpha.1 (https://github.com/PyO3/pyo3#8399916e)
   Compiling testrust v0.1.0 (C:\Users\azati\CLionProjects\testrust)
     Running `rustc --edition=2018 --crate-name string_sum src\lib.rs --color always --crate-type cdylib --emit=dep-info,link -C opt-level=3 --crate-type cdylib --cfg "featu
re=\"pyo3\"" -C metadata=44d6093e6dc62267 --out-dir C:\Users\azati\CLionProjects\testrust\target\release\deps -L dependency=C:\Users\azati\CLionProjects\testrust\target\rele
ase\deps --extern pyo3=C:\Users\azati\CLionProjects\testrust\target\release\deps\libpyo3-55a5e493979761a3.rlib -L native=C:\Users\azati\CLionProjects\testrust\venv\libs`
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\
\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\d
eps\\string_sum.string_sum.8by8a1ry-cgu.0.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.1.rcgu.o" "C:\\Users\
\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.10.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\stri
ng_sum.string_sum.8by8a1ry-cgu.11.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.12.rcgu.o" "C:\\Users\\azati\
\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.13.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.
string_sum.8by8a1ry-cgu.14.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.15.rcgu.o" "C:\\Users\\azati\\CLionP
rojects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.2.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_s
um.8by8a1ry-cgu.3.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.4.rcgu.o" "C:\\Users\\azati\\CLionProjects\\t
estrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.5.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1r
y-cgu.6.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.7.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\t
arget\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.8.rcgu.o" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.string_sum.8by8a1ry-cgu.9.rc
gu.o" "/OUT:C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.dll" "/DEF:C:\\Users\\azati\\AppData\\Local\\Temp\\rustcRi1C3v\\lib.def" "C:\\Users\
\azati\\CLionProjects\\testrust\\target\\release\\deps\\string_sum.1p67c0k2rnpbavvn.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\azati\\.rustup\\toolchains\\nightly-x
86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvi
s" "/NATVIS:C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\azati\\CLionProjects\\testrust\\ta
rget\\release\\deps" "/LIBPATH:C:\\Users\\azati\\CLionProjects\\testrust\\venv\\libs" "/LIBPATH:C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\r
ustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\libpyo3-55a5e493979761a3.rlib" "C:\\Users\\azati\\CLionProjects\\test
rust\\target\\release\\deps\\libnum_traits-8b286df90cdcc751.rlib" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\libspin-066fde1b466eb1aa.rlib" "C:\\User
s\\azati\\CLionProjects\\testrust\\target\\release\\deps\\liblibc-0bec6cd7264d8549.rlib" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\libinventory-be43
b72b996f9f38.rlib" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\libmashup-24ea472bcf4918e8.rlib" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\re
lease\\deps\\libproc_macro_hack-f3a1021acb922f97.rlib" "C:\\Users\\azati\\CLionProjects\\testrust\\target\\release\\deps\\libdoc_comment-10da6fe1fb218b7d.rlib" "C:\\Users\\a
zati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-382dd3d01e0cc852.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\n
ightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-fcd87a43cbc6f7f8.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-wi
ndows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-521a49668a980bb7.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\
rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-9eab307b7f82c3f0.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-win
dows-msvc\\lib\\librustc_std_workspace_alloc-a1570f4ad99fcee0.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-m
svc\\lib\\libunwind-ca8937bf32f9c9b8.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-967944a
14a0a0aae.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-e6c9f758f0aa026f.rlib" "C:\\Users
\\azati\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-8e59df0e2cb2e44a.rlib" "C:\\Users\\azati
\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-dba92194f1a14aaa.rlib" "C:\\Users\\azati\\.rustup\\toolchains\\nigh
tly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-e86690cfb6b393a1.rlib" "python35.lib" "python35.lib" "python35.lib" "python35.lib
" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "pytho
n35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib"
 "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python
35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib"
"python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python3
5.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "
python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35
.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "python35.lib" "p
ython35.lib" "python35.lib" "python35.lib" "python35.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib" "/DLL" "/IMPLIB:C:\\Users\\azati\\CLionProjects\\testrust\\t
arget\\release\\deps\\string_sum.dll.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'python35.lib'


error: aborting due to previous error

error: Could not compile `testrust`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name string_sum src\lib.rs --color always --crate-type cdylib --emit=dep-info,link -C opt-level=3 --crate-t
ype cdylib --cfg "feature=\"pyo3\"" -C metadata=44d6093e6dc62267 --out-dir C:\Users\azati\CLionProjects\testrust\target\release\deps -L dependency=C:\Users\azati\CLionProjec
ts\testrust\target\release\deps --extern pyo3=C:\Users\azati\CLionProjects\testrust\target\release\deps\libpyo3-55a5e493979761a3.rlib -L native=C:\Users\azati\CLionProjects\
testrust\venv\libs` (exit code: 1)
error: cargo failed with code: 101
```

When I build outside of virtualenv it works fine
```bat
(venv) > deactivate
> python setup.py build
running build
running build_ext
running build_rust
cargo rustc --lib --manifest-path Cargo.toml --features pyo3/extension-module pyo3/python3 --release --verbose -- --crate-type cdylib
       Fresh unicode-xid v0.1.0
       Fresh ucd-util v0.1.3
       Fresh lazy_static v1.3.0
       Fresh proc-macro-hack-impl v0.4.1
       Fresh utf8-ranges v1.0.2
       Fresh version_check v0.1.5
       Fresh doc-comment v0.3.0
       Fresh spin v0.5.0
       Fresh thread_local v0.3.6
       Fresh regex-syntax v0.6.6
       Fresh proc-macro-hack v0.4.1
       Fresh proc-macro2 v0.4.28
       Fresh memchr v2.2.0
       Fresh quote v0.6.12
       Fresh aho-corasick v0.7.3
       Fresh mashup-impl v0.1.9
       Fresh libc v0.2.53
       Fresh num-traits v0.2.6
       Fresh syn v0.15.33
       Fresh regex v1.1.6
       Fresh ghost v0.1.0
       Fresh ctor v0.1.9
       Fresh pyo3-derive-backend v0.7.0-alpha.1 (https://github.com/PyO3/pyo3#8399916e)
       Fresh inventory-impl v0.1.3
       Fresh mashup v0.1.9
   Compiling pyo3 v0.7.0-alpha.1 (https://github.com/PyO3/pyo3#8399916e)
       Fresh inventory v0.1.3
       Fresh pyo3cls v0.7.0-alpha.1 (https://github.com/PyO3/pyo3#8399916e)
     Running `C:\Users\azati\CLionProjects\testrust\target\release\build\pyo3-c914dd4a19b8944a\build-script-build`
     Running `rustc --edition=2018 --crate-name pyo3 C:\Users\azati\.cargo\git\checkouts\pyo3-a22e69bc62b9f0fd\8399916\src\lib.rs --color always --crate-type lib --emit=dep-
info,link -C opt-level=3 --cfg "feature=\"default\"" --cfg "feature=\"extension-module\"" --cfg "feature=\"python3\"" -C metadata=55a5e493979761a3 -C extra-filename=-55a5e49
3979761a3 --out-dir C:\Users\azati\CLionProjects\testrust\target\release\deps -L dependency=C:\Users\azati\CLionProjects\testrust\target\release\deps --extern doc_comment=C:
\Users\azati\CLionProjects\testrust\target\release\deps\libdoc_comment-10da6fe1fb218b7d.rlib --extern inventory=C:\Users\azati\CLionProjects\testrust\target\release\deps\lib
inventory-be43b72b996f9f38.rlib --extern libc=C:\Users\azati\CLionProjects\testrust\target\release\deps\liblibc-0bec6cd7264d8549.rlib --extern mashup=C:\Users\azati\CLionPro
jects\testrust\target\release\deps\libmashup-24ea472bcf4918e8.rlib --extern num_traits=C:\Users\azati\CLionProjects\testrust\target\release\deps\libnum_traits-8b286df90cdcc7
51.rlib --extern pyo3cls=C:\Users\azati\CLionProjects\testrust\target\release\deps\pyo3cls-c48fbe503c44cd08.dll --extern spin=C:\Users\azati\CLionProjects\testrust\target\re
lease\deps\libspin-066fde1b466eb1aa.rlib --cap-lints allow -L native=C:\Python35\libs --cfg Py_3_5 --cfg Py_3 --cfg "py_sys_config=\"Py_USING_UNICODE\"" --cfg "py_sys_config
=\"Py_UNICODE_SIZE_2\"" --cfg "py_sys_config=\"WITH_THREAD\"" -l pythonXY:python35`
   Compiling testrust v0.1.0 (C:\Users\azati\CLionProjects\testrust)
     Running `rustc --edition=2018 --crate-name string_sum src\lib.rs --color always --crate-type cdylib --emit=dep-info,link -C opt-level=3 --crate-type cdylib --cfg "featu
re=\"pyo3\"" -C metadata=44d6093e6dc62267 --out-dir C:\Users\azati\CLionProjects\testrust\target\release\deps -L dependency=C:\Users\azati\CLionProjects\testrust\target\rele
ase\deps --extern pyo3=C:\Users\azati\CLionProjects\testrust\target\release\deps\libpyo3-55a5e493979761a3.rlib -L native=C:\Python35\libs`
    Finished release [optimized] target(s) in 8.41s
```

The problem seems to be with `native` option being equal to `C:\Users\azati\CLionProjects\testrust\venv\libs` inside virtualenv and `C:\Python35\libs` outside of it, I've tried to find out where this option is generated (looking for `sys.prefix`/`sys.exec_prefix`/`sys.executable` which are virtualenv dependent) and found [this line](https://github.com/PyO3/pyo3/blob/master/build.rs#L506), tried to change its value locally to [`sys.base_prefix`](https://docs.python.org/3/library/sys.html#sys.base_prefix), clear cache (by removing *target* directory), rebuild and it worked both inside and outside of virtualenv.

### PR DESCRIPTION
**Pull request by lycantropos**
Resolves #468.

- [x] Run `cargo fmt` (This is checked by travis ci).
- [x] Run `cargo clippy` and check there are no hard errors (There are a bunch of existing warnings; This is also checked by travis).
- [x] If applicable, add an entry in the changelog.
- [x] If applicable, add documentation to all new items and extend the guide.
- [x] If applicable, add tests for all new or fixed functions

### CODE REVIEW

File: tests/test_venv.rs [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+    fn is_example_built_using_venv(venv_name: &str, example_name: &str) -> bool {
+        if cfg!(target_os = "windows") {
+            Command::new("cmd")
+                .args(&[
+                    "/C",
+                    format!(
+                        "{0}\\Scripts\\activate.bat && \
+                         cd examples\\{1} && \
+                         python -m pip install --upgrade setuptools-rust && \
```
Comment (lycantropos) [inline tests/test_venv.rs]: without pre-installing `setuptools-rust` package command
```cmd
python setup.py build
```
fails with
```cmd
running build_ext
running build_rust
error: invalid command 'build_rust'
```
so it should be installed before

Comment (pganssle) [reply tests/test_venv.rs]: @lycantropos Actually you should not invoke `setup.py` directly, instead use `pip install` with a `pyproject.toml`. The `word-count` and `rustapi_modules` examples are built with PEP 517, and installing or building them by invoking `setup.py` probably works even worse than it would in a normal project.

Comment (lycantropos) [reply tests/test_venv.rs]:
```cmd
(venv) > python -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\users\azati\clionprojects\pyo3\venv\lib\site-packages (19.1)
(venv) > python -m pip install .
```
gives
```cmd
> python -m pip install .
Processing c:\users\azati\clionprojects\pyo3\examples\word-count
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: word-count
  Building wheel for word-count (PEP 517) ... error
  ERROR: Complete output from command 'C:\Users\azati\CLionProjects\pyo3\venv\Scripts\python.exe' 'C:\Users\azati\CLionProjects\pyo3\venv\lib\site-packages\pip\_vendor\pep51
7\_in_process.py' build_wheel 'C:\Users\azati\AppData\Local\Temp\tmp1rcvfwh_':
  ERROR: running bdist_wheel
  running build
  running build_py
  running egg_info
  writing word_count.egg-info\PKG-INFO
  writing top-level names to word_count.egg-info\top_level.txt
  writing dependency_links to word_count.egg-info\dependency_links.txt
  reading manifest file 'word_count.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'word_count.egg-info\SOURCES.txt'
  running build_ext
  running build_rust
  error: failed to load source for a dependency on `pyo3`

  Caused by:
    Unable to update C:\Users\azati\AppData\Local

  Caused by:
    failed to read `C:\Users\azati\AppData\Local\Cargo.toml`

  Caused by:
    The system cannot find the file specified. (os error 2)
  Traceback (most recent call last):
    File "C:\Users\azati\CLionProjects\pyo3\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "C:\Users\azati\CLionProjects\pyo3\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\azati\CLionProjects\pyo3\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 141, in build_wheel
      metadata_directory)
    File "C:\Users\azati\AppData\Local\Temp\pip-build-env-n1a5am83\overlay\Lib\site-packages\setuptools\build_meta.py", line 192, in build_wheel
      self.run_setup()
    File "C:\Users\azati\AppData\Local\Temp\pip-build-env-n1a5am83\overlay\Lib\site-packages\setuptools\build_meta.py", line 141, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 92, in <module>
      'sdist': CargoModifiedSdist,
    File "C:\Users\azati\AppData\Local\Temp\pip-build-env-n1a5am83\overlay\Lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Python35\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Python35\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\azati\AppData\Local\Temp\pip-build-env-n1a5am83\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Python35\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Python35\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Python35\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\azati\AppData\Local\Temp\pip-build-env-n1a5am83\overlay\Lib\site-packages\setuptools_rust\build_ext.py", line 26, in run
      build_rust.run()
    File "C:\Users\azati\AppData\Local\Temp\pip-build-env-n1a5am83\overlay\Lib\site-packages\setuptools_rust\build.py", line 313, in run
      self.build_extension(ext)
    File "C:\Users\azati\AppData\Local\Temp\pip-build-env-n1a5am83\overlay\Lib\site-packages\setuptools_rust\build.py", line 95, in build_extension
      metadata = json.loads(check_output(metadata_command).decode("utf-8"))
    File "C:\Python35\lib\subprocess.py", line 316, in check_output
      **kwargs).stdout
    File "C:\Python35\lib\subprocess.py", line 398, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101
  ----------------------------------------
  ERROR: Failed building wheel for word-count
  Running setup.py clean for word-count
Failed to build word-count
ERROR: Could not build wheels for word-count which use PEP 517 and cannot be installed directly
```
or it should be made differently?

**Comment by lycantropos** [comment]
> In addition to the issue I mentioned about `pip` or `pep517.build` vs `setup.py`, I think this is the wrong way to do this test. These are a bunch of system commands, so there's no need to write this in Rust, or to use conditional compilation here.
> 
> I think maybe start by just adding a script to the CI that you invoke on Appveyor that executes one of these builds.
> 
> I also don't see the _fix_ here, is that coming in a later commit?

There should be different script for Travis CI as well? To be sure that I'm not breaking something. If so, where to place scripts? Directly in YAML configurations?

File: tests/test_venv.rs (hunk 1 above)
Comment (lycantropos) [reply tests/test_venv.rs]: get similar output in WSL
```bash
(venv) $ python -m pip install -U pip
...
Successfully installed pip-19.1
(venv) $ python -m pip install .
Processing /home/ace/pyo3/examples/word-count
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: word-count
  Building wheel for word-count (PEP 517) ... error
  ERROR: Complete output from command /home/ace/pyo3/examples/word-count/venv/bin/python /home/ace/pyo3/examples/word-count/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp_ald7kvr:
  ERROR: running bdist_wheel
  running build
  running build_py
  running egg_info
  writing word_count.egg-info/PKG-INFO
  writing dependency_links to word_count.egg-info/dependency_links.txt
  writing top-level names to word_count.egg-info/top_level.txt
  reading manifest file 'word_count.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'word_count.egg-info/SOURCES.txt'
  running build_ext
  running build_rust
  error: failed to load source for a dependency on `pyo3`

  Caused by:
    Unable to update /

  Caused by:
    failed to read `/Cargo.toml`

  Caused by:
    No such file or directory (os error 2)
  Traceback (most recent call last):
    File "/home/ace/pyo3/examples/word-count/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/ace/pyo3/examples/word-count/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ace/pyo3/examples/word-count/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 141, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-ir8gxftr/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 192, in build_wheel
      self.run_setup()
    File "/tmp/pip-build-env-ir8gxftr/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 141, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 92, in <module>
      'sdist': CargoModifiedSdist,
    File "/tmp/pip-build-env-ir8gxftr/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-ir8gxftr/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-ir8gxftr/overlay/lib/python3.6/site-packages/setuptools_rust/build_ext.py", line 26, in run
      build_rust.run()
    File "/tmp/pip-build-env-ir8gxftr/overlay/lib/python3.6/site-packages/setuptools_rust/build.py", line 313, in run
      self.build_extension(ext)
    File "/tmp/pip-build-env-ir8gxftr/overlay/lib/python3.6/site-packages/setuptools_rust/build.py", line 95, in build_extension
      metadata = json.loads(check_output(metadata_command).decode("utf-8"))
    File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.6/subprocess.py", line 418, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
  ----------------------------------------
  ERROR: Failed building wheel for word-count
  Running setup.py clean for word-count
Failed to build word-count
ERROR: Could not build wheels for word-count which use PEP 517 and cannot be installed directly
```

**Comment by kngwyu** [comment]
> I think maybe start by just adding a script to the CI that you invoke on Appveyor that executes one of these builds.

:+1:

> There should be different script for Travis CI as well? To be sure that I'm not breaking something. If so, where to place scripts? Directly in YAML configurations?

In ci/travis/test.sh or so.

**Comment by pganssle** [comment]
@lycantropos @kngwyu I think Appveyor is the important one, but having it on Travis doesn't hurt.

I think maybe `ci/travis` is the wrong place, maybe just `ci/test_venv.sh` or something like that.

**Comment by kngwyu** [comment]
How about using `tox` to test venv?
Then we don't need to add additional scripts.

**Comment by lycantropos** [comment]
what should we do with [this kind of message](https://travis-ci.org/PyO3/pyo3/jobs/528387287#L353):
```bash
./ci/travis/test.sh: line 6: cargo: command not found
The command "./ci/travis/test.sh" exited with 127.
```
?
it seems like modifying `PATH` in *setup.sh* is not working

**Comment by lycantropos** [comment]
> How about using `tox` to test venv?
> Then we don't need to add additional scripts.

I'm not so familiar with `tox`, can you please provide an example of activating `venv` in it?

File: .travis.yml [hunk 2]
```diff
@@ -46,13 +46,14 @@ addons:
       - libiberty-dev
 
 before_install:
-  - source ./ci/travis/setup.sh
```
Comment (konstin) [inline .travis.yml]: This change is the reason for 

```
./ci/travis/test.sh: line 6: cargo: command not found
```

**Comment by konstin** [comment]
>  I'm not so familiar with tox, can you please provide an example of activating venv in it?

Not kngwyu, but anyways: The cool thing about tox is that it creates the venv itself. If the correct python version is active, you should only need to call `tox -e py` (and maybe `pip install tox` beforehand). You can easily try this out by just running `tox` on your local machine

**Comment by lycantropos** [comment]
@konstin: so in the end it will be similar to *ci/travis* directory (especially *setup.sh* & *test.sh* scripts), but for AppVeyor?

**Comment by pganssle** [comment]
> How about using tox to test venv?
> Then we don't need to add additional scripts.

I'm not entirely sure why our existing tests with `tox` were not hitting this edge case already, honestly, which is why I didn't suggest `tox` in the first place.

**Comment by kngwyu** [comment]
@pganssle 
I think now tox is not invoked in Appveyor.
Or you tested the tox works on local windows?

**Comment by pganssle** [comment]
@kngwyu Oh, I assumed the tests were run on all platforms. Can we just turn on tox for the appveyor builds and have that test this?

I have no Windows computer to test this on, so I haven't done anything local.

**Comment by kngwyu** [comment]
@pganssle 
> Can we just turn on tox for the appveyor builds and have that test this?

I tried it in #475

**Comment by pganssle** [comment]
@kngwyu Looks like that successfully reproduces the issue!

@lycantropos Sorry I didn't suggest this earlier, I genuinely thought we were already doing it! I think enabling the `tox` runs on appveyor like @kngwyu did in #475 is the best way to test your change.

I also checked with @gaborbernat, who maintains virtualenv, and his cursory checks seemed to indicate that `base_prefix` is the right thing to use, so your approach to fixing this looks good.

**Comment by lycantropos** [comment]
I've added `tox-venv` plugin to use stdlib `venv` instead of `virtualenv` because the latter seems to create full copy of Python and overriding `sys.base_prefix` as well, but didn't make a copy of *Python/libs* directory which is needed for projects to compile on Windows.
I've also added `pip` & `setuptools` in examples' requirements because it seems like they need to be upgraded manually until [this PR](https://github.com/tox-dev/tox-venv/pull/25) is merged and `test-venv` is updated.

Finally, we have errors related to `hypothesis` strategies used for [`datetime.timestamp` method](https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp) testing, which min/max limits are [platform-dependent](https://stackoverflow.com/a/50860754/5997596).

**Comment by lycantropos** [comment]
I've manually found edge-cases for `datetime.timestamp`, for Linux environment I've used *Docker* containers.

File: .travis.yml [hunk 3]
```diff
@@ -49,7 +49,7 @@ before_install:
   - source ./ci/travis/setup.sh
 
 install:
-  - pip install setuptools-rust pytest pytest-benchmark tox
+  - pip install setuptools-rust pytest pytest-benchmark tox tox-venv
 
 script:
   - ./ci/travis/test.sh
```
Comment (lycantropos) [inline .travis.yml]: if I understood correctly we can add `virtualenv` support for Linux by installing `tox-venv` and running  script as a separate step like
```yml
install:
  - pip install setuptools-rust pytest pytest-benchmark tox

script:
  - ./ci/travis/test.sh
  - pip install tox-venv
  - ./ci/travis/test.sh
```
but it will increase build time

File: ci/appveyor/setup.ps1 [hunk 4]
```diff
@@ -0,0 +1,8 @@
+$env:PATH="$env:PYTHON;$env:PYTHON\\Scripts;$env:PATH"
+
+Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.msi"
+Start-Process -FilePath "msiexec.exe" -ArgumentList "/i rust-nightly-$env:TARGET.msi INSTALLDIR=`"$((Get-Location).Path)\rust-nightly-$env:TARGET`" /quiet /qn /norestart" -Wait
+$env:PATH="$env:PATH;$((Get-Location).Path)/rust-nightly-$env:TARGET/bin"
+
+$pythonLocation = Invoke-Expression "python -c `"import sys; print(sys.base_prefix)`""
+$env:LIBPATH = "$env:LIBPATH; $( Join-Path $pythonLocation "libs" )"
```
Comment (lycantropos) [inline ci/appveyor/setup.ps1]: it is similar to this line
https://github.com/PyO3/pyo3/blob/c4c75bbf811773414d31ae9205988f47ee876399/ci/travis/setup.sh#L35

File: appveyor.yml [hunk 5]
```diff
@@ -1,25 +1,24 @@
 version: 0.2.{build}
 environment:
   TARGET: x86_64-pc-windows-msvc
+  RUST_BACKTRACE: 1
   matrix:
     - PYTHON: "C:/Python35-x64"
     - PYTHON: "C:/Python36-x64"
```
Comment (lycantropos) [inline appveyor.yml]: what about adding `x32` versions and Python37? this can be done in a separate PR though

**Comment by kngwyu** [comment]
@lycantropos 
Good catch, thanks.
But probably the fix for the datetime example should be in a separate PR.

File: appveyor.yml (hunk 5 above)
Comment (kngwyu) [reply appveyor.yml]: Yeah, I think we should add Python37 but I'm not sure we should support 32bit architecture.
And just a nit, but there's no architecture named 'x32'.
The 32bit version of 'x86-64' is called 'x86'.

Comment (lycantropos) [reply appveyor.yml]: Thanks, I'll keep it in mind.

**Comment by lycantropos** [comment]
> @lycantropos
> Good catch, thanks.
> But probably the fix for the datetime example should be in a separate PR.

I thought that there is no way of merging if tests fail. Also I do not know what is left to do or I can add entry to changelog and we are done?

File: examples/word-count/pyproject.toml [hunk 6]
```diff
@@ -1,3 +1,3 @@
 [build-system]
-requires = ["setuptools", "wheel", "setuptools-rust", "toml"]
+requires = ["setuptools>=41.0.0", "pip>=19.1", "wheel", "setuptools_rust>=0.10.2", "toml"]
```
[the remark this answers is not in the document]
Comment (pganssle) [reply examples/word-count/pyproject.toml]: That doesn't make sense to me, `pip` is invoked *before* this file is read. I don't think it will have any effect on the build.

File: examples/word-count/requirements-dev.txt [hunk 7]
```diff
@@ -1,3 +1,5 @@
+setuptools>=41.0.0
+pip>=19.1
```
[the remark this answers is not in the document]
Comment (pganssle) [reply examples/word-count/requirements-dev.txt]: I think you may need `pip>=19.1` here, but not `setuptools`, which will not be used.

[the remark this answers is not in the document]
Comment (lycantropos) [reply examples/word-count/requirements-dev.txt]: you are right, completed dependencies

File: examples/rustapi_module/requirements-dev.txt [hunk 8]
```diff
@@ -1,3 +1,5 @@
+setuptools>=41.0.0
+pip>=19.1
```
[the remark this answers is not in the document]
Comment (lycantropos) [reply examples/rustapi_module/requirements-dev.txt]: left `pip`, it fails to build without it

**Comment by kngwyu** [comment]
I changed the title instead of separating the PR

File: build.rs [hunk 9]
```diff
@@ -534,7 +534,7 @@ fn configure(interpreter_version: &PythonVersion, lines: Vec<String>) -> Result<
     let libpath: &str = &lines[1];
     let enable_shared: &str = &lines[2];
     let ld_version: &str = &lines[3];
-    let exec_prefix: &str = &lines[4];
+    let base_prefix: &str = &lines[4];
```
Comment (kngwyu) [inline build.rs]: This type annotation(`: &str`) is redundant.
Could you please all `: &str` from these 4 lines?
They're not your fault, but it's nice timing to refactor them.

**Comment by kngwyu** [comment]
It's merged at last, thanks.
