### PR TITLE
Change `search_lib_dir`'s return type to Result

### LINKED ISSUE #3952: panic when PYO3_CROSS_LIB_DIR is set to a missing path
i am trying to build "https://github.com/cher-nov/cryptg" for android, after defining everything i am still getting an error i cannot understand can you please help?
thanks.

this is the error:

Caused by:
  process didn't exit successfully: `/home/e/Desktop/rust/cryptg/target/release/build/pyo3-ffi-3e8bee156c9e8f82/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PYO3_CROSS
  cargo:rerun-if-env-changed=PYO3_CROSS_LIB_DIR
  cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_VERSION
  cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_IMPLEMENTATION
  cargo:rerun-if-env-changed=PYO3_NO_PYTHON

  --- stderr
  thread 'main' panicked at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/impl_.rs:1286:33:
  Path does not exist: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0:     0x5d9271c98566 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1:     0x5d9271c98566 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5d9271c98566 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
     3:     0x5d9271c98566 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x5d9271cbbba0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
     5:     0x5d9271cbbba0 - core::fmt::write::h3ed6aeaa977c8e45
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
     6:     0x5d9271c9588f - std::io::Write::write_fmt::h78b18af5775fedb5
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
     7:     0x5d9271c98344 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x5d9271c98344 - std::sys_common::backtrace::print::h85035a511aafe7a8
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x5d9271c99a37 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
    10:     0x5d9271c99799 - std::panicking::default_hook::hf5fcb0f213fe709a
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
    11:     0x5d9271c99ec8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
    12:     0x5d9271c99da2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
    13:     0x5d9271c98a66 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
    14:     0x5d9271c99b00 - rust_begin_unwind
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
    15:     0x5d9271c27415 - core::panicking::panic_fmt::h784f20a50eaab275
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
    16:     0x5d9271c27883 - core::result::unwrap_failed::h03d8a5018196e1cd
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
    17:     0x5d9271c3e42e - core::result::Result<T,E>::expect::h8beb11f53446bd2f
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1030:23
    18:     0x5d9271c3603b - pyo3_build_config::impl_::search_lib_dir::h149935c4f6bb86b1
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/impl_.rs:1286:14
    19:     0x5d9271c3591b - pyo3_build_config::impl_::find_all_sysconfigdata::h88e7440c5894a6c2
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/impl_.rs:1242:9
    20:     0x5d9271c351a0 - pyo3_build_config::impl_::find_sysconfigdata::h6945dc31b1f4fac4
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/impl_.rs:1177:31
    21:     0x5d9271c378da - pyo3_build_config::impl_::cross_compile_from_sysconfigdata::ha2da77a2a971b7af
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/impl_.rs:1350:25
    22:     0x5d9271c38237 - pyo3_build_config::impl_::load_cross_compile_config::ha207bdee8fb7b37b
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/impl_.rs:1476:34
    23:     0x5d9271c3ad85 - pyo3_build_config::impl_::make_cross_compile_config::h55fcd06f48f28cd3
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/impl_.rs:1700:38
    24:     0x5d9271c4a1c3 - pyo3_build_config::pyo3_build_script_impl::resolve_interpreter_config::hb55cb19547d3395f
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-build-config-0.20.2/src/lib.rs:188:50
    25:     0x5d9271c2a4ef - build_script_build::configure_pyo3::h660862241ac2233a
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-ffi-0.20.2/build.rs:80:30
    26:     0x5d9271c2ada1 - build_script_build::main::h6499a30294e2ac45
                                 at /home/e/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-ffi-0.20.2/build.rs:121:21
    27:     0x5d9271c291ab - core::ops::function::FnOnce::call_once::h59a15a55be2b1781
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
    28:     0x5d9271c28f0e - std::sys_common::backtrace::__rust_begin_short_backtrace::h1ea601e63da27be9
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
    29:     0x5d9271c28f81 - std::rt::lang_start::{{closure}}::h3ba4104c739f57c1
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
    30:     0x5d9271c90cd1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
    31:     0x5d9271c90cd1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
    32:     0x5d9271c90cd1 - std::panicking::try::h8bbf75149211aaaa
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
    33:     0x5d9271c90cd1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
    34:     0x5d9271c90cd1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
    35:     0x5d9271c90cd1 - std::panicking::try::do_call::hcb3194972c74716d
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
    36:     0x5d9271c90cd1 - std::panicking::try::hcdc6892c5f0dba4c
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
    37:     0x5d9271c90cd1 - std::panic::catch_unwind::h4910beb4573f4776
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
    38:     0x5d9271c90cd1 - std::rt::lang_start_internal::h6939038e2873596b
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
    39:     0x5d9271c28f5a - std::rt::lang_start::h097246fc9cc59edc
                                 at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
    40:     0x5d9271c2af1e - main
    41:     0x7ddefd429d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    42:     0x7ddefd429e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    43:     0x5d9271c27b45 - _start
    44:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
note: If the build failed due to a missing target, you can run this command:
note:
note:     rustup target install aarch64-linux-android

### PR DESCRIPTION
**Pull request by reswqa**
This closes #3952.

### CODE REVIEW

File: pyo3-build-config/src/impl_.rs [hunk 1]
```diff
@@ -1327,17 +1327,19 @@ fn is_cpython_lib_dir(path: &str, v: &Option<PythonVersion>) -> bool {
 }
 
 /// recursive search for _sysconfigdata, returns all possibilities of sysconfigdata paths
-fn search_lib_dir(path: impl AsRef<Path>, cross: &CrossCompileConfig) -> Vec<PathBuf> {
+fn search_lib_dir(path: impl AsRef<Path>, cross: &CrossCompileConfig) -> Result<Vec<PathBuf>> {
     let mut sysconfig_paths = vec![];
-    for f in fs::read_dir(path).expect("Path does not exist") {
+    for f in fs::read_dir(path)
+        .context("failed to search the lib dir, please check your path and permissions.")?
```
Comment (adamreichold) [inline pyo3-build-config/src/impl_.rs:1333]: I think we should name the relevant environment variables here or possibly add more targeted calls to `context` at the call sites of `search_lib_dir` so the user knows what to check exactly.

Comment (davidhewitt) [reply pyo3-build-config/src/impl_.rs]: Added a reference to `PYO3_CROSS_LIB_DIR`

**Comment by davidhewitt** [comment]
I pushed a commit to add a test and more clarity on the hints. Let's merge this; thanks @reswqa for getting this moving (and sorry I took so long to add input here)!
