### PR TITLE
use `FromPyObjectBound` for `PyAny::extract`

### LINKED ISSUE #3958: Better document how to migrate borrowing `extract()` calls
### Bug Description

To get a taste for the 0.21.0 migration I tried to migrate [instant-segment](https://github.com/instant-labs/instant-segment) over. If I manually enable `gil-refs` (I was a little surprised that wasn't default enabled), it compiles fine. However, if I remove `gil-refs` I get some compilation failures. However, reading the [migration guide](https://pyo3.rs/v0.21.0-beta.0/migration#from-020-to-021) didn't help me find a solution for this easily. Searching for `FromPyObject` finds some prose on that, mentioning the `extract_bound()` method but it didn't seem to help for this.

As discussed here: https://hachyderm.io/@davidhewitt@fosstodon.org/112077791453594471. Even with the additional hints on `FromPyObjectBound`, I didn't really figure out how to apply that here.

```rust
error[E0277]: the trait bound `&str: PyClass` is not satisfied
   --> instant-segment-py/src/lib.rs:38:45
    |
38  |                 let key = item.get_item(0)?.extract::<&str>()?;
    |                                             ^^^^^^^ the trait `PyClass` is not implemented for `&str`
    |
    = help: the following other types implement trait `PyClass`:
              Segmenter
              Search
    = note: required for `&str` to implement `FromPyObject<'_>`
note: required by a bound in `PyAny::extract`
   --> /Users/djc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.0-beta.0/src/types/any.rs:806:12
    |
804 |     pub fn extract<'py, D>(&'py self) -> PyResult<D>
    |            ------- required by a bound in this associated function
805 |     where
806 |         D: FromPyObject<'py>,
    |            ^^^^^^^^^^^^^^^^^ required by this bound in `PyAny::extract`
```

### Steps to Reproduce

1. `git clone https://github.com/instant-labs/instant-segment`
2. Update `instant-segment-py/Cargo.toml` to depend on pyo3 `=0.21.0-beta.0`
3. Run `cargo check`

### Backtrace

_No response_

### Your operating system and version

macOS 14.4

### Your Python version (`python --version`)

Python 3.9.6 (default, Feb  3 2024, 15:58:27)

### Your Rust version (`rustc --version`)

rustc 1.76.0 (07dca489a 2024-02-04)

### Your PyO3 version

0.21.0-beta.0

### How did you install python? Did you use a virtualenv?

System Python 3.

### Additional Info

FWIW, I've always found the `.parse()` form of `FromStr` a little too magic as a reader, and I usually use `Type::from_str()` instead. It would be nice if that was used more often/was ergonomic enough for these kinds of things (though chaining like in this particular context maybe too hard?).

### PR DESCRIPTION
**Pull request by Icxolu**
This changes the bound of `PyAny::extract` to use `FromPyObjectBound` instead of `FromPyObject`. This allows extracting borrowed types like `&str` or `&[u8]` using the `gil-ref` API, even if the `gil-refs` feature is disabled.

To allow this, `FromPyObjectBound::from_py_object_bound` is switched to take a `Borrowed` instead of `&Bound`. ~This also means that the `FromPyObjectBound` implemetations can now be unconditionally.~ To not break fully qualified syntax (`FromPyObject::extract`) these are kept with `gil-refs` enabled.

Fixes #3958

### CODE REVIEW

File: src/conversions/std/slice.rs [hunk 1]
```diff
@@ -20,21 +18,8 @@ impl<'a> IntoPy<PyObject> for &'a [u8] {
...
-    fn extract(obj: &'py PyAny) -> PyResult<Self> {
-        Ok(obj.downcast::<PyBytes>()?.as_bytes())
-    }
-
-    #[cfg(feature = "experimental-inspect")]
-    fn type_input() -> TypeInfo {
-        Self::type_output()
-    }
-}
-
```
Comment (davidhewitt) [inline src/conversions/std/slice.rs:34]: I think it might be good to keep the conditional implementations here, only because code which was previously calling `FromPyObject::extract(obj)` using UFCS will break when removing these implementations. So the action of removing the `gil-refs` feature seems like a gentler break point IMO.

**Review by davidhewitt — COMMENTED** [review]
Making `PyAny::extract` work the same way as the other `.extract()` methods seems like a good consistency change. Because `FromPyObjectBound` has a blanket from `FromPyObject`, I would hope that it means that users depending on `FromPyObject` as a trait bound in generic code wouldn't experience breaking changes.

File: src/conversions/std/slice.rs (hunk 1 above)
Comment (Icxolu) [reply src/conversions/std/slice.rs:34]: Ah, that makes sense, haven't thought of that. I'll drop the comment removing those

**Review by davidhewitt — APPROVED** [review]
This looks good to me, thanks!
