### PR TITLE
fixes #4285 -- allow full-path to pymodule with nested declarative modules

### LINKED ISSUE #4285: Declarative modules submodules don't work with `#[pyo3::prelude::pymodule]`
pyca/cryptography avoids using the prelude, and instead references things with their full name.

This does not work with declarative modules's submodules:

```rust
#[pyo3::prelude::pymodule]
mod foo {
    // `submod` won't actually be registered!
    #[pyo3::prelude::pymodule]
    mod submod {}
}
```

This is because we specifically look for `#[pymodule]`, but don't allow the full name: https://github.com/PyO3/pyo3/blob/main/pyo3-macros-backend/src/module.rs#L213

We should allow the full name to work.

### PR DESCRIPTION
**Pull request by alex**
fixes #4285

### CODE REVIEW

File: pyo3-macros-backend/src/module.rs [hunk 1]
```diff
@@ -207,10 +207,12 @@ pub fn pymodule_module_impl(mut module: syn::ItemMod) -> Result<TokenStream> {
             }
             Item::Mod(item_mod) => {
                 ensure_spanned!(
-                    !has_attribute(&item_mod.attrs, "pymodule_export"),
+                    !has_attribute(&item_mod.attrs, &["pymodule_export"]),
                     item.span() => "`#[pymodule_export]` may only be used on `use` statements"
                 );
-                if has_attribute(&item_mod.attrs, "pymodule") {
+                if has_attribute(&item_mod.attrs, &["pymodule"])
+                    || has_attribute(&item_mod.attrs, &["pyo3", "prelude", "pymodule"])
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/module.rs:214]: We should probably use `ctx.pyo3_path` instead of `pyo3` hard-coded here.

`pyo3::pymodule` is also a valid path to the macro, so we should allow that.

**Review by davidhewitt — COMMENTED** [review]
Thanks, this is definitely worth solving.

I'd prefer a more complete solution. I think also this needs similar treatment for `#[pyclass]` and `#[pyfunction]`?

I wonder whether a more thorough alternative solution would be to immediately parse and expand inner `#[pyclass]` / `#[pyfunction]` / `#[pymodule]` macros. I don't know if there's any implications of expansion ordering related to that.

Actually now that I say this - I guess declarative modules will fail to see a structure like this already:

```rust
#[pymodule]
mod foo {
    macro_rules! class {
        ($name:ident) {
            #[pyclass]
            struct $name { }
        }
    }
    
    class!(Foo);
    class!(Bar);
}
```

File: pyo3-macros-backend/src/module.rs (hunk 1 above)
Comment (alex) [reply pyo3-macros-backend/src/module.rs]: Hmm, moved too fast, it's not clear what the best way to get an `&str` out of the `syn::Path` is. This may need more involved surgery.

**Comment by alex** [comment]
Hmm, how would expanding the macros eagerly work? Handling the variety of different forms a user can write this in is... expansive. (A user can `use pyo3::prelude as foo;` which this PR obviously doesn't handle.)

**Comment by alex** [comment]
Are there other pieces you'd like here besides expanding to pyfunction/pyclass?

**Comment by davidhewitt** [comment]
I think that's just it, I see you solved the `Path` complication above 👍

The eager expansion / unlimited forms of `use` imports can be problems for the future.

**Comment by alex** [comment]
Will add support for those after work today. Thanks for the review

**Comment by alex** [comment]
Ok, added!

**Review by davidhewitt — APPROVED** [review]
Looks fine to me, thanks!
