### PR TITLE
fix deprecation warning for trailing optional on `#[setter]` functions

### LINKED ISSUE #4292: 'Deprecation of implicit default for trailing optional arguments' Causing issues with erasable setters
### Bug Description

As a result of the (upcoming) changes in 0.22 and 0.23 with `Option<T>` arguments requiring a `#[pyo3(signature=...)]` [link to migration guide](https://pyo3.rs/v0.22.0/migration#deprecation-of-implicit-default-for-trailing-optional-arguments).

This causes a problem for setters of a `pyclass`, which can be erased by setting `None`, since you're not allowed to specify a signature on a setter.

This is caused by #2935. In this case, I do not need a default argument. 
However, it will be required in version 0.23.

### Steps to Reproduce

```rust
use pyo3::prelude::*;

#[pyclass]
struct SimpleClass {
    field: Option<u32>
}

#[pymethods]
impl SimpleClass {
    #[new]
    #[pyo3(signature = (value=None))]
    fn new(field: Option<u32>) -> Self {
        Self { field }
    }

    #[getter]
    fn get_field(&self) -> Option<u32> {
        self.field
    }

    /// This causes issues
    #[setter]
    fn set_field((&mut self, field: Option<u32>) {
        self.field = field;
    }
}
```

### Backtrace

_No response_

### Your operating system and version

Windows/Linux (All effected)

### Your Python version (`python --version`)

Python 3.10.12

### Your Rust version (`rustc --version`)

rustc 1.79.0 (129f3b996 2024-06-10)

### Your PyO3 version

0.22+

### How did you install python? Did you use a virtualenv?

apt + venv

### Additional Info

This currently causes non-removable warnings, however in the future this will break code.

EDIT: Added more information

### PR DESCRIPTION
**Pull request by davidhewitt**
Fixes #4292

Basically just don't emit the warning for `setter` or `getter` functions, and adds a test.

### CODE REVIEW

File: pyo3-macros-backend/src/method.rs [hunk 1]
```diff
@@ -228,6 +228,18 @@ impl FnType {
         }
     }
 
+    pub fn signature_attribute_allowed(&self) -> bool {
```
Comment (alex) [inline pyo3-macros-backend/src/method.rs:231]: I think it'd be helpful for future us to add a comment explaining why (getter/setter/classattr have fixed signatures with a single arg where `Option<>` has a specific meaning)

Comment (davidhewitt) [reply pyo3-macros-backend/src/method.rs:231]: Good idea, added one, WDYT?

Comment (alex) [reply pyo3-macros-backend/src/method.rs:231]: LGTM. Thanks
