### PR TITLE
auto-initialize: new feature to control initializing Python

### LINKED ISSUE #742: test suite failures and missing symbols on macOS
## 🐛 Bug Reports

There are failures in the test suite on macOS with `pyenv` installed Python 3.7.6.

```
failures:

---- buffer::test::test_array_buffer stdout ----
thread 'buffer::test::test_array_buffer' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: Py(0x10b9fa4f0, PhantomData) }', src/libcore/result.rs:1189:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- exceptions::test::test_check_exception stdout ----
thread 'exceptions::test::test_check_exception' panicked at 'Can not import module: socket: PyErr { type: Py(0x10b9fa4f0, PhantomData) }', src/libcore/result.rs:1189:5


failures:
    buffer::test::test_array_buffer
    exceptions::test::test_check_exception
```

The issue is caused by missing Python library symbols in the final linked rust executable.  For example, the failure in `test_check_exception` happens on an `import socket`.  The Python `socket` module imports a C extension module `_socket` that references `_PyTime_AsMilliseconds`, which is missing:

```
Traceback (most recent call last):
  File "/Users/david/.pyenv/versions/3.7.6/lib/python3.7/socket.py", line 49, in <module>
    import _socket
ImportError: dlopen(/Users/david/.pyenv/versions/3.7.6/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so, 2): Symbol not found: __PyTime_AsMilliseconds
  Referenced from: /Users/david/.pyenv/versions/3.7.6/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/david/.pyenv/versions/3.7.6/lib/python3.7/lib-dynload/_socket.cpython-37m-darwin.so
```
The issue may be related to the fact that the `pyenv` installation only provides a static Python library.  

The issue may be known; it was obliquely mentioned in #704 before being deleted from the original issue report.

### 🌍 Environment

 - Your operating system and version:
macOS 10.15.2

 - Your python version:
3.7.6

 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:
pyenv 

 - Your rust version (`rustc --version`):
1.41.0-nightly

 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` 
Yes.

### 💥 Reproducing

`cargo test`

### LINKED ISSUE #762: Importing Python random lead to an error
Hi!

### 🌍 Environment

 - Your operating system and version:

macOS Mojave 10.14.6
 - Your python version: 

Tested on 3.8.1 and 3.6.10
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:

I use pyenv
 - Your rust version (`rustc --version`):

rustc 1.43.0-nightly (58b834344 2020-02-05)
 - Are you using the latest pyo3 version? Have you tried using latest master?

0.8.4 and master both have this issue 

### 💥 Reproducing

```rust
fn main(){
    let gil = Python::acquire_gil();
    let py = gil.python();
    match py.import("random") {
            Err(e) => e.print(py),
            Ok(x) => {},
        }
}
```

```
Traceback (most recent call last):
  File "/Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: dlopen(/Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/lib-dynload/math.cpython-36m-darwin.so, 2): Symbol not found: __PyLong_GCD
  Referenced from: /Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/lib-dynload/math.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/lib-dynload/math.cpython-36m-darwin.so
```

### LINKED ISSUE #1213: Failing tests on master
## 🐛 Bug Reports

After I cloned the repo for the first time I ran the tests to check for errors and I got two. I'm reporting them here by suggestion of @kngwyu .

```
failures:

---- buffer::test::test_array_buffer stdout ----
thread 'buffer::test::test_array_buffer' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: 0x55fb0678ffe0 }', src/buffer.rs:675:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- exceptions::test::test_check_exception stdout ----
thread 'exceptions::test::test_check_exception' panicked at 'Can not import module: socket: PyErr { type: 0x55fb0678ffe0 }', src/exceptions.rs:499:5


failures:
    buffer::test::test_array_buffer
    exceptions::test::test_check_exception
```

### 🌍 Environment

 - Your operating system and version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
$ uname -rsm       
Linux 5.4.0-39-generic x86_64
```
 - Your python version: 
```
$ python --version
Python 2.7.17
$ python3 --version
Python 3.8.3
```
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Python 2 - apt, Python 3 - Compiled from source, installed to system.
 - Your Rust version (`rustc --version`):
```
$ rustc --version
rustc 1.48.0-nightly (8876ffc92 2020-10-02)
```
 - Your PyO3 version: Master @ 37ce406ba18eb4f42bebf14c4bf33596f1f0dc3b
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: See above

### 💥 Reproducing

I ran:
```
$ cargo test
```

### PR DESCRIPTION
**Pull request by davidhewitt**
This PR add a new feature `auto-initialize` to control whether `Python::with_gil` and `Python::acquire_gil` call `prepare_freethreaded_python` automatically.

I wanted to add this for a couple of reasons:
- When building an `extension-module` then this functionality is not needed.
- When linking against a static python lib (or PyPy) then this functionality doesn't even work correctly.

The PR checks for the static python and PyPy cases and removes the `prepare_freethreaded_python` API, and instead emits a `compile_error!` if the `auto-initialize` feature is enabled.

Closes #742
Closes #762
Closes #1213 

---

**TODO:**

It would be nice to make this feature opt-in instead of opt-out, but that's a breaking change so we should delay that until 0.14 release.

I'd like to write some more documentation for this in the guide before merging. 

Also needs CHANGELOG entry.

### CODE REVIEW

**Comment by kngwyu** [comment]
Thanks!
I really like the idea to raise a compile error before failing to link, but I need some clarifications:
- About `prepare_freethreaded_python`:
  - I agree that this should be disabled for PyPy or static linking. Then, how about introducing some new configuration(e.g., `Py_SHARED`) and mark `#[cfg(not(any(PyPy, Py_SHARED)))] fn prepare_freethreaded_python`? I'm not sure this should be a feature flag.
- About `auto-initialize`
  - Isn't this a `not(extension-module)`? Why do we need a new feature?

Again, this is a difficult problem, and thank you for tackling it.

**Comment by davidhewitt** [comment]
Thanks for the questions. I'm very happy to change the design if we think alternatives are better. Here's my thinking about your proposed alternatives:

- using `Py_SHARED` flag, I don't think we can fail compilation in `build.rs`. This means the error message when building will be that `prepare_freethtreaded_python` is missing. A nicer error than link failures maybe, especially if we add documentation to that function do that users understand what might have happened.

  The failure will still be quite hard to diagnose for the user compared to a friendly error message from the build script.

- With `auto-initialize` being `not(extension-module)` - I suppose in practice yes, this is true. But I think this would then be another case of #771 because then `extension-module` feature is taking away functionality again.

  Also, this would mean that users who want to run `cargo test` which relies on auto-initialize would have to _always_ use the `--no-default-features` workaround to disable `extension-module`, even after #1123 is stable. It seems more idiomatic Rust to me to be able to control this properly with a separate feature flag.

  The feature flag is also more general. For example, in some special cases users might want to embed python and manually initialize it before calling PyO3 code. In those cases they don't need `auto-initialize` functionality either.

**Comment by davidhewitt** [comment]
... I'm thinking that maybe we can use `Py_SHARED` plus the `auto-initialize` feature. We can use `compile_error!` to produce a friendly error message, so my argument above for the `embedding` feature now seems weak.

**Comment by davidhewitt** [comment]
Reworked this PR as discussed but I expect CI to continue to fail until #1350 is merged, because one of the simplifications in that PR fixes how Py_SHARED would be set.

**Comment by davidhewitt** [comment]
Rebased and rebuilt this PR as a single commit; hopefully CI is green this time 🤞

File: src/gil.rs [hunk 1]
```diff
@@ -137,7 +136,56 @@ impl GILGuard {
...
+        //    auto-initialize so this avoids breaking existing builds.
+        //  - Otherwise, just check the GIL is initialized.
+        cfg_if::cfg_if! {
+            if #[cfg(all(feature = "auto-initialize", Py_SHARED, not(PyPy)))] {
+                prepare_freethreaded_python();
+            } else if #[cfg(all(feature = "auto-initialize", not(feature = "extension-module"), not(Py_SHARED), not(rustdoc)))] {
+                compile_error!(concat!(
+                    "The `auto-initialize` feature is not supported when linking Python ",
+                    "statically instead of with a shared library.\n",
+                    "\n",
```
Comment (kngwyu) [inline src/gil.rs:152]: How about making this a bit shorter?
```suggestion
                    "statically instead of with a shared library.\n\n",
```

File: src/gil.rs [hunk 2]
```diff
@@ -137,7 +136,56 @@ impl GILGuard {
...
+        // Maybe auto-initialize the GIL:
+        //  - If auto-initialize feature set and supported, try to initalize the interpreter.
+        //  - If the auto-initialize feature is set but unsupported, emit hard errors only when
+        //    the extension-module feature is not activated - extension modules don't care about
+        //    auto-initialize so this avoids breaking existing builds.
+        //  - Otherwise, just check the GIL is initialized.
+        cfg_if::cfg_if! {
+            if #[cfg(all(feature = "auto-initialize", Py_SHARED, not(PyPy)))] {
+                prepare_freethreaded_python();
+            } else if #[cfg(all(feature = "auto-initialize", not(feature = "extension-module"), not(Py_SHARED), not(rustdoc)))] {
```
Comment (kngwyu) [inline src/gil.rs:148]: I think we can make this simpler by `else if all(auto-initialize, PyPy) { ... } else if all(auto_initialize, ...)`

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -84,28 +84,31 @@ jobs:
...
-      - name: Build docs
-        run: cargo doc --features "num-bigint num-complex hashbrown" --verbose --target ${{ matrix.platform.rust-target }}
+      # Validate docs have no warnings (except on PyPy; auto-initialize feature fails the compile until `cfg(rustdoc)` is stable).
+      - if: matrix.python-version != 'pypy-3.6'
+        name: Build docs
+        run: cargo doc --no-default-features --features "macros num-bigint num-complex hashbrown" --verbose --target ${{ matrix.platform.rust-target }}
 
-      - name: Build without default features
+      - name: Build (no features)
         run: cargo build --no-default-features --verbose --target ${{ matrix.platform.rust-target }}
```
Comment (kngwyu) [inline .github/workflows/ci.yml:93]: It looks like that `auto-initialize` and `macros` are enabled in this build, though I don't know why 😕

File: .github/workflows/ci.yml [hunk 4]
```diff
@@ -84,28 +84,31 @@ jobs:
...
-      - name: Build with default features
-        run: cargo build --features "num-bigint num-complex hashbrown" --verbose --target ${{ matrix.platform.rust-target }}
+      - name: Build (all additive features)
+        run: cargo build --no-default-features --features "macros num-bigint num-complex hashbrown" --verbose --target ${{ matrix.platform.rust-target }}
 
       # Run tests (except on PyPy, because no embedding API).
       - if: matrix.python-version != 'pypy-3.6'
         name: Test
-        run: cargo test --features "num-bigint num-complex hashbrown" --target ${{ matrix.platform.rust-target }}
+        run: cargo test --no-default-features --features "macros num-bigint num-complex hashbrown" --target ${{ matrix.platform.rust-target }}
```
Comment (kngwyu) [inline .github/workflows/ci.yml:101]: Why not using `auto-initialize`?

**Review by kngwyu — APPROVED** [review]
LGTM, thanks!
CI failures are because `auto-initialise` is unintentionally invoked. I'm sorry but I have no idea why this happens.

File: src/gil.rs (hunk 2 above)
Comment (davidhewitt) [reply src/gil.rs:148]: `not(extension-module)` is unfortunately necessary to avoid a breaking change - otherwise all extension modules would suddenly start failing. We could make it as you suggest in `0.14`.

File: .github/workflows/ci.yml (hunk 4 above)
Comment (davidhewitt) [reply .github/workflows/ci.yml:101]: It's automatically included in tests because I put this in `[dev-dependencies]`:

```
# features needed to run the PyO3 test suite
pyo3 = { path = ".", default-features = false, features = ["macros", "auto-initialize"] }
```

However, that's also the reason why `auto-initialize` and `macros` are included in the `cargo build` command above. Interestingly `cargo` is about to stabilize a fix for this as a new `resolver = "2"` option in Cargo.toml. https://github.com/rust-lang/cargo/pull/8997 (I tested on nightly and the features are no longer included in `cargo build`.)

Because in the future what I've done here _will_ work correctly in the future, I'm going to keep the code mostly as-is for the moment and introduce a hack to avoid the immediate issue with a TODO to tidy it up once we bump MSRV in the future (probably to Rust 1.52).

File: .github/workflows/ci.yml (hunk 3 above)
Comment (davidhewitt) [reply .github/workflows/ci.yml:93]: It's because of the `Cargo.toml` changes - see other comment.

File: src/gil.rs (hunk 2 above)
Comment (kngwyu) [reply src/gil.rs]: Ah, thanks. That makes sense.
BTW, do you think that we should keep auto-initialize in default-features?

Comment (davidhewitt) [reply src/gil.rs]: I think in the long-run it's better to remove `auto-initialize` from default-features, but that's also a breaking change, so let's remove it in `0.14`.

I'll create an issue to track these cleanups and add it to the `0.14` milestone.

**Comment by davidhewitt** [comment]
@kngwyu I pushed a CHANGELOG entry and a new guide page `guide/src/features.md` to document this functionality.

I also added a tiny "hack" with `cfg(__pyo3_ci)` to suppress the error message in our CI until we are able to bump MSRV to a Rust version which includes the cargo `resolver = "2"`. Might be nearly a year though - I put `TODO` on the location in `ci.yml` and `build.rs` where I added the hack.

If you are happy with this, I think this is ready to merge! 🚀

**Comment by kngwyu** [comment]
> I also added a tiny "hack" with cfg(__pyo3_ci) to suppress the error message in our CI until we are able to bump MSRV to a Rust version which includes the cargo resolver = "2". Might be nearly a year though - I put TODO on the location in ci.yml and build.rs where I added the hack.

Is it much simpler to remove the dev-dependency for now?

File: src/gil.rs (hunk 2 above)
Comment (kngwyu) [reply src/gil.rs]: 👍🏼

**Comment by davidhewitt** [comment]
If we remove the `dev-dependency` and also remove `auto-initialize` from default features then to run the PyO3 test suite we'll have to write `cargo test --features auto-initialize`.

I'm sure I'll forget to add the feature a lot and it's also annoying to type something so long.

I think it's better to leave the very small hack in so that we can make exactly the API we want for users. Especially as we know the fix which removes the need for the hack is going to be stabilised very soon.

(Because we only need the hack to fix the pypy CI jobs, we only need to wait until it's in the most recent stable rust version.)

**Comment by kngwyu** [comment]
> If we remove the dev-dependency and also remove auto-initialize from default features

OK, if you are to release 0.14 before the next stable release, let's go in this way 👍🏼 #

**Comment by davidhewitt** [comment]
(I force-pushed to fix the commit message. Will merge shortly.)
