### PR TITLE
Left-hand operands are fellback to right-hand ones for type mismatching

### LINKED ISSUE #844: __radd__ etc don't get called if __add__ is also defined
If we make a class like this:

```rust
#[pyclass]
#[derive(Debug)]
struct RhsArithmetic {}

#[pymethods]
impl RhsArithmetic {
    #[new]
    fn new() -> RhsArithmetic {
        RhsArithmetic {}
    }
}

#[pyproto]
impl PyNumberProtocol for RhsArithmetic {
    fn __mul__(lhs: PyRef<'p, Self>, rhs: &PyAny) -> PyResult<String> {
        Ok(format!("MUL"))
    }
    fn __rmul__(&self, other: &PyAny) -> PyResult<String> {
        Ok(format!("RMUL"))
    }
}
```

Then both `1 * rhs` and `rhs * 1` call the function in the `tp_as_number.nb_mul` slot. As of #839 this will be our `__mul__` implementation above (and never `__rmul__`).

And specifically it will call it with the arguments in the same order as invoked. So from above, we will have `__mul__(1, rhs)` and `__mul__(rhs, 1)`.

This is problematic, because `__mul__` as defined above will raise a `TypeError` if the first argument is not `Self`.

We saw this behaviour reported on Gitter. All three of the below will currently be calling `__mul__`, which is why the second will `TypeError`:

```
>>> rhs * 1.0
'MUL'
>>> 1.0 * rhs # should call __rmul__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError
>>> rhs * rhs
'MUL'
```

I am thinking that instead of doing [this](https://github.com/PyO3/pyo3/blob/1aa4ae82847ec418791419ff74f54e5b5f85b30f/src/class/number.rs#L650), if both `__mul__` and `__rmul__` are defined we should be creating a wrapper function which calls the correct function depending on the type of the first argument.

The implementation of [`PyNumber_Add`](https://github.com/python/cpython/blob/224481a8c988fca12f488544edd2f01c0af2a91d/Objects/abstract.c#L999) suggests that we should return `Py_NotImplemented` from this wrapper function if there is a type error, so that `sq_concat` is given a chance to be called also.

### PR DESCRIPTION
**Pull request by kngwyu**
Fixes #844. 
Include some other refactorings:
- ` SlotSetter` is refactored not to have `skipped_setters` field.
- `py_ternary_num_func` macros are removed since they are just called once.
- `#[macro_export]` for macros in `class/macros.rs` are removed.

### CODE REVIEW

**Comment by kngwyu** [comment]
And I changed right hand methods to use `extract_or_return_not_implemented`, so now we can write tests that confirm that `NotImplemented` is correctly returned when both of `__add__` and `__radd__` is defined. cc: @mvaled

**Comment by kngwyu** [comment]
Sigh, coverage decreased after I added some tests... :sweat:

File: tests/test_arithmetics.rs [hunk 1]
```diff
@@ -292,46 +328,182 @@ impl PyNumberProtocol for LhsAndRhsArithmetic {
...
+    py_run!(py, c, "assert 1 >> c == '1 >> BA'");
+    py_run!(py, c, "assert 1 & c == '1 & BA'");
+    py_run!(py, c, "assert 1 ^ c == '1 ^ BA'");
+    py_run!(py, c, "assert 1 | c == '1 | BA'");
     py_run!(py, c, "assert 1 ** c == '1 ** BA'");
 }
 
+#[pyclass]
+#[derive(Debug)]
+struct LhsFellbackToRhs {}
```
Comment (davidhewitt) [inline tests/test_arithmetics.rs:397]: Rather than making a new `#[pyclass]` here, was it possible to just use the renamed `LhsAndRhsArithmetic` class? There's four sets of tests which we can write:

```
#[test]
fn can_call_lhs_explicitly() {
    py_run!(py, c, "assert c.__add__(1) == '1 + BA'");
}

#[test]
fn can_call_rhs_explicitly() {
    py_run!(py, c, "assert c.__radd__(1) == '1 + RA'");
    // etc for all operators
}

#[test]
fn can_call_lhs_operation() {
     py_run!(py, c, "assert c + 1 == '1 + BA'");
    // etc for all operators
}

#[test]
fn can_call_rhs_operation() {
     py_run!(py, c, "assert 1 + c == '1 + RA'");
    // etc for all operators
}
```

File: pyo3-derive-backend/src/pyproto.rs [hunk 2]
```diff
@@ -134,23 +134,22 @@ fn slot_initialization(
...
     // Collect initializers
     let mut initializers: Vec<TokenStream> = vec![];
-    'outer_loop: for m in proto.slot_setters {
-        if skipped_setters.contains(&m.set_function) {
+    for m in proto.slot_setters {
+        // Skip if any required protocol are not implemented or already used.
+        if m.proto_names
+            .iter()
+            .any(|name| !method_names.contains(*name) || used_protocols.contains(name))
+        {
```
[the remark this answers is not in the document]
Comment (kngwyu) [reply pyo3-derive-backend/src/pyproto.rs]: Thanks, I encapsuled it to an iterator.

File: tests/test_arithmetics.rs (hunk 1 above)
Comment (kngwyu) [reply tests/test_arithmetics.rs]: Thanks, I simplified the test cases, though I still stuck with `lhs_overrides_rhs` and `lhs_fellback_to_rhs`.

File: tests/test_arithmetics.rs [hunk 3]
```diff
@@ -292,44 +338,94 @@ impl PyNumberProtocol for LhsAndRhsArithmetic {
...
+    fn __rmatmul__(&self, other: &PyAny) -> String {
+        format!("{:?} @ RA", other)
     }
 }
 
 #[pyproto]
-impl PyObjectProtocol for LhsAndRhsArithmetic {
+impl PyObjectProtocol for LhsAndRhs {
     fn __repr__(&self) -> &'static str {
         "BA"
```
Comment (davidhewitt) [inline tests/test_arithmetics.rs:377]: I wonder if `LhsAndRhs` should have a field `name: String`, and then this could be:

```suggestion
        &self.name
```

That way the tests could be written as e.g. `"assert a.__radd__(b) == 'B + A'"`

(I find `RA` and `BA` slightly confusing. It's easy enough to look back up at the pyclass to figure it out though, so this isn't a strong feeling.)

File: pyo3-derive-backend/src/defs.rs [hunk 4]
```diff
@@ -30,6 +31,40 @@ impl Proto {
     {
         self.py_methods.iter().find(|m| query == m.name)
     }
+    // Since the order matters, we expose only the iterator instead of the slice.
+    pub(crate) fn setters(&self, implemented: HashSet<String>) -> SlotSetterIter {
+        SlotSetterIter {
+            iter: self.slot_setters.iter(),
+            implemented_protocols: implemented,
```
Comment (davidhewitt) [inline pyo3-derive-backend/src/defs.rs:38]: I quite like `std::iter::from_fn`, and return `impl Iterator<Item = &'static str>` instead of making a new struct, but I am happy with this way too 👍

**Review by davidhewitt — APPROVED** [review]
This looks really great! Feel free to take on or ignore any of these minor ideas as you like before merging 😄

File: CHANGELOG.md [hunk 5]
```diff
@@ -42,6 +42,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 - Allows `&Self` as a `#[pymethods]` argument again. [#1071](https://github.com/PyO3/pyo3/pull/1071)
 - Fix best-effort build against PyPy 3.6. #[1092](https://github.com/PyO3/pyo3/pull/1092)
 - Improve lifetime elision in `#[pyproto]`. [#1093](https://github.com/PyO3/pyo3/pull/1093)
+- `__add__` is correctly fellback to `__radd__` when both of them are defined. [#1107](https://github.com/PyO3/pyo3/pull/1107)
```
[the remark this answers is not in the document]
Comment (davidhewitt) [reply CHANGELOG.md:45]: Actually I think the fallback is an implementation detail the user doesn't need to know about, maybe this version says what they need to care about:

```suggestion
- Fix support for both `__add__` and `__radd__`  in the `+` operator when both are defined in `PyNumberProtocol` (and similar for all other reversible operators). [#1107](https://github.com/PyO3/pyo3/pull/1107)
```

[the remark this answers is not in the document]
Comment (kngwyu) [reply CHANGELOG.md:45]: :+1:

File: tests/test_arithmetics.rs (hunk 3 above)
Comment (kngwyu) [reply tests/test_arithmetics.rs:377]: I tried so but it wasn't so meaningful when we want to test which operator is called.

File: pyo3-derive-backend/src/defs.rs (hunk 4 above)
Comment (kngwyu) [reply pyo3-derive-backend/src/defs.rs:38]: Thanks, I didn't know that function.

File: tests/test_arithmetics.rs [hunk 6]
```diff
@@ -280,10 +280,56 @@ fn rhs_arithmetic() {
 }
 
 #[pyclass]
-struct LhsAndRhsArithmetic {}
+struct LhsAndRhs {}
```
[the remark this answers is not in the document]
Comment (kngwyu) [reply tests/test_arithmetics.rs:283]: Since the behavior of `__add__` is almost the same as `+`, I don't see strong necessity for it.

File: pyo3-derive-backend/src/defs.rs [hunk 7]
```diff
@@ -30,6 +31,28 @@ impl Proto {
     {
         self.py_methods.iter().find(|m| query == m.name)
     }
+    // Since the order matters, we expose only the iterator instead of the slice.
+    pub(crate) fn setters(
+        &self,
+        mut implemented_protocols: HashSet<String>,
+    ) -> impl Iterator<Item = &'static str> {
+        self.slot_setters.iter().filter_map(move |setter| {
```
Comment (davidhewitt) [inline pyo3-derive-backend/src/defs.rs:39]: Nice one, this implementation is really elegant!

**Review by davidhewitt — APPROVED** [review]
💯
