### PR TITLE
fix vectorcall argument handling

### LINKED ISSUE #4093: `PyObject_CallOneArg()` usage triggers assert
### Bug Description

I'm getting an error using `PyObject_CallOneArg()` and I think this may be a bug. Feel free to close this issue if it isn't 👀 

### Steps to Reproduce

a minimal-ish example:

```rust
let zoneinfo_module = PyImport_ImportModule("zoneinfo\0".as_ptr().cast::<c_char>());
let zoneinfo_class =
    PyObject_GetAttrString(zoneinfo_module, "ZoneInfo\0".as_ptr().cast::<c_char>());
let zoneinfo_instance = PyObject_CallOneArg(
    zoneinfo_class,
    PyUnicode_FromString("Europe/Amsterdam\0".as_ptr().cast::<c_char>()),
);
```

this triggers the assert below. Indeed the `n` is set to `9223372036854775809` (max i64 + 1). The function _seems_ to usually get smaller values like `0`, or `3` (corresponding to the number of arguments).

```rust
// abstract_.rs
pub unsafe fn PyVectorcall_NARGS(n: size_t) -> Py_ssize_t {
    assert!(n <= (PY_SSIZE_T_MAX as size_t));
    (n as Py_ssize_t) & !PY_VECTORCALL_ARGUMENTS_OFFSET
}

```

The large value can be traced back directly to `PyObject_CallOneArg`

```rust
// in abstract_.rs
pub unsafe fn PyObject_CallOneArg(func: *mut PyObject, arg: *mut PyObject) -> *mut PyObject {
    assert!(!arg.is_null());
    let args_array = [std::ptr::null_mut(), arg];
    let args = args_array.as_ptr().offset(1); // For PY_VECTORCALL_ARGUMENTS_OFFSET
    let tstate = PyThreadState_GET();
    let nargsf = 1 | PY_VECTORCALL_ARGUMENTS_OFFSET;
    _PyObject_VectorcallTstate(tstate, func, args, nargsf as size_t, std::ptr::null_mut())
}
```

where `1 | PY_VECTORCALL_ARGUMENTS_OFFSET` results in this massive number. Patching  `let nargsf = 1;` gets things working—but it should obviously be derived from `PY_VECTORCALL_ARGUMENTS_OFFSET` in some way.

I'm still pretty new to the C API, so it isn't obvious to me what the answer is 😬. Of course I'd be happy to submit a PR if that'd help 🙂 

### Backtrace

_No response_

### Your operating system and version

MacOS 14.4.1

### Your Python version (`python --version`)

Python 3.12.0

### Your Rust version (`rustc --version`)

1.77.2

### Your PyO3 version

master branch

### How did you install python? Did you use a virtualenv?

```
pyenv virtualenv 3.12.0 foo
pyenv local foo
```

I then added my code to the `string_example` example in the `pyo3` repo

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by birkenfeld**
Fixes #4093

- Make PY_VECTORCALL_ARGUMENTS_OFFSET a size_t like on CPython
- Change the assert in PyVectorcall_NARGS to check the recovered number, not the original value (which is > PY_SSIZE_T_MAX on purpose)

### CODE REVIEW

**Comment by birkenfeld** [comment]
For the CPython definitions, see
- https://github.com/python/cpython/blob/main/Include/abstract.h#L275
- https://github.com/python/cpython/blob/main/Include/cpython/abstract.h#L32 and

File: pyo3-ffi/src/cpython/abstract_.rs [hunk 1]
```diff
@@ -42,14 +42,15 @@ extern "C" {
...
-    1 << (8 * std::mem::size_of::<Py_ssize_t>() as Py_ssize_t - 1);
+const PY_VECTORCALL_ARGUMENTS_OFFSET: size_t =
+    1 << (8 * std::mem::size_of::<size_t>() as size_t - 1);
 
 #[cfg(Py_3_8)]
 #[inline(always)]
 pub unsafe fn PyVectorcall_NARGS(n: size_t) -> Py_ssize_t {
-    assert!(n <= (PY_SSIZE_T_MAX as size_t));
-    (n as Py_ssize_t) & !PY_VECTORCALL_ARGUMENTS_OFFSET
+    let real_n = n & !PY_VECTORCALL_ARGUMENTS_OFFSET;
```
Comment (adamreichold) [inline pyo3-ffi/src/cpython/abstract_.rs:51]: I think it would be nicer to just shadow `n` here instead of adding another name.

File: pyo3-ffi/src/cpython/abstract_.rs [hunk 2]
```diff
@@ -42,14 +42,15 @@ extern "C" {
...
+    assert!(real_n <= (PY_SSIZE_T_MAX as size_t));
+    real_n as Py_ssize_t
```
Comment (adamreichold) [inline pyo3-ffi/src/cpython/abstract_.rs:53]: I think nightly Clippy recently started to lint this code and recommending

```rust
n.try_into().unwrap()
```

instead.

Comment (birkenfeld) [reply pyo3-ffi/src/cpython/abstract_.rs:53]: I don't see such a lint locally with nightly...

File: pyo3-ffi/src/cpython/abstract_.rs (hunk 1 above)
Comment (birkenfeld) [reply pyo3-ffi/src/cpython/abstract_.rs:51]: Ok.

File: pyo3-ffi/src/cpython/abstract_.rs (hunk 2 above)
Comment (adamreichold) [reply pyo3-ffi/src/cpython/abstract_.rs]: The reference to lint was mainly to explain why I suggested the change now even though it is unrelated to the issue in question. I do think Clippy is right though and deferring to the standard library implementation is more readable and less error prone.

File: pyo3-ffi/src/cpython/abstract_.rs [hunk 3]
```diff
@@ -42,14 +42,15 @@ extern "C" {
...
-const PY_VECTORCALL_ARGUMENTS_OFFSET: Py_ssize_t =
-    1 << (8 * std::mem::size_of::<Py_ssize_t>() as Py_ssize_t - 1);
+const PY_VECTORCALL_ARGUMENTS_OFFSET: size_t =
+    1 << (8 * std::mem::size_of::<size_t>() as size_t - 1);
 
 #[cfg(Py_3_8)]
 #[inline(always)]
 pub unsafe fn PyVectorcall_NARGS(n: size_t) -> Py_ssize_t {
+    let n = n & !PY_VECTORCALL_ARGUMENTS_OFFSET;
     assert!(n <= (PY_SSIZE_T_MAX as size_t));
```
Comment (davidhewitt) [inline pyo3-ffi/src/cpython/abstract_.rs:52]: Should we also remove the assertion? Python headers don't seem to have it, and with this implementation it now seems that this assertion will never be triggered due to the masking.

**Review by davidhewitt — COMMENTED** [review]
Whoops, my original implementation there makes no sense, thanks for fixing! A bit of a surprise we didn't get this reported before, I guess that we haven't managed to use these vectorcall methods very extensively in PyO3 itself yet...

File: pyo3-ffi/src/cpython/abstract_.rs (hunk 3 above)
Comment (davidhewitt) [reply pyo3-ffi/src/cpython/abstract_.rs:52]: I guess the suggested `.try_into().unwrap()` form would also remove the need for the assertion due to the introduction of the checked cast.

Comment (adamreichold) [reply pyo3-ffi/src/cpython/abstract_.rs:52]: The assertion would turn into the `unwrap`, but the runtime check could still be present. Personally, I would prefer the checked cast and let the compiler figure out that the masking may turn the check into no-op.

Comment (davidhewitt) [reply pyo3-ffi/src/cpython/abstract_.rs:52]: Agreed

File: pyo3-ffi/src/cpython/abstract_.rs (hunk 2 above)
Comment (birkenfeld) [reply pyo3-ffi/src/cpython/abstract_.rs]: Gotcha, will change it.

**Review by adamreichold — APPROVED** [review]
