### PR TITLE
unify `IntoPyObject`/`FromPyObject` derive attributes

### LINKED ISSUE #4884: limited `pyo3` options when deriving both `FromPyObject` and `IntoPyObject`?
Currently combining the derive macros for `FromPyObject` and `IntoPyObject` limits the possible `#[pyo3(...)]` options to the union of options supported by both macros. It would be desirable to also allow individual options when combining them.

See also: https://github.com/PyO3/pyo3/discussions/4883#discussioncomment-12000940

### Discussed in https://github.com/PyO3/pyo3/discussions/4883

<div type='discussions-op-text'>

<sup>Originally posted by **baxtersa** January 29, 2025</sup>
Hi all. I've been working with `FromPyObject` for values passed as arguments from python code calling into Rust, but am having trouble implementing the `IntoPyObject` direction. We have a custom `from_py_with` function because one of our fields is a generic type with a `const` parameter, so we manually convert from a `Vec` to a fixed-size array. When adding the derivation for `IntoPyObject`, we get compiler errors on the `pyo3(...)` attribute saying `error: expected 'attribute' or 'item'`. Without `derive(IntoPyObject)`, the rest of this code compiles just fine.

Here is a simplified reproduction of what I'm seeing

```rust
fn custom_fn(obj: &pyo3::Bound<pyo3::PyAny>) -> pyo3::PyResult<OtherType> {
    Ok(OtherType {
        other_field: 0
    })
}

pub struct OtherType {
    pub other_field: u32,
}

// No compilation error if I remove `pyo3::IntoPyObject` here
#[derive(pyo3::FromPyObject, pyo3::IntoPyObject)]
pub struct MinimalRepro {
    #[pyo3(from_py_with = "custom_fn")]
    pub field: OtherType,
}
```
and the compiler error we receive
```rust
error: expected `attribute` or `item`
   --> src/repro.rs:163:12
    |
163 |     #[pyo3(from_py_with = "custom_fn")]
    |            ^^^^^^^^^^^^
```
Is it possible to use `from_py_with` when also deriving `IntoPyObject`? I have seen that something like `into_py_with` is in-progress too, so maybe this is just a current limitation?

I'm using `pyo3=0.23.4`.

Thanks for the assistance.</div>

### PR DESCRIPTION
**Pull request by Icxolu**
This combines the attributes of the `IntoPyObject` and `FromPyObject` derive macros, such that individual options can still be used when deriving both.

Closes #4884

### CODE REVIEW

File: pyo3-macros-backend/src/derive_attributes.rs [hunk 1]
```diff
@@ -0,0 +1,217 @@
...
+    /// Treat the Container as a Wrapper, operate directly on its field
+    Transparent(attributes::kw::transparent),
+    /// Force every field to be extracted from item of source Python object.
+    ItemAll(attributes::kw::from_item_all),
+    /// Change the name of an enum variant in the generated error message.
+    ErrorAnnotation(LitStr),
+    /// Change the path for the pyo3 crate
+    Crate(CrateAttribute),
+    /// Converts the field idents according to the [RenamingRule](attributes::RenamingRule) before extraction
+    RenameAll(RenameAllAttribute),
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/derive_attributes.rs:21]: Should this be supported for `IntoPyObject`? I guess a separate follow-up issue.

**Review by davidhewitt — APPROVED** [review]
Thanks, this looks great to me! It's slightly unfortunate that if a user writes just `#[derive(IntoPyObject)]` and then adds a load of attributes only specific to `#[derive(FromPyObject)]` they are (often) just silently ignored, but it seems there is no better alternative (and the same as `serde`).

File: pyo3-macros-backend/src/derive_attributes.rs (hunk 1 above)
Comment (Icxolu) [reply pyo3-macros-backend/src/derive_attributes.rs:21]: Probably, will have a look 👍

**Comment by bbstilson** [comment]
@davidhewitt any idea which release this will release in?

**Comment by davidhewitt** [comment]
See #5107
