### PR TITLE
Introspection: Fixes Mach-O parsing

### LINKED ISSUE #5023: `range end index out of range` error in pyo3-introspection
### Bug Description

I'm trying to use the new `pyo3-introspection` crate (introduced in https://github.com/PyO3/pyo3/pull/3977) to generate stubs and ran into a panic when trying this on my MacOS arm64 machine. The binary I wrote to try and generate stubs is [@rules_pyo3//pyo3/private/stubgen.rs](https://github.com/abrisco/rules_pyo3/blob/7e7e5f1563bf7cf748ac74b5e5a06cfec2ed82ef/pyo3/private/stubgen.rs). The pyo3 module is being built optimized but I did try debug and got the same result.

### Steps to Reproduce

1. Clone https://github.com/abrisco/rules_pyo3/tree/stubgen
2. Run `bazel build //pyo3/private/tests/string_sum:string_sum`

### Backtrace

```shell
thread 'main' panicked at external/+rust_ext+rpyo3c__pyo3-introspection-0.25.0-dev/src/introspection.rs:214:38:
range end index 9007199255016033 out of range for slice of length 478128
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail::do_panic::runtime
   3: core::slice::index::slice_end_index_len_fail
   4: pyo3_introspection::introspection::read_symbol_value_with_ptr_and_len
   5: pyo3_introspection::introspection::find_introspection_chunks_in_macho
   6: pyo3_introspection::introspection::find_introspection_chunks_in_binary_object
   7: pyo3_introspection::introspection::introspect_cdylib
   8: stubgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Your operating system and version

MacOS arm64

### Your Python version (`python --version`)

Python 3.11.11

### Your Rust version (`rustc --version`)

1.85.1 (4eb161250 2025-03-15)

### Your PyO3 version

0.25.0-dev

### How did you install python? Did you use a virtualenv?

None

### Additional Info

I know my steps to repro are Bazel but I can work with someone to get more canonical repro steps. My hope was that I could provide enough info so that the issue might be obvious.

### PR DESCRIPTION
**Pull request by Tpt**
- properly pick the correct section
- clean error when fixup chains are used

Closes #5023

### CODE REVIEW

**Comment by Tpt** [comment]
(no changelog, this is a follow up to a previous not-relased-yet MR)

**Comment by abrisco** [comment]
FYI: If you update 

> Issue #5023

to 

```
closes #5023
```
 then the issue will be automatically closed upon merging 😄

File: pyo3-introspection/src/introspection.rs [hunk 1]
```diff
@@ -132,6 +133,12 @@ fn find_introspection_chunks_in_macho(
     if !macho.little_endian {
         bail!("Only little endian Mach-o binaries are supported");
     }
+    ensure!(
+        !macho.load_commands.iter().any(|command| {
+            matches!(command.command, CommandVariant::DyldChainedFixups(_))
+        }),
+        "Macho-o binaries with fixup chains are not supported yet, to avoid using fixup chains, use --codegen=link-arg=-no_fixup_chains option"
```
Comment (abrisco) [inline pyo3-introspection/src/introspection.rs:140]: Nit, I think backticks make the solution stand out a bit more
```suggestion
        "Macho-o binaries with fixup chains are not supported yet, to avoid using fixup chains, use `--codegen=link-arg=-no_fixup_chains` option"
```

File: pyo3-introspection/src/introspection.rs [hunk 2]
```diff
@@ -132,6 +133,12 @@ fn find_introspection_chunks_in_macho(
     if !macho.little_endian {
         bail!("Only little endian Mach-o binaries are supported");
     }
+    ensure!(
+        !macho.load_commands.iter().any(|command| {
+            matches!(command.command, CommandVariant::DyldChainedFixups(_))
+        }),
+        "Macho-o binaries with fixup chains are not supported yet, to avoid using fixup chains, use `--codegen=link-arg=-no_fixup_chains` option"
```
Comment (birkenfeld) [inline pyo3-introspection/src/introspection.rs:140]: Macho-O? :D

Comment (Tpt) [reply pyo3-introspection/src/introspection.rs:140]: Thanks!

```suggestion
        "Mach-O binaries with fixup chains are not supported yet, to avoid using fixup chains, use `--codegen=link-arg=-no_fixup_chains` option"
```

File: pyo3-introspection/src/introspection.rs [hunk 3]
```diff
@@ -140,9 +147,14 @@ fn find_introspection_chunks_in_macho(
...
-        if nlist.is_global() && nlist.get_type() == N_SECT && is_introspection_symbol(name) {
-            let section = &sections[nlist.n_sect];
+    for symbol in macho.symbols() {
+        let (name, nlist) = symbol?;
+        if nlist.is_global()
+            && nlist.get_type() == N_SECT
+            && nlist.n_sect != NO_SECT as usize
+            && is_introspection_symbol(name)
+        {
+            let section = &sections[nlist.n_sect - 1]; // Sections are counted from 1
```
[the remark this answers is not in the document]
Comment (Tpt) [reply pyo3-introspection/src/introspection.rs:157]: Because there was a section right after with the exact same shift between positions in memory and positions in the file (a lot of Mach-O file do not have any shift and this is the case of the binary generated by maturin/cargo in the CI)

File: pyo3-introspection/src/introspection.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Tpt) [reply pyo3-introspection/src/introspection.rs]: Indeed, thanks

**Review by davidhewitt — APPROVED** [review]
Thanks!
