### PR TITLE
fix `#[pyfunction]` option parsing

### LINKED ISSUE #5012: Basic pyfunction parse error
Try the below snippet, which I believe should be a valid compile:

```rust
#[pyo3::pymodule]
mod pyo3_scratch {
    use pyo3::prelude::*;

    #[pyfunction(crate = "pyo3", name = "f")]
    fn foo() {}
}
```

We get two compile errors:

```rust
error: expected one of: `name`, `pass_module`, `signature`, `text_signature`, `crate`
 --> src/lib.rs:5:32
  |
5 |     #[pyfunction(crate = "pyo3", name = "f")]
  |                                ^

error[E0433]: failed to resolve: use of undeclared crate or module `foo`
 --> src/lib.rs:6:8
  |
6 |     fn foo() {}
  |        ^^^ use of undeclared crate or module `foo`
```

### PR DESCRIPTION
**Pull request by Icxolu**
We did not consume the "," after the `crate` option, so it could only be used as the last one.

Closes #5012

### CODE REVIEW

File: pyo3-macros-backend/src/pyfunction.rs [hunk 1]
```diff
@@ -96,23 +94,8 @@ impl Parse for PyFunctionOptions {
...
-                }
-            } else if lookahead.peek(syn::Token![crate]) {
-                // TODO needs duplicate check?
-                options.krate = Some(input.parse()?);
-            } else {
-                return Err(lookahead.error());
-            }
+        for option in Punctuated::<PyFunctionOption, syn::Token![,]>::parse_terminated(input)? {
+            options.add_attributes([option])?;
         }
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/pyfunction.rs:99]:
```suggestion
        let attrs = Punctuated::<PyFunctionOption, syn::Token![,]>::parse_terminated(input)?;
        options.add_attributes(attrs)?;
```

**Review by davidhewitt — APPROVED** [review]
Thanks, less code and better result! 🎉 

(just tiny golfing suggestion...)

File: pyo3-macros-backend/src/pyfunction.rs (hunk 1 above)
Comment (Icxolu) [reply pyo3-macros-backend/src/pyfunction.rs]: That's even better, thanks!
