### PR TITLE
pyfunction: fix from_py_with on Option<T> argument

### LINKED ISSUE #2280: `from_py_with` doesn't seem to play nicely with optional arguments
### Bug Description

When trying to build optional arguments, using `from_py_with` I'm getting 

```
expected struct `InnerType`, found enum `Option`
```

### Steps to Reproduce

```rs

fn build_regex(obj: &PyAny) -> PyResult<Option<Regex>> {
    if obj.is_none() {
        Ok(None)
    } else {
        let regex_str: &str = obj.extract()?;
        let regex = Regex::new(regex_str).map_err(|e| PyValueError::new_err(e.to_string()))?;
        Ok(Some(regex))
    }
}

#[pyfunction]
pub fn regex_match(
    str: String,
    #[pyo3(from_py_with = "build_regex")] pattern: Option<Regex>,
) -> PyResult<bool> {
    if let Some(pattern) = pattern {
        if !pattern.is_match(&str) {
            return Ok(false);
        }
    }
    Ok(true)
}
```

(I know in this case I could build the regex inside `regex_match` but in practice I want to be able to call `regex_match` from other code with a pre-compiled regex.

### Backtrace

```shell
error[E0308]: mismatched types
  --> src/validators.rs:36:52
   |
36 |     #[pyo3(from_py_with = "build_regex")] pattern: Option<Regex>,
   |                                                    ^^^^^^ expected struct `regex::Regex`, found enum `Option`
   |
   = note: expected struct `regex::Regex`
                found enum `Option<_>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `pydantic-core` due to previous error
```
```


### Your operating system and version

MacOS 12.2.1

### Your Python version (`python --version`)

3.10.4

### Your Rust version (`rustc --version`)

rustc 1.59.0 (9d1b2106e 2022-02-23)

### Your PyO3 version

`{version = "0.16.3", features = ["extension-module"]}`

### How did you install python? Did you use a virtualenv?

pyenv, yes

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by davidhewitt**
This fixes #2280 by making it do the "obvious" thing - an argument `#[pyo3(from_py_with = "foo")] x: Option<i32>` requires `foo` to be a function with returns `PyResult<Option<i32>>`. Turns out there was just a slight typo in the macro-generated code.

### CODE REVIEW

File: tests/test_pyfunction.rs [hunk 1]
```diff
@@ -114,23 +113,20 @@ fn test_functions_with_function_args() {
     });
 }
 
-#[cfg(not(Py_LIMITED_API))]
```
Comment (davidhewitt) [inline tests/test_pyfunction.rs:117]: Not directly related to this PR; just noticed that these attributes are probably not necessary so deleted them.

**Review by messense — APPROVED** [review]
