### PR TITLE
handle `#[pyo3(from_py_with = "")]` in `#[setter]` methods

### LINKED ISSUE #3992: `#[pyo3(from_py_with = "...")]` causes compilation error when used in methods with the `#[setter]` attribute.
### Bug Description

Using the [`from_py_with` per-argument option](https://pyo3.rs/v0.21.0-beta.0/function.html?highlight=from_py_with#per-argument-options) inside a method with the `#[setter]` attribute causes a compilation error despite working fine in constructors and other methods without the setter attribute. The following code reproduces the issue with the error:

```
the trait bound `Field: pyo3::PyClass` is not satisfied
     the trait `pyo3::PyClass` is implemented for `Foo`
     required for `Field` to implement `pyo3::FromPyObject<'_>` [E0277]
```

```rust
use pyo3::prelude::*;

#[derive(Clone)]
struct Field(pub i32);

fn from_py_to_field(value: &PyAny) -> PyResult<Field> {
    let value = value.extract()?;
    Ok(Field(value))
}

#[pyclass]
struct Foo {
    field: Field,
}

#[pymethods]
impl Foo {
    // These compile successfully.
    #[new]
    fn new(#[pyo3(from_py_with = "from_py_to_field")] field: Field) -> Self {
        Self { field }
    }

    fn set_field_fn(&mut self, #[pyo3(from_py_with = "from_py_to_field")] field: Field) {
        self.field = field;
    }

    // This does not compile: "the trait bound `Field: pyo3::PyClass` is not satisfied"
    #[setter]
    fn field(&mut self, #[pyo3(from_py_with = "from_py_to_field")] field: Field) {
        self.field = field
    }
}
``` 

I've tested this in 0.20.3 and 0.21.0-beta.0 with the new `Bound` smart pointer.

### Steps to Reproduce

1. Annotate the argument of a `#[setter]` method with `#[pyo3(from_py_with="..")]` for some argument that doesn't implement `PyClass` (or run the example from the issue).
2. Compile

### Backtrace

_No response_

### Your operating system and version

MacOS Sonoma (M1 Max)

### Your Python version (`python --version`)

N/A

### Your Rust version (`rustc --version`)

rustc 1.76.0 (07dca489a 2024-02-04) 

### Your PyO3 version

0.20.3 and 0.21-beta.0

### How did you install python? Did you use a virtualenv?

I install python with pyenv, but this issue does not require a Python installation or virtual environment to reproduce.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Icxolu**
Fixes #3992 

Handle the `#[pyo3(from_py_with = "")]` attribute in `#[setter]` methods instead of silently ignoring it.

### CODE REVIEW

File: pyo3-macros-backend/src/pymethod.rs [hunk 1]
```diff
@@ -586,6 +586,34 @@ pub fn impl_py_setter_def(
...
+            let _val = #pyo3_path::impl_::extract_argument::from_py_with(
+                &_value.into(),
+                #name,
+                from_py_with as fn(_) -> _,
+            )?;
+        })
+    })
+    .unwrap_or_else(|| {
+        quote! {
+            let _val = #pyo3_path::FromPyObject::extract_bound(_value.into())?;
```
Comment (davidhewitt) [inline pyo3-macros-backend/src/pymethod.rs:613]: I suppose here we probably want to check if `_val` is a GIL Ref, via `holders.push_gil_refs_checker`?

**Review by davidhewitt — APPROVED** [review]
Looks good to me, thanks!

I wonder if the fact that this slipped through means that there's a bigger refactoring overdue, but I'm happy to leave that for a future PR...

File: pyo3-macros-backend/src/pymethod.rs (hunk 1 above)
Comment (davidhewitt) [reply pyo3-macros-backend/src/pymethod.rs:613]: (Either way, I think worthy of its own PR and newsfragment, so I'll merge this PR now.)

**Comment by MarquessV** [comment]
Thanks for the quick fix @Icxolu!

File: pyo3-macros-backend/src/pymethod.rs (hunk 1 above)
Comment (Icxolu) [reply pyo3-macros-backend/src/pymethod.rs:613]: True, maybe I'll take a look at that tomorrow
