### PR TITLE
Deprecate and remove `Py_TRACE_REFS` support

### LINKED ISSUE #5736: Remove Py_TRACE_REFS wrappers
https://github.com/python/cpython/pull/108663 updated the `Py_TRACE_REFS` option to work with the limited API. There were substantial changes to the C API exposed when `Py_TRACE_REFS`, so that means defining `Py_TRACE_REFS` is broken for 3.13 and newer.

Should we perhaps just get rid of the support for the option in PyO3? I don't think it's used much and I suspect the only reason there's a wrapper for it is because `Py_DEBUG` used to also define `Py_TRACE_REFS`

### PR DESCRIPTION
**Pull request by Cheukting**
closes #5736

### CODE REVIEW

File: pyo3-build-config/src/impl_.rs [hunk 1]
```diff
@@ -1147,6 +1147,7 @@ pub fn cross_compiling_from_cargo_env() -> Result<Option<CrossCompileConfig>> {
 pub enum BuildFlag {
     Py_DEBUG,
     Py_REF_DEBUG,
+    #[deprecated = "Not supported since Python 3.13"]
```
Comment (davidhewitt) [inline pyo3-build-config/src/impl_.rs]:
```suggestion
    #[deprecated(since = "0.29.0", note = "no longer supported by PyO3")]
```

Comment (Cheukting) [reply pyo3-build-config/src/impl_.rs]: After in-cooperate this change, there's an error from check-guide. I think it is due to version 0.29.0 does not exist yet
