### PR TITLE
Use a critical section to serialize adding builtins to globals

### LINKED ISSUE #4913: Error: KeyError: '__builtins__' with globals when importing from a callback on Python >= 3.10
### Bug Description

When executing with GIL and running a python code with some globals set, which calls back into rust, then trying to import a module in this lower stack fails with KeyError: '__builtins__'.

### Steps to Reproduce

```rust
use pyo3::types::{PyDictMethods, PyTracebackMethods};

#[pyo3::pyclass]
#[derive(Clone)]
struct Cls {
    code: String,
}

impl Cls {
    fn reproducer(&mut self, py: pyo3::Python) -> pyo3::PyResult<()> {
        let variables = pyo3::types::PyDict::new(py);
        variables.set_item("cls", pyo3::Py::new(py, self.clone())?)?;

        let code = std::ffi::CString::new(self.code.as_str())?;
        let output = py.run(code.as_c_str(), None, Some(&variables));

        if let Err(ref err) = output {
            if let Some(tb) = err.traceback(py) {
                eprint!("{}", tb.format()?);
            }
        }

        output?;

        println!("Running with globals now");

        let output = py.run(code.as_c_str(), Some(&variables), None);

        if let Err(ref err) = output {
            if let Some(tb) = err.traceback(py) {
                eprint!("{}", tb.format()?);
            }
        }

        output?;

        Ok(())
    }
}

#[pyo3::pymethods]
impl Cls {
    fn func(&mut self, py: pyo3::Python) -> pyo3::PyResult<()> {
        /* Importing anything here, even an empty name "" gives the same error */
        py.import("math")?;

        println!("func exec");

        Ok(())
    }

}

fn main() -> eyre::Result<()> {
    let mut cls = Cls {
        code: r#"
cls.func()
"#.to_string(),
    };
    pyo3::prepare_freethreaded_python();

    pyo3::Python::with_gil(|py| {
        /* Importing here works */
        py.import("math")?;

        println!("Imported");

        cls.reproducer(py)
    })?;

    Ok(())
}
```

```toml
[package]
name = "pyo3-test"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6"
pyo3 = "0.23"
```

This will print:
```
Imported
func exec
Running with globals now
Traceback (most recent call last):
  File "<string>", line 2, in <module>
Error: KeyError: '__builtins__'

Location:
    src/main.rs:62:5
```

### Backtrace

```shell
The traceback is not that interesting or helpful:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
Error: KeyError: '__builtins__'
```

### Your operating system and version

Gentoo Linux

### Your Python version (`python --version`)

Python 3.13.2

### Your Rust version (`rustc --version`)

rustc 1.82.0 (f6e511eec 2024-10-15)

### Your PyO3 version

0.23.4

### How did you install python? Did you use a virtualenv?

`emerge python`, no virtualenv

### Additional Info

- This is similar to https://github.com/PyO3/pyo3/issues/3370 with the exception that this is two levels down the stack (`rust->python->rust->py.import()`).
- The issue goes away with the `abi3-py39` feature due to the cfg feature gate in https://github.com/PyO3/pyo3/blob/main/src/marker.rs#L652
- It also did not happen with `pyo3 0.22.3`
- It might be some cpython issue, just like in the #3370 issue, but I hope it can be fixed with just a change in the feature gate in `run_code()` as It would be nice to have this fixed before the 0.24 release in #4905 but I understand that the rabbit hole might ho deeper than I think, so fingers crossed 🤞 it does not.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #4913

Because `PyDict` is a concurrent hash table, it's safe to first check if the dict has a key without holding a critical section then acquire the critical section and fill the dict.

Also adds a test based on the reproducer that I verified fails on `main`.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
I ran `cargo stress` repeatedly for ~10 times to try to trigger any flaky tests due to thread safety issues. I didn't see any failures.

**Comment by nertpinx** [comment]
Works perfectly in our setup as well and looks good to me. Thank you!

File: src/marker.rs [hunk 1]
```diff
@@ -649,30 +648,40 @@ impl<'py> Python<'py> {
...
-                if unsafe { ffi::PyDict_SetItem(globals.as_ptr(), builtins_s, builtins) } == -1 {
+        // If `globals` don't provide `__builtins__`, most of the code will fail if Python
+        // version is <3.10. That's probably not what user intended, so insert `__builtins__`
+        // for them.
+        //
+        // See also:
+        // - https://github.com/python/cpython/pull/24564 (the same fix in CPython 3.10)
+        // - https://github.com/PyO3/pyo3/issues/3370
+        let builtins_s = crate::intern!(self, "__builtins__").as_ptr();
+        let has_builtins = unsafe { ffi::PyDict_Contains(globals.as_ptr(), builtins_s) };
```
Comment (davidhewitt) [inline src/marker.rs:659]: While we're at it, perhaps let's just use safe APIs here?

```suggestion
        let has_builtins = globals.contains(builtins)?;
```

There was once a slight perf advantage where the raw FFI would have avoided a useless reference count incref / decref on the key, but since `IntoPyObject` we can now avoid that cost completely. So the safe API should be zero cost and shorter, safer code.

... and similar below.

**Review by davidhewitt — APPROVED** [review]
