### PR TITLE
Don't expose PyASCIIObjectState on Python3.14 and newer

### LINKED ISSUE #5131: PyUnicode and PyASCII tests are failing on 3.14
See e.g. [here](https://github.com/PyO3/pyo3/actions/runs/14932775845/job/41953621143?pr=5044).

Panics due to hitting unreachable code or failing C API calls. Seems to be new in 3.14.0b1.

```
failures:
      ffi::tests::ascii
      ffi::tests::ucs4
      types::string::tests::test_string_data_ucs1
      types::string::tests::test_string_data_ucs1_invalid
      types::string::tests::test_string_data_ucs2
      types::string::tests::test_string_data_ucs2_invalid
      types::string::tests::test_string_data_ucs4
      types::string::tests::test_string_data_ucs4_invalid
```

I've seen this locally as well but haven't been able to figure out the root cause yet.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #5131.

This changed in between alpha 7 and beta 1: https://github.com/python/cpython/pull/133085

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Also `set_interned` is definitely wrong on the free-threaded build. But also why are we exposing setters at all? The C API doesn't expose setters.

File: pyo3-ffi/src/cpython/unicodeobject.rs [hunk 1]
```diff
@@ -184,115 +186,116 @@ impl PyASCIIObjectState {
...
             .set(STATE_INTERNED_INDEX, STATE_INTERNED_WIDTH, val as u64)
     }
 
     #[inline]
-    #[cfg(Py_3_14)]
-    unsafe fn interned(&self) -> u16 {
-        std::mem::transmute(
+    #[cfg(all(Py_3_14, Py_GIL_DISABLED))]
+    unsafe fn interned(&self) -> u8 {
+        let interned: AtomicU8 = std::mem::transmute(
```
Comment (ngoldbaum) [inline pyo3-ffi/src/cpython/unicodeobject.rs:199]: This feels scary?

**Comment by davidhewitt** [comment]
I wonder, in 3.14 `PyUnicode_KIND` and `PyUnicode_DATA` are now exposed as symbols we can call instead of having to decode the bitfield.

Should we just rip out the bitfield decoding on 3.14 (and up) and instead use the API functions? I think we have to drop a couple of the APIs we currently offer, but overall would be a lot less code to maintain, less coupling to cpython details, and a lot sounder.

**Comment by ngoldbaum** [comment]
> Should we just rip out the bitfield decoding on 3.14 (and up) and instead use the API functions? I think we have to drop a couple of the APIs we currently offer, but overall would be a lot less code to maintain, less coupling to cpython details, and a lot sounder.

Ah neat, guess I should have checked that.

This seems like a good idea, let me see how hard it is...

**Comment by ngoldbaum** [comment]
> This seems like a good idea, let me see how hard it is...

I don't see how to implement `PyUnicode_IS_ASCII`, `PyUnicode_IS_COMPACT` and `PyUnicode_IS_ASCII_COMPACT` without having access to the bitfields....

**Comment by ngoldbaum** [comment]
I can't reproduce the 3.14 windows failures on my Windows setup.

**Comment by davidhewitt** [comment]
> > This seems like a good idea, let me see how hard it is...
> 
> I don't see how to implement `PyUnicode_IS_ASCII`, `PyUnicode_IS_COMPACT` and `PyUnicode_IS_ASCII_COMPACT` without having access to the bitfields....

I was thinking maybe to make those functions inaccessible on 3.14 +?



> I can't reproduce the 3.14 windows failures on my Windows setup.

I will try to find time to look on Monday.

**Comment by clin1234** [comment]
@ngoldbaum Beat me to the punch; can you grant me commit access to your branch? I was thinking of adding a deprecation message to the entire PyASCIIObject (due to https://github.com/python/cpython/pull/133085). Also this: https://github.com/clin1234/pyo3/commit/21ce13279ed8ee434b93e6e6ee36f3519fbf0ff2

**Comment by clin1234** [comment]
Also, this: https://github.com/python/cpython/blob/3.14/Include/cpython/unicodeobject.h#L102-L162
The `state` member has to be aligned in 4-byte boundaries for non-GIL builds, and I don't think the numerous brittle bit-twiddling functions to convert between pyo3's `u32 state` and `struct PyASCIIObjectState` are suitable in the long-term.

**Comment by ngoldbaum** [comment]
The last push removes `PyASCIIObjectState` on Python 3.14 and newer.

I *think* the mysterious Windows failures went away? The remaining failures are unrelated issues in the `jiff` tests.

**Comment by ngoldbaum** [comment]
> I think the mysterious Windows failures went away?

Spoke too soon. Somehow the thing we did with the bindgen `ParseCallbacks` to handle the anonymous struct in the `ob_refcnt` field seems to be breaking, but only on Windows, and only intermittently.

File: pyo3-ffi/src/cpython/unicodeobject.rs [hunk 2]
```diff
@@ -163,19 +161,18 @@ const STATE_READY_WIDTH: u8 = 1;
 ///
 /// Memory layout of C bitfields is implementation defined, so these functions are still
 /// unsafe. Users must verify that they work as expected on the architectures they target.
+#[cfg(not(Py_3_14))]
 #[repr(C)]
```
Comment (davidhewitt) [inline pyo3-ffi/src/cpython/unicodeobject.rs:165]: Was the deletion intentional? Seems probably not given the new cfg.

```suggestion
#[repr(C)]
#[repr(align(4))]
```

File: pyo3-ffi/src/cpython/unicodeobject.rs [hunk 3]
```diff
@@ -383,36 +296,28 @@ pub struct PyASCIIObject {
...
     /// unsigned int :24;
-    ///
-    /// 3.14 and later:
-    /// uint16_t interned;   // SSTATE_* constants.
-    /// unsigned short kind:3; // PyUnicode_*_KIND constants.
-    /// unsigned short compact:1;
-    /// unsigned short ascii:1;
-    /// unsigned int statically_allocated:1;
-    /// unsigned int :10;
+    /// 3.14 and higher don't access the internal state
```
Comment (davidhewitt) [inline pyo3-ffi/src/cpython/unicodeobject.rs:306]:
```suggestion
    /// on 3.14 and higher PyO3 doesn't access the internal state
```

**Review by davidhewitt — COMMENTED** [review]
Thanks, couple of final tweaks and then I think good to merge 👍 

The windows ffi check is at least not going to block merge, so I suggest we merge this, ship 0.25, and investigate / clean up separately.

File: pyo3-ffi/src/cpython/unicodeobject.rs (hunk 2 above)
Comment (ngoldbaum) [reply pyo3-ffi/src/cpython/unicodeobject.rs:165]: Yes, the deletion was intentional. It's only correct to have it on the free-threaded build on 3.14 and newer. If you take a look at definition for `PyASCIIObjectState` in e.g. 3.13 there's no `alignas` use and it's only used in 3.14 on the GIL-disabled build. Since we're not exposing the struct  on 3.14, there's no need to include it.

That said, I honestly don't fully follow the discussion about this in https://github.com/capi-workgroup/decisions/issues/61, so please let me know if you think I'm misunderstanding.

Comment (davidhewitt) [reply pyo3-ffi/src/cpython/unicodeobject.rs:165]: Understood, tests seem to be passing so it seems ok to remove 👍
