### PR TITLE
Also relax the PySequence check when extracting fixed-sized arrays.

### LINKED ISSUE #2674: Cannot extract Rust arrray from NumPy array
I am getting _TypeError: argument 'oned': 'ndarray' object cannot be converted to 'Sequence'_  running test.py with the following files:

src/lib.rs
```
use pyo3::prelude::*;

#[pyclass(module = "rust_module")]
#[derive(Default, Debug, serde::Serialize, serde::Deserialize, Clone)]
pub struct DummyClass{
    name: String,
    oned: [f64;3],
    twod: [[f64;3];3],
}

#[pymethods]
impl DummyClass {
    #[new]
    pub fn pynew(
        name: String,
        oned: [f64;3],
        twod: [[f64;3];3],
    ) -> PyResult<Self>{
        Ok(Self { name, oned, twod})
    }

    fn __call__(&self) -> PyResult<String>{
        Ok("Success".into())
    }
}

#[pymodule]
fn pyo3_pure(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<DummyClass>()?;
    Ok(())
}

```

Cargo.toml

```
[package]
name = "reproduce-extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.17.2", features = ["serde", "abi3-py37", "extension-module"] }
numpy = { version = "^0.17.2" }
serde = { version = "^1.0", features = ["derive"]}

[lib]
name = "pyo3_pure"
crate-type = ["cdylib"]

```

pyproject.toml
```
[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"

[project]
# The name pyo3_pure instead of pyo3-pure is intentional,
# it's used as a crate name resolution regression test
name = "pyo3_pure"
version = "0.1.0"

dependencies = [
    "numpy"
]
```

test.py
```
from pyo3_pure import DummyClass
import numpy as np

# test = DummyClass("hello",[0,0,0],[[0,0,0],[0,0,0],[0,0,0]])
test = DummyClass("hello",np.array([0,0,0]),np.array([[0,0,0],[0,0,0],[0,0,0]]))

print(test())
```

_Originally posted by @Billyangnz in https://github.com/PyO3/pyo3/issues/2615#issuecomment-1273884897_

### PR DESCRIPTION
**Pull request by adamreichold**
Closes #2674

### CODE REVIEW

File: src/conversions/array.rs [hunk 1]
```diff
@@ -61,8 +63,16 @@ mod min_const_generics {
...
     {
-        let seq = <crate::types::PySequence as PyTryFrom>::try_from(obj)?;
-        let seq_len = seq.len()? as usize;
+        // Types that pass `PySequence_Check` usually implement enough of the sequence protocol
+        // to support this function and if not, we will only fail extraction safely.
+        let seq = unsafe {
+            if ffi::PySequence_Check(obj.as_ptr()) != 0 {
+                <PySequence as PyTryFrom>::try_from_unchecked(obj)
+            } else {
+                return Err(PyDowncastError::new(obj, "Sequence").into());
```
Comment (davidhewitt) [inline src/conversions/array.rs:72]: Willing to add a test for this error branch (ie. pass a non-iterable) to get the coverage to 100%? 😃

File: newsfragments/2675.fixed.md [hunk 2]
```diff
@@ -0,0 +1 @@
+`impl FromPyObject for [T; N]` will accept anything passing `PySequence_Check`, e.g. NumPy arrays, in the same way that `impl FromPyObject for Vec<T>` was modified after [#2477](https://github.com/PyO3/pyo3/pull/2477).
```
Comment (davidhewitt) [inline newsfragments/2675.fixed.md:1]: Given this is a revert, I think it'd be quite handy to state what version the behaviour is reverting to rather than the offending PR. Users who want to see the PR can start with the link from the CHANGELOG to this PR and follow the discussion thread.

E.g. "Fix regression of `impl FromPyObject for [T; N]` no longer accepting types passing `PySequence_Check`, e.g. NumPy arrays, since 0.17.0."

**Review by davidhewitt — COMMENTED** [review]
Thanks for handling this, and sorry for my slow reply. My son and I were both sick with colds over the weekend previous and I'm just about getting back up to speed now.

Just a couple of tiny suggestions 👍

File: src/conversions/array.rs (hunk 1 above)
Comment (adamreichold) [reply src/conversions/array.rs:72]: Added a test case triggering this error path.

File: newsfragments/2675.fixed.md (hunk 2 above)
Comment (adamreichold) [reply newsfragments/2675.fixed.md]: Adjusted the wording, please re-review.

**Review by davidhewitt — APPROVED** [review]
Looks great, thanks again! I guess we should put out 0.17.3 - anything else we should include?

**Comment by adamreichold** [comment]
> Looks great, thanks again! I guess we should put out 0.17.3 - anything else we should include?

I don't think we have any other bug fixes ready that are blocked only on review. Everything else seems to be enhancements.

We do have two undiagnosed crash bugs in https://github.com/PyO3/pyo3/issues/2611 and https://github.com/PyO3/pyo3/discussions/26778 though.

Personally, I am not sure if this fix here alone warrants a point release but then again it is a regression. (Turning NumPy arrays into fixed-size Rust arrays seems a bit fringe as NumPy arrays are relatively inefficient for small arrays which is where fixed-size Rust arrays are usually applied.)

**Comment by davidhewitt** [comment]
Ok. Let's hold off for the moment; Python 3.11.0 is due at the end of the month so maybe we can target 0.17.3 for then once we can confirm PyO3 officially supports it. (Unless we can land some bigger features worthy of calling it 0.18!)
