### PR TITLE
Bound 'py lifetime by GILPool in the internal usecases

### LINKED ISSUE #653: Static references to Python objects are allowed, but unsafe
## 🐛 Bug Reports

There is no compile-time check preventing functions wrapped in PyO3 to take `static` references to Python objects. This allows those references to be stored and cause unsafe behavior.

Suggestion: forbid static references at compile-time (if possible), or add some documentation explaining why they shouldn't be used.

### 🌍 Environment

 - Your operating system and version: Archlinux
 - Your python version: 3.7.4
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Repo package + virtualenv
 - Your rust version (`rustc --version`): rustc 1.39.0-nightly (ca3766e2e 2019-09-14)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Yes

### 💥 Reproducing

Rust:
```rust
use pyo3::prelude::*;
use pyo3::types::PyList;

#[pymodule]
fn my_module(_py: Python, m: &PyModule) -> PyResult<()> {

    #[pyclass]
    struct MyClass { list: &'static PyList}

    #[pymethods]
    impl MyClass {

        #[new]
        fn new(obj: &PyRawObject, list: &'static PyList) {
            obj.init({ MyClass { list } });
        }

        fn print(&self) {
            println!("{}", self.list.len()); // KABOOM
        }
    }

    m.add_class::<MyClass>()?;

    Ok(())
}
```

Python :
```
>>> from my_module import MyClass
>>> obj = MyClass([1, 2, 3])
>>> obj.print()
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by kngwyu**
Fixes #653. 
By using `GILPool::py` instead of `Python::assume_gil_acquired`, we can inhivit `&'static` reference as an argument.
This PR also pushes some cleanups around `POOL`.

### CODE REVIEW

File: src/gil.rs [hunk 1]
```diff
@@ -187,42 +176,65 @@ impl ReleasePool {
...
+    value: UnsafeCell<Option<ReleasePoolImpl>>,
+}
+
+impl ReleasePool {
+    const fn new() -> Self {
+        Self {
+            value: UnsafeCell::new(None),
+        }
+    }
+    unsafe fn get_or_init(&self) -> &mut ReleasePoolImpl {
```
Comment (davidhewitt) [inline src/gil.rs:189]: It looks like this function isn't thread safe, so I guess you intended for this to be only used alongside the GIL to ensure no race conditions.

```suggestion
    /// # Safety
    /// This function should only be used when the GIL is acquired, to ensure thread safety.
    unsafe fn get_or_init(&self) -> &mut ReleasePoolImpl {
```

File: src/gil.rs [hunk 2]
```diff
@@ -187,42 +176,65 @@ impl ReleasePool {
...
+        if (*self.value.get()).is_none() {
+            *self.value.get() = Some(ReleasePoolImpl::new());
+        }
+        (*self.value.get()).as_mut().unwrap()
```
Comment (davidhewitt) [inline src/gil.rs:193]:
```suggestion
        (*self.value).get_or_insert_with(ReleasePoolImpl::new)
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -10,8 +10,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 ### Changed
 
 * `PyObject` and `Py<T>` reference counts are now decremented sooner after `drop()`. [#851](https://github.com/PyO3/pyo3/pull/851)
-  * When the GIL is held, the refcount is now decreased immediately on drop. (Previously would wait until just before releasing the GIL.)
-  * When the GIL is not held, the refcount is now decreased when the GIL is next acquired. (Previously would wait until next time the GIL was released.)
```
Comment (davidhewitt) [inline CHANGELOG.md:14]: Why did you remove the second bullet?

File: src/gil.rs [hunk 4]
```diff
@@ -187,42 +176,65 @@ impl ReleasePool {
...
+unsafe impl Sync for ReleasePool {}
 
 #[doc(hidden)]
-pub struct GILPool<'p> {
-    py: Python<'p>,
+pub struct GILPool {
     owned: usize,
     borrowed: usize,
     no_send: Unsendable,
 }
```
Comment (davidhewitt) [inline src/gil.rs:206]: Now that GILPool doesn't have `py`, I think we can change GILGuard to be 

```
struct GILGuard {
    gstate: ffi::PyGILState_State,
    pool: GILPool
}
```

and then we can simplify _a lot_ of the duplication in this file.

File: src/gil.rs [hunk 5]
```diff
@@ -187,42 +176,65 @@ impl ReleasePool {
...
-impl<'p> GILPool<'p> {
+impl GILPool {
+    /// # Safety
+    /// This function requires that GIL is already acquired.
     #[inline]
-    pub fn new(py: Python) -> GILPool {
+    pub unsafe fn new() -> GILPool {
         increment_gil_count();
-        let p: &'static mut ReleasePool = unsafe { &mut *POOL };
+        let pool = POOL.get_or_init();
```
Comment (davidhewitt) [inline src/gil.rs:214]: Oh, I think I missed a `release_pointers()` call here:

```suggestion
        // Release objects that were dropped since last GIL acquisition
        let pool = POOL.get_or_init();
        pool.release_pointers();
```

Maybe this is why you removed the second bullet from the CHANGELOG?

File: src/gil.rs [hunk 6]
```diff
@@ -187,42 +176,65 @@ impl ReleasePool {
...
     no_send: Unsendable,
 }
 
-impl<'p> GILPool<'p> {
+impl GILPool {
+    /// # Safety
+    /// This function requires that GIL is already acquired.
     #[inline]
-    pub fn new(py: Python) -> GILPool {
+    pub unsafe fn new() -> GILPool {
```
Comment (davidhewitt) [inline src/gil.rs:212]: 👍 I agree this is unsafe - and nice use of `# Safety`.

File: tests/ui/static_ref.stderr [hunk 7]
```diff
@@ -0,0 +1,11 @@
...
+ --> $DIR/static_ref.rs:9:1
+  |
+9 | #[pymethods]
+  | ^^^^^^^^^^^-
+  | |          |
+  | |          `_pool` dropped here while still borrowed
+  | borrowed value does not live long enough
+  | cast requires that `_pool` is borrowed for `'static`
+  |
+  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
Comment (davidhewitt) [inline tests/ui/static_ref.stderr:11]: Looks like this `note` was added in early feb: https://github.com/rust-lang/rust/commit/26c86a6a2828b1048fa2fd425595ef8fb475249a

So might need to bump minimum rust version slightly to keep travis happy?

**Comment by davidhewitt** [comment]
Should we add a `# Safety` doc to `Python::assume_gil_acquired()` to specifically mention that `'static` lifetimes can easily be inferred but are never safe? Then this PR can probably also resolve #800 for now.

File: CHANGELOG.md (hunk 3 above)
Comment (kngwyu) [reply CHANGELOG.md:14]: Ah, sorry, I didn't notice that these two lines point out different things.

File: src/gil.rs (hunk 2 above)
Comment (kngwyu) [reply src/gil.rs:193]: :+1:

File: src/gil.rs (hunk 4 above)
Comment (kngwyu) [reply src/gil.rs:206]: Seems nice :+1:

File: tests/ui/static_ref.stderr (hunk 7 above)
Comment (kngwyu) [reply tests/ui/static_ref.stderr:11]: Yeah, but since to find the minimum nightly by binary search is really hard, I just skip the test using `TRAVIS_JOB_NAME`.

**Comment by kngwyu** [comment]
@davidhewitt 
Thank you for comments!
I think they are all addressed now.

File: CHANGELOG.md [hunk 8]
```diff
@@ -10,8 +10,8 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
...
+* When the GIL is held, the refcount is now decreased immediately on drop. (Previously would wait until just before releasing the GIL.)
+* When the GIL is not held, the refcount is now decreased when the GIL is next acquired. (Previously would wait until next time the GIL was released.)
```
Comment (davidhewitt) [inline CHANGELOG.md:14]: I meant these bullet points to be sub-bullets of the one above. But maybe you prefer them flattened?

```suggestion
  * When the GIL is held, the refcount is now decreased immediately on drop. (Previously would wait until just before releasing the GIL.)
  * When the GIL is not held, the refcount is now decreased when the GIL is next acquired. (Previously would wait until next time the GIL was released.)
```

File: CHANGELOG.md [hunk 9]
```diff
@@ -20,6 +20,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 ### Fixed
 * `__radd__` and other `__r*__` methods now correctly work with operators. [#839](https://github.com/PyO3/pyo3/pull/839)
 * Garbage Collector causing random panics when traversing objects that were mutably borrowed. [#855](https://github.com/PyO3/pyo3/pull/855)
+* `&'static Py~` is not allowed as arguments. [#869](https://github.com/PyO3/pyo3/pull/869)
```
Comment (davidhewitt) [inline CHANGELOG.md:23]:
```suggestion
* `&'static Py~` being allowed as arguments. [#869](https://github.com/PyO3/pyo3/pull/869)
```

File: src/python.rs [hunk 10]
```diff
@@ -57,6 +57,10 @@ impl<'p> Python<'p> {
     /// Because the output lifetime `'p` is not connected to any input parameter,
     /// care must be taken that the compiler infers an appropriate lifetime for `'p`
     /// when calling this function.
+    ///
+    /// # Safety
+    /// The lifetime `'p` must be shorter than the period you *assume* that you have GIL.
+    /// I.e., `Python<'static>` is always *really* unsafe.
```
Comment (davidhewitt) [inline src/python.rs:63]: 👍 nice. Not sure the comma is necessary.

```suggestion
    /// I.e. `Python<'static>` is always *really* unsafe.
```

File: CHANGELOG.md (hunk 8 above)
Comment (kngwyu) [reply CHANGELOG.md:14]: Ah, sorry again, I was not aware of how they are structured.

File: src/python.rs (hunk 10 above)
Comment (kngwyu) [reply src/python.rs:63]: I didn't know but it looks a matter of Blitish/American English https://english.stackexchange.com/questions/6894/should-there-be-a-comma-after-i-e

Comment (davidhewitt) [reply src/python.rs:63]: Heh that makes sense with me being British 😂
